/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, March 22, 2014 at 3:02:46 PM Central European Standard Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol AmazonServiceRequestDelegate
@optional
-(void)request(id):arg1 didReceiveResponse(id):arg2 ;
-(void)request(id):arg1 didReceiveData(id):arg2 ;
-(void)request(id):arg1 didCompleteWithResponse(id):arg2 ;
-(void)request(id):arg1 didSendData(int):arg2 totalBytesWritten(int):arg3 totalBytesExpectedToWrite(int):arg4 ;
-(void)request(id):arg1 didFailWithServiceException(id):arg2 ;
-(void)request(id):arg1 didFailWithError(id):arg2 ;
@end
