/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, March 22, 2014 at 2:44:49 PM Central European Standard Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface AmazonSimpleDBClient : AmazonWebServiceClient {
}
-(id)initWithAccessKey:(id)arg1 withSecretKey:(id)arg2;
-(id)putAttributes:(id)arg1;
-(id)batchDeleteAttributes:(id)arg1;
-(id)deleteDomain:(id)arg1;
-(id)createDomain:(id)arg1;
-(id)deleteAttributes:(id)arg1;
-(id)listDomains:(id)arg1;
-(id)getAttributes:(id)arg1;
-(id)batchPutAttributes:(id)arg1;
-(id)domainMetadata:(id)arg1;
-(id)initWithCredentials:(id)arg1;
-(id)select:(id)arg1;
@end