/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, March 22, 2014 at 3:02:03 PM Central European Standard Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface APLSimpleEditor : NSObject {
	NSArray* _clips; 
	NSArray* _clipTimeRanges; 
	AVMutableComposition* _composition; 
	AVMutableVideoComposition* _videoComposition; 
	AVMutableAudioMix* _audioMix; 
	struct {
		long long value;
		int timescale;
		unsigned flags;
		long long epoch;
	} _transitionDuration; 
}
@property (nonatomic,copy) NSArray* clips; 				//@synthesize clips=_clips - In the implementation block
@property (nonatomic,copy) NSArray* clipTimeRanges; 				//@synthesize clipTimeRanges=_clipTimeRanges - In the implementation block
@property (assign,nonatomic) struct transitionDuration; 				//@synthesize transitionDuration=_transitionDuration - In the implementation block
@property (nonatomic,retain) AVMutableComposition* composition; 				//@synthesize composition=_composition - In the implementation block
@property (nonatomic,retain) AVMutableVideoComposition* videoComposition; 				//@synthesize videoComposition=_videoComposition - In the implementation block
@property (nonatomic,retain) AVMutableAudioMix* audioMix; 				//@synthesize audioMix=_audioMix - In the implementation block
-(void)buildTransitionComposition:(id)arg1 andVideoComposition:(id)arg2 andAudioMix:(id)arg3;
-(void)buildCompositionObjectsForPlayback;
-(id)getPlayerItem;
-(void)setClips:(id)arg1;
-(void)setClipTimeRanges:(id)arg1;
-(void)setTransitionDuration:(struct )arg1;
-(void)setVideoComposition:(id)arg1;
-(void)setComposition:(id)arg1;
-(void)setAudioMix:(id)arg1;
-(void).cxx_destruct;
@end