/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, March 22, 2014 at 2:59:59 PM Central European Standard Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface CLSIcon : NSObject {
	NSData* _data; 
	NSString* _dataHash; 
	CGSize _size; 
	BOOL _prerendered; 
}
@property (nonatomic,copy) NSData* data; 				//@synthesize data=_data - In the implementation block
@property (nonatomic,copy) NSString* dataHash; 				//@synthesize dataHash=_dataHash - In the implementation block
@property (nonatomic,copy) CGSize size; 				//@synthesize size=_size - In the implementation block
@property (nonatomic,copy) BOOL prerendered; 				//@synthesize prerendered=_prerendered - In the implementation block
@property (nonatomic,copy) float surfaceArea; 
@property (nonatomic,copy) BOOL isWithinMaxSurfaceArea; 
+(BOOL)isWithinMaxSurfaceAreaWithImage:(id)arg1;
-(id)initWithPNGImageAtPath:(id)arg1 size:(CGSize)arg2 prerendered:(BOOL)arg3;
-(id)initWithData:(id)arg1 dataHash:(id)arg2 size:(CGSize)arg3 prerendered:(BOOL)arg4;
-(id)initWithData:(id)arg1 size:(CGSize)arg2 prerendered:(BOOL)arg3;
-(BOOL)largerThanSize:(CGSize)arg1;
-(void)dealloc;
-(id)init;
-(id)initWithData:(id)arg1 size:(CGSize)arg2;
@end