/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, March 22, 2014 at 3:01:09 PM Central European Standard Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface EC2CreateImageRequest : AmazonServiceRequestConfig {
	NSString* instanceId; 
	NSString* name; 
	NSString* descriptionValue; 
	_Bool noReboot; 
	_Bool noRebootIsSet; 
	NSMutableArray* blockDeviceMappings; 
}
@property (nonatomic,retain) NSString* instanceId; 
@property (nonatomic,retain) NSString* name; 
@property (nonatomic,retain) NSString* descriptionValue; 
@property (assign,nonatomic) _Bool noReboot; 
@property (nonatomic,copy) _Bool noRebootIsSet; 
@property (nonatomic,retain) NSMutableArray* blockDeviceMappings; 
-(void)addBlockDeviceMapping:(id)arg1;
-(void)setBlockDeviceMappings:(id)arg1;
-(void)setInstanceId:(id)arg1;
-(id)initWithInstanceId:(id)arg1 andName:(id)arg2;
-(void)setNoReboot:(_Bool)arg1;
-(void)setDescriptionValue:(id)arg1;
-(void)dealloc;
-(id)init;
-(void)setName:(id)arg1;
@end