/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, March 22, 2014 at 3:00:26 PM Central European Standard Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface EC2VolumeStatusInfo : NSObject {
	NSString* status; 
	NSMutableArray* details; 
}
@property (nonatomic,retain) NSString* status; 
@property (nonatomic,retain) NSMutableArray* details; 
-(void)addDetail:(id)arg1;
-(void)dealloc;
-(id)init;
-(id)description;
-(void)setStatus:(id)arg1;
-(void)setDetails:(id)arg1;
@end