/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, March 22, 2014 at 3:01:56 PM Central European Standard Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface ElasticLoadBalancingInstance : NSObject {
	NSString* instanceId; 
}
@property (nonatomic,retain) NSString* instanceId; 
-(void)setInstanceId:(id)arg1;
-(id)initWithInstanceId:(id)arg1;
-(void)dealloc;
-(id)init;
-(id)description;
@end