/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, March 22, 2014 at 3:00:22 PM Central European Standard Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface ElasticLoadBalancingCreateLoadBalancerPolicyRequest : AmazonServiceRequestConfig {
	NSString* loadBalancerName; 
	NSString* policyName; 
	NSString* policyTypeName; 
	NSMutableArray* policyAttributes; 
}
@property (nonatomic,retain) NSString* loadBalancerName; 
@property (nonatomic,retain) NSString* policyName; 
@property (nonatomic,retain) NSString* policyTypeName; 
@property (nonatomic,retain) NSMutableArray* policyAttributes; 
-(void)addPolicyAttribute:(id)arg1;
-(void)setPolicyTypeName:(id)arg1;
-(void)setPolicyAttributes:(id)arg1;
-(void)setLoadBalancerName:(id)arg1;
-(void)setPolicyName:(id)arg1;
-(void)dealloc;
-(id)init;
-(id)description;
@end