/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, March 22, 2014 at 3:02:13 PM Central European Standard Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface ElasticLoadBalancingDescribeInstanceHealthRequest : AmazonServiceRequestConfig {
	NSString* loadBalancerName; 
	NSMutableArray* instances; 
}
@property (nonatomic,retain) NSString* loadBalancerName; 
@property (nonatomic,retain) NSMutableArray* instances; 
-(id)initWithLoadBalancerName:(id)arg1;
-(void)setLoadBalancerName:(id)arg1;
-(void)addInstance:(id)arg1;
-(void)setInstances:(id)arg1;
-(void)dealloc;
-(id)init;
-(id)description;
@end