/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, March 22, 2014 at 2:45:25 PM Central European Standard Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface FBCrypto : NSObject {
	NSData* _encryptionKeyData; 
	NSData* _macKeyData; 
}
+(id)randomBytes:(unsigned)arg1;
+(id)makeMasterKey;
-(id)_macForIV:(id)arg1 cipherData:(id)arg2 additionalDataToSign:(id)arg3;
-(id)initWithMasterKey:(id)arg1;
-(id)initWithEncryptionKey:(id)arg1 macKey:(id)arg2;
-(id)encrypt:(id)arg1 additionalDataToSign:(id)arg2;
-(id)decrypt:(id)arg1 additionalSignedData:(id)arg2;
-(void)dealloc;
@end