/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, March 22, 2014 at 3:01:59 PM Central European Standard Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface S3CompleteMultipartUploadResponse : S3Response {
	S3CompleteMultipartUploadResult* completeMultipartUploadResult; 
}
@property (nonatomic,copy) S3CompleteMultipartUploadResult* completeMultipartUploadResult; 
-(void)processBody;
-(void)dealloc;
@end