/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, March 22, 2014 at 3:00:16 PM Central European Standard Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface S3SetBucketCrossOriginRequest : S3Request {
	S3BucketCrossOriginConfiguration* configuration; 
}
@property (nonatomic,retain) S3BucketCrossOriginConfiguration* configuration; 
+(id)requestWithBucketName:(id)arg1;
+(id)requestWithBucketName:(id)arg1 withConfiguration:(id)arg2;
-(id)configureURLRequest;
-(id)initWithBucketName:(id)arg1;
-(id)initWithBucketName:(id)arg1 withConfiguration:(id)arg2;
-(void)dealloc;
-(void)setConfiguration:(id)arg1;
@end