/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, March 22, 2014 at 2:44:43 PM Central European Standard Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface TFDeviceInfo : NSObject {
}
+(id)carrier;
+(id)machine;
+(id)connectivityState;
+(void)addCustomEnvironmentInformation:(id)arg1 forKey:(id)arg2;
+(id)deviceInformation;
+(id)orientation;
+(void)initialize;
+(id)batteryState;
+(void)setDeviceIdentifier:(id)arg1;
+(id)architecture;
@end