/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, March 22, 2014 at 3:00:54 PM Central European Standard Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface VNComposedAsset : NSObject {
	AVComposition* _asset; 
	AVVideoComposition* _videoComposition; 
	AVAudioMix* _audioMix; 
}
@property (nonatomic,retain) AVComposition* asset; 				//@synthesize asset=_asset - In the implementation block
@property (nonatomic,retain) AVVideoComposition* videoComposition; 				//@synthesize videoComposition=_videoComposition - In the implementation block
@property (nonatomic,retain) AVAudioMix* audioMix; 				//@synthesize audioMix=_audioMix - In the implementation block
-(id)asExportSession:(unsigned long long*)arg1;
-(id)asPlayerItem;
-(void)setVideoComposition:(id)arg1;
-(void)setAsset:(id)arg1;
-(void)setAudioMix:(id)arg1;
-(void).cxx_destruct;
@end