/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, March 22, 2014 at 3:01:38 PM Central European Standard Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface VNFontButton : UIButton {
}
-(void)sizeToFitLabelExpandLeft;
-(void)sizeToFitLabelExpandRight;
-(id)initWithFrame:(CGRect)arg1;
-(id)initWithCoder:(id)arg1;
-(id)init;
-(void)awakeFromNib;
-(id)getFontName;
-(void)bootstrap;
@end