/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, March 22, 2014 at 3:02:13 PM Central European Standard Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface VNGroupedTableView : UITableView {
}
+(float)defaultCellHeightForIndexPath:(id)arg1;
+(id)cellForRowAtIndexPath:(id)arg1 dequeuedFromTableView:(id)arg2 customIdentifier:(id)arg3;
+(id)adjustedIndexPath:(id)arg1 tableView:(id)arg2;
+(id)textFieldWithDelegate:(id)arg1;
@end