/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, March 22, 2014 at 3:01:38 PM Central European Standard Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface VNLoginView : UIView {
	UILabel* _title; 
	UIButton* _backButton; 
	UIImageView* _navBar; 
}
@property (nonatomic,retain) UILabel* title; 				//@synthesize title=_title - In the implementation block
@property (nonatomic,retain) UIButton* backButton; 				//@synthesize backButton=_backButton - In the implementation block
@property (nonatomic,retain) UIImageView* navBar; 				//@synthesize navBar=_navBar - In the implementation block
+(void)alignViews:(id)arg1 rootView:(id)arg2 offset:(float)arg3 keyboard:(BOOL)arg4;
+(void)alignViews:(id)arg1 rootView:(id)arg2 offset:(float)arg3 keyboard:(BOOL)arg4 accountForScreenSize:(BOOL)arg5;
-(void)keyboardAppear;
-(void)keyboardDisappear;
-(void)setBackButton:(id)arg1;
-(void)setNavBar:(id)arg1;
-(void)setTitle:(id)arg1;
-(void)awakeFromNib;
-(void).cxx_destruct;
@end