/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, March 22, 2014 at 3:02:24 PM Central European Standard Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <MKMapViewDelegate.h>

@interface VNVenueFeedViewController : VNBasicFeedViewController <MKMapViewDelegate> {
	VNLoaderView* _loaderView; 
	NSString* _nameHint; 
	NSString* _venueID; 
	MKMapView* _mapView; 
	UIView* _headerView; 
	VNVenueService* _venueService; 
	VNVenue* _venue; 
}
@property (nonatomic,retain) NSString* nameHint; 				//@synthesize nameHint=_nameHint - In the implementation block
@property (nonatomic,retain) NSString* venueID; 				//@synthesize venueID=_venueID - In the implementation block
@property (nonatomic,retain) MKMapView* mapView; 				//@synthesize mapView=_mapView - In the implementation block
@property (nonatomic,retain) UIView* headerView; 				//@synthesize headerView=_headerView - In the implementation block
@property (nonatomic,retain) VNVenueService* venueService; 				//@synthesize venueService=_venueService - In the implementation block
@property (nonatomic,retain) VNVenue* venue; 				//@synthesize venue=_venue - In the implementation block
-(void)setVenue:(id)arg1;
-(id)initWithVenueID:(id)arg1;
-(void)createHeaderView;
-(void)setVenueService:(id)arg1;
-(void)setNameHint:(id)arg1;
-(void)setVenueID:(id)arg1;
-(void)dealloc;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1;
-(void)viewWillDisappear:(BOOL)arg1;
-(void)setHeaderView:(id)arg1;
-(void)setMapView:(id)arg1;
-(id)mapView:(id)arg1 viewForAnnotation:(id)arg2;
-(void).cxx_destruct;
@end