/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, March 22, 2014 at 2:59:55 PM Central European Standard Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol VNVideoTableViewCellDelegate
@required
-(void)videoTableViewCellMoreCommentsButtonWasTapped(id):arg1 ;
-(void)videoTableViewCellCommentButtonWasTapped(id):arg1 ;
-(void)videoTableViewCellLikesButtonWasTapped(id):arg1 ;
-(void)videoTableViewCellRepostsButtonWasTapped(id):arg1 ;
-(void)videoTableViewCellAuthorButtonWasTapped(id):arg1 ;
-(void)videoTableViewCellUserWasTapped(id):arg1 user(id):arg2 ;
-(void)videoTableViewCellLocationWasTapped(id):arg1 ;
-(void)videoTableViewCellDidDeletePost(id):arg1 ;
-(void)videoTableViewCellMoreCommentsButtonWasTapped(id):arg1 ;
-(void)videoTableViewCellCommentButtonWasTapped(id):arg1 ;
-(void)videoTableViewCellLikesButtonWasTapped(id):arg1 ;
-(void)videoTableViewCellRepostsButtonWasTapped(id):arg1 ;
-(void)videoTableViewCellAuthorButtonWasTapped(id):arg1 ;
-(void)videoTableViewCellUserWasTapped(id):arg1 user(id):arg2 ;
-(void)videoTableViewCellLocationWasTapped(id):arg1 ;
-(void)videoTableViewCellDidDeletePost(id):arg1 ;
@end
