//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface CommunicationDisplayViewController : UIViewController
{
}

+ (_Bool)shouldRelock;
+ (_Bool)starkUnlocked;
+ (_Bool)lockWasInterrupted;
+ (_Bool)springBoardIsLocked;
- (void)_postOkToRelock;
- (_Bool)_shouldRelock;
- (_Bool)isShowingLock;
- (_Bool)_springboardIsLocked;
- (_Bool)_lockWasInterrupted;

@end

