//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PhoneApplication.h"

@interface PhoneApplication (Private)
- (void)requestSuspendAfterLastCall;
- (void)requestSuspendWithTransparencyAfterLastCall;
- (void)_forceWindowFront;
@end

