/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllPeople.h"

#import "CLLocationManagerDelegate-Protocol.h"
#import "MKMapViewDelegate-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class CLLocationManager, MKMapView, MapSearchViewController, MapsDetailsViewController, NSDate, NSMutableArray, NSString, NSTimer, UIActivityIndicatorView, UIButton, UIImageView, UILabel, UITableView, UIViewController;

@interface MapPageViewController : _ABAddressBookCopyArrayOfAllPeople <MKMapViewDelegate, UITableViewDataSource, UITableViewDelegate, CLLocationManagerDelegate, UIAlertViewDelegate>
{
    MKMapView *mapView;
    NSMutableArray *reports;
    NSMutableArray *listOfMapPlaces;
    float latitude;
    float longitude;
    double region_span_latitudeDelta;
    double region_span_longitudeDelta;
    CLLocationManager *locationManager;
    NSString *lat;
    NSString *lon;
    NSDate *locationManagerStartDate;
    BOOL haveAlreadyReceivedCoordinates;
    BOOL gps_kCLErrorLocationUnknown;
    BOOL gps_kCLErrorDenied;
    BOOL notif_egain_open;
    BOOL notif_campaigns_open;
    BOOL side;
    BOOL side2;
    UITableView *table1;
    UIButton *btn1;
    UIButton *btn2;
    UIButton *btn3;
    int maps_TAB_NEARESTLIST;
    int maps_TAB_NEARESTMAP;
    int maps_TAB_SEARCH;
    int maps_TAB_SELECTION;
    UIButton *topL_services;
    UIButton *topR_msisdns;
    UILabel *numlb1;
    UILabel *numlb2;
    UIImageView *numlb2ImgView;
    UIViewController *rightview;
    UIViewController *leftview;
    NSTimer *mytimer;
    UIButton *transparentButton;
    UIActivityIndicatorView *spinner;
    UILabel *loading;
    MapsDetailsViewController *MapsDetailsView;
    MapSearchViewController *MapSearchView;
}

- (void)setMapSearchView:(id)fp8;
- (id)MapSearchView;
- (void)setMapsDetailsView:(id)fp8;
- (id)MapsDetailsView;
- (void)setLoading:(id)fp8;
- (id)loading;
- (void)setSpinner:(id)fp8;
- (id)spinner;
- (void)setTransparentButton:(id)fp8;
- (id)transparentButton;
- (void)setMytimer:(id)fp8;
- (id)mytimer;
- (void)setSide2:(BOOL)fp8;
- (BOOL)side2;
- (void)setSide:(BOOL)fp8;
- (BOOL)side;
- (void)setLeftview:(id)fp8;
- (id)leftview;
- (void)setRightview:(id)fp8;
- (id)rightview;
- (void)setNumlb2ImgView:(id)fp8;
- (id)numlb2ImgView;
- (void)setNumlb2:(id)fp8;
- (id)numlb2;
- (void)setNumlb1:(id)fp8;
- (id)numlb1;
- (void)setTopR_msisdns:(id)fp8;
- (id)topR_msisdns;
- (void)setTopL_services:(id)fp8;
- (id)topL_services;
- (void)setNotif_campaigns_open:(BOOL)fp8;
- (BOOL)notif_campaigns_open;
- (void)setNotif_egain_open:(BOOL)fp8;
- (BOOL)notif_egain_open;
- (void)setGps_kCLErrorDenied:(BOOL)fp8;
- (BOOL)gps_kCLErrorDenied;
- (void)setGps_kCLErrorLocationUnknown:(BOOL)fp8;
- (BOOL)gps_kCLErrorLocationUnknown;
- (void)setHaveAlreadyReceivedCoordinates:(BOOL)fp8;
- (BOOL)haveAlreadyReceivedCoordinates;
- (void)setLocationManagerStartDate:(id)fp8;
- (id)locationManagerStartDate;
- (void)setLon:(id)fp8;
- (id)lon;
- (void)setLat:(id)fp8;
- (id)lat;
- (void)setLongitude:(float)fp8;
- (float)longitude;
- (void)setLatitude:(float)fp8;
- (float)latitude;
- (void)setListOfMapPlaces:(id)fp8;
- (id)listOfMapPlaces;
- (void)setReports:(id)fp8;
- (id)reports;
- (void)setMapView:(id)fp8;
- (id)mapView;
- (void)setMaps_TAB_SELECTION:(int)fp8;
- (int)maps_TAB_SELECTION;
- (void)setMaps_TAB_SEARCH:(int)fp8;
- (int)maps_TAB_SEARCH;
- (void)setMaps_TAB_NEARESTMAP:(int)fp8;
- (int)maps_TAB_NEARESTMAP;
- (void)setMaps_TAB_NEARESTLIST:(int)fp8;
- (int)maps_TAB_NEARESTLIST;
- (void)setBtn3:(id)fp8;
- (id)btn3;
- (void)setBtn2:(id)fp8;
- (id)btn2;
- (void)setBtn1:(id)fp8;
- (id)btn1;
- (void)setTable1:(id)fp8;
- (id)table1;
- (void).cxx_destruct;
- (void)locationManager:(id)fp8 didUpdateToLocation:(id)fp12 fromLocation:(id)fp16;
- (void)locationManager:(id)fp8 didFailWithError:(id)fp12;
- (void)stopUpdatingLocationCosmote;
- (void)getlocation;
- (void)opennotifications_campaigns:(id)fp8;
- (void)opennotifications_egain:(id)fp8;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;
- (void)removeleftview;
- (void)removerightview;
- (void)openleftside_code;
- (void)openleftside:(id)fp8;
- (void)openrightside_code;
- (void)openrightside:(id)fp8;
- (void)centerMap;
- (void)alertView:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (void)mapView:(id)fp8 annotationView:(id)fp12 calloutAccessoryControlTapped:(id)fp16;
- (void)showMapApp:(id)fp8;
- (id)mapView:(id)fp8 viewForAnnotation:(id)fp12;
- (void)placePins;
- (void)mapViewDidFinishLoadingMap:(id)fp8;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)viewDidUnload;
- (void)searchact:(id)fp8;
- (void)mapact:(id)fp8;
- (void)listact:(id)fp8;
- (void)transparentButtonAct:(id)fp8;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (float)tableView:(id)fp8 heightForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (void)buildHeader;
- (void)BuildMap;
- (void)makeHTTPConn;
- (void)GoToRoot;
- (void)fetchGPS;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidLoad;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;

@end

