/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllPeople.h"

@class NSTimer, UIActivityIndicatorView, UIButton, UIImageView, UILabel, UIView, UIViewController;

@interface MyBillDetailsViewController : _ABAddressBookCopyArrayOfAllPeople
{
    BOOL notif_egain_open;
    BOOL notif_campaigns_open;
    BOOL side;
    BOOL side2;
    UILabel *lb1;
    UILabel *lb2;
    UILabel *lb3;
    UILabel *lb4;
    UILabel *statlb1;
    UILabel *statlb2;
    UILabel *statlb3;
    UILabel *statlb4;
    UILabel *color_lb1;
    UILabel *color_lb2;
    UILabel *color_lb3;
    UILabel *color_lb4;
    UILabel *genlb1;
    UILabel *genlb2;
    UIView *graphview;
    UIButton *topL_services;
    UIButton *topR_msisdns;
    UILabel *numlb1;
    UILabel *numlb2;
    UIImageView *numlb2ImgView;
    UIViewController *rightview;
    UIViewController *leftview;
    NSTimer *mytimer;
    UIActivityIndicatorView *spinner;
    UILabel *loading;
}

- (void)setLoading:(id)fp8;
- (id)loading;
- (void)setSpinner:(id)fp8;
- (id)spinner;
- (void)setMytimer:(id)fp8;
- (id)mytimer;
- (void)setSide2:(BOOL)fp8;
- (BOOL)side2;
- (void)setSide:(BOOL)fp8;
- (BOOL)side;
- (void)setLeftview:(id)fp8;
- (id)leftview;
- (void)setRightview:(id)fp8;
- (id)rightview;
- (void)setNumlb2ImgView:(id)fp8;
- (id)numlb2ImgView;
- (void)setNumlb2:(id)fp8;
- (id)numlb2;
- (void)setNumlb1:(id)fp8;
- (id)numlb1;
- (void)setTopR_msisdns:(id)fp8;
- (id)topR_msisdns;
- (void)setTopL_services:(id)fp8;
- (id)topL_services;
- (void)setNotif_campaigns_open:(BOOL)fp8;
- (BOOL)notif_campaigns_open;
- (void)setNotif_egain_open:(BOOL)fp8;
- (BOOL)notif_egain_open;
- (void)setGraphview:(id)fp8;
- (id)graphview;
- (void)setGenlb2:(id)fp8;
- (id)genlb2;
- (void)setGenlb1:(id)fp8;
- (id)genlb1;
- (void)setColor_lb4:(id)fp8;
- (id)color_lb4;
- (void)setColor_lb3:(id)fp8;
- (id)color_lb3;
- (void)setColor_lb2:(id)fp8;
- (id)color_lb2;
- (void)setColor_lb1:(id)fp8;
- (id)color_lb1;
- (void)setStatlb4:(id)fp8;
- (id)statlb4;
- (void)setStatlb3:(id)fp8;
- (id)statlb3;
- (void)setStatlb2:(id)fp8;
- (id)statlb2;
- (void)setStatlb1:(id)fp8;
- (id)statlb1;
- (void)setLb4:(id)fp8;
- (id)lb4;
- (void)setLb3:(id)fp8;
- (id)lb3;
- (void)setLb2:(id)fp8;
- (id)lb2;
- (void)setLb1:(id)fp8;
- (id)lb1;
- (void).cxx_destruct;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)viewDidUnload;
- (void)opennotifications_campaigns:(id)fp8;
- (void)opennotifications_egain:(id)fp8;
- (void)removeleftview;
- (void)removerightview;
- (void)openleftside_code;
- (void)openleftside:(id)fp8;
- (void)openrightside_code;
- (void)openrightside:(id)fp8;
- (void)goback:(id)fp8;
- (void)myprogramact:(id)fp8;
- (void)makeHTTPConn;
- (void)GoToRoot;
- (void)buildHeader;
- (void)viewWillDissapear:(BOOL)fp8;
- (void)viewDidDissapear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidLoad;
- (id)initWithNibName:(id)fp8 bundle:(id)fp12;

@end

