/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ABAddressBookCopyArrayOfAllPeople.h"

@class NSString;

@interface SBJsonParser : _ABAddressBookCopyArrayOfAllPeople
{
    unsigned int maxDepth;
    NSString *error;
}

- (void)setError:(id)fp8;
- (id)error;
- (void)setMaxDepth:(unsigned int)fp8;
- (unsigned int)maxDepth;
- (void).cxx_destruct;
- (id)objectWithString:(id)fp8 error:(id *)fp12;
- (id)objectWithString:(id)fp8;
- (id)objectWithData:(id)fp8;
- (id)init;

@end

