/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "ZBarReaderView.h"

@class AVCaptureDevice, AVCaptureInput, AVCaptureSession;

@interface ZBarReaderViewImpl : ZBarReaderView
{
    AVCaptureSession *session;
    AVCaptureDevice *device;
    AVCaptureInput *input;
}

- (void)_initWithImageScanner:(id)fp8;
- (void)initSubviews;
- (void)dealloc;
- (void)updateCrop;
- (id)scanner;
- (void)setDevice:(id)fp8;
- (BOOL)enableCache;
- (void)setEnableCache:(BOOL)fp8;
- (void)setTorchMode:(int)fp8;
- (void)setShowsFPS:(BOOL)fp8;
- (void)start;
- (void)stop;
- (void)flushCache;
- (void)onVideoStart:(id)fp8;
- (void)onVideoStop:(id)fp8;
- (void)onVideoError:(id)fp8;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (void)captureReader:(id)fp8 didTrackSymbols:(id)fp12;
- (void)captureReader:(id)fp8 didReadNewSymbolsFromImage:(id)fp12;
- (id)session;
- (id)device;

@end

