/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:13:13 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <RenrenDelegate.h>

@interface SNSAuthRenren : NSObject <RenrenDelegate> {
	Renren* mRenren; 
	id loginCallback; 
	id logoutCallback; 
}
@property (nonatomic,copy) id loginCallback; 
@property (nonatomic,copy) id logoutCallback; 
-(BOOL)canHandleAuthURL:(id)arg1;
-(void)handleAuthURL:(id)arg1;
-(BOOL)isLoggedin;
-(id)getAccessToken;
-(void)authorizeWithCompletionBlock:(id)arg1;
-(void)cancelAuthorizeWithCompletionBlock:(id)arg1;
-(void)renrenDidLogout:(id)arg1;
-(void)renrenDidLogin:(id)arg1;
-(void)renrenDidloginFail:(id)arg1 withError:(id)arg2;
-(void)setLoginCallback:(id)arg1;
-(void)setLogoutCallback:(id)arg1;
-(id)init;
-(void).cxx_destruct;
-(BOOL)isExpired;
@end