/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:13:17 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UITextFieldDelegate.h>
#import <UIActionSheetDelegate.h>

@interface UpdatePhoneSMSViewController : NLViewController <UITextFieldDelegate, UIActionSheetDelegate> {
	NSString* authNumber; 
	UIButton* _confirmBtn; 
	int _resendCount; 
	id<SMSPinCodeConfirmDelegate> _delegate; 
}
@property (nonatomic,retain) UIButton* confirmBtn; 				//@synthesize confirmBtn=_confirmBtn - In the implementation block
@property (nonatomic,retain) NSString* authNumber; 
@property (assign,nonatomic) int resendCount; 				//@synthesize resendCount=_resendCount - In the implementation block
@property (assign,nonatomic,__weak) id<SMSPinCodeConfirmDelegate> delegate; 				//@synthesize delegate=_delegate - In the implementation block
-(void)popViewControllerAnimated;
-(void)textFieldDidChange:(id)arg1;
-(void)setResendCount:(int)arg1;
-(void)setAuthNumber:(id)arg1;
-(void)setConfirmBtn:(id)arg1;
-(void)help:(id)arg1;
-(void)clickConfirm:(id)arg1;
-(void)resendSMS:(id)arg1;
-(void)IVR:(id)arg1;
-(void)didConfirmSMSPinCode:(id)arg1;
-(void)setDelegate:(id)arg1;
-(id)init;
-(BOOL)canPerformAction:(SEL)arg1 withSender:(id)arg2;
-(void)didReceiveMemoryWarning;
-(void)touchesBegan:(id)arg1 withEvent:(id)arg2;
-(BOOL)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
-(void)viewWillAppear:(BOOL)arg1;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2;
-(void)viewDidLoad;
-(void)loadView;
-(void)viewDidUnload;
-(void).cxx_destruct;
@end