/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AAUIDeviceLocatorStateDidChangeNotification.h"

#import "CRCarPlayPreferencesDelegate-Protocol.h"
#import "DevicePINControllerDelegate-Protocol.h"

@class CRCarPlayPreferences, NSArray, NSDictionary, NSMutableDictionary, NSTimer, PSSpecifier, TVOutManager;

@interface GeneralController : _AAUIDeviceLocatorStateDidChangeNotification <CRCarPlayPreferencesDelegate, DevicePINControllerDelegate>
{
    NSArray *_autoLockValues;
    NSDictionary *_autoLockTitleDictionary;
    NSMutableDictionary *_localizedAutoLockTitleDictionary;
    NSTimer *_usageTimer;
    TVOutManager *_tvOutManager;
    PSSpecifier *_tvOutSpecifier;
    PSSpecifier *_siriSpecifier;
    CRCarPlayPreferences *_carPreferences;
}

- (void)setCarPreferences:(id)fp8;
- (id)carPreferences;
- (void)handleURL:(id)fp8;
- (BOOL)shouldDeferPushForSpecifierID:(id)fp8;
- (void)didCancelEnteringPIN;
- (void)didAcceptEnteredPIN:(id)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)_localizeAutoLockTitles;
- (void)enableEdge:(id)fp8;
- (id)EDGEEnabled:(id)fp8;
- (id)init;
- (void)profileNotification:(id)fp8;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (void)setLocksAndUnlocksWithCase:(id)fp8 specifier:(id)fp12;
- (id)locksAndUnlocksWithCase:(id)fp8;
- (id)parentalControlsEnabled:(id)fp8;
- (void)dealloc;
- (void)handleCarPlayAllowedDidChange;
- (void)updateAssistantSpecifiers;
- (BOOL)_hasCarPlayContent;
- (id)specifiers;
- (void)_setUseSwitchForOrientationLockWithSpecifier:(id)fp8;
- (void)setScreenLock:(id)fp8 specifier:(id)fp12;
- (id)screenLock:(id)fp8;
- (void)handleTVOutChange;
- (void)updateAutoLockSpecifier;

@end

