/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "LocationIndicatorExplanationView.h"

@class UILabel;

@interface LocationIndicatorSystemExplanationView : LocationIndicatorExplanationView
{
    UILabel *_additionalInfoLabel;
}

- (float)preferredHeightForWidth:(float)fp8 inTableView:(id)fp12;
- (void)layoutForWidth:(float)fp8 inTableView:(id)fp12;
- (void)dealloc;
- (id)initWithSpecifier:(id)fp8;

@end

