/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AAUIDeviceLocatorStateDidChangeNotification.h"

#import "PSHeaderFooterView-Protocol.h"

@class UIImageView, UILabel;

@interface LocationIndicatorExplanationView : _AAUIDeviceLocatorStateDidChangeNotification <PSHeaderFooterView>
{
    UIImageView *_activeIcon;
    UILabel *_activeLabel;
    UIImageView *_recentIcon;
    UILabel *_recentLabel;
    UIImageView *_geofenceIcon;
    UILabel *_geofenceLabel;
}

- (float)preferredHeightForWidth:(float)fp8 inTableView:(id)fp12;
- (float)preferredHeightForWidth:(float)fp8;
- (void)layoutSubviews;
- (void)layoutForWidth:(float)fp8 inTableView:(id)fp12;
- (void)dealloc;
- (id)initWithSpecifier:(id)fp8;

@end

