/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PSStateRestoration-Protocol.h"

@protocol PSController <PSStateRestoration>
- (void)statusBarWillAnimateByHeight:(float)fp8;
- (void)willBecomeActive;
- (void)willResignActive;
- (id)readPreferenceValue:(id)fp8;
- (void)setPreferenceValue:(id)fp8 specifier:(id)fp12;
- (void)handleURL:(id)fp8;
- (void)showController:(id)fp8 animate:(BOOL)fp12;
- (void)showController:(id)fp8;
- (void)didWake;
- (void)didUnlock;
- (void)willUnlock;
- (void)didLock;
- (void)suspend;
- (id)specifier;
- (void)setSpecifier:(id)fp8;
- (id)rootController;
- (void)setRootController:(id)fp8;
- (id)parentController;
- (void)setParentController:(id)fp8;
@end

