/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AAUIDeviceLocatorStateDidChangeNotification.h"

@class PSSpecifier;

@interface SettingsNetworkRoamingController : _AAUIDeviceLocatorStateDidChangeNotification
{
    PSSpecifier *_voiceRoamingSpecifier;
    PSSpecifier *_dataRoamingSpecifier;
    PSSpecifier *_cdmaRoamingSpecifier;
}

- (id)getCDMARoamingStatus:(id)fp8;
- (void)setCDMARoamingEnabled:(id)fp8 specifier:(id)fp12;
- (void)setEUInternetEnabled:(id)fp8 specifier:(id)fp12;
- (void)setDataRoamingEnabled:(id)fp8 specifier:(id)fp12;
- (id)getEUInternetStatus:(id)fp8;
- (id)getDataRoamingStatus:(id)fp8;
- (id)getVoiceRoamingStatus:(id)fp8;
- (void)setVoiceRoamingEnabled:(id)fp8 specifier:(id)fp12;
- (void)reloadRoamingStatus;
- (void)newCarrierNotification;
- (id)specifiers;
- (id)_voiceRoamingFooterTextWithVoiceRoamingOn:(BOOL)fp8;
- (id)cdmaRoamingSpecifiers;
- (id)dataRoamingSpecifiers;
- (void)dealloc;
- (id)init;

@end

