/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:08:53 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol AVAudioRecorderDelegate
@optional
-(void)audioRecorderEncodeErrorDidOccur(id):arg1 error(id):arg2 ;
-(void)audioRecorderDidFinishRecording(id):arg1 successfully(BOOL):arg2 ;
-(void)audioRecorderBeginInterruption(id):arg1 ;
-(void)audioRecorderEndInterruption(id):arg1 withOptions(unsigned):arg2 ;
-(void)audioRecorderEndInterruption(id):arg1 withFlags(unsigned):arg2 ;
-(void)audioRecorderEndInterruption(id):arg1 ;
@end
