/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:12:38 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface ChannelUtil : NSObject {
}
+(void)setCookieWithName:(id)arg1 value:(id)arg2 forDomain:(id)arg3;
+(void)verifyAndFixDatabaseLocations;
+(id)appSDKVersion;
+(void)deleteCookieUsingPredicator:(id)arg1;
+(void)printCookieStorage;
+(id)mimeTypeForExtension:(id)arg1;
@end