/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:11:46 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface FriendHitokotoAttributedStringCacheManager : NSObject {
	NSCache* mAttributedStringDictionaryForKey; 
}
+(id)allocWithZone:(NSZone*)arg1;
+(id)sharedManager;
-(id)getAttributedString:(id)arg1 width:(float)arg2 font:(id)arg3 sticonHeight:(float)arg4 color:(int)arg5 maximumLines:(int)arg6;
-(id)init;
-(id)copyWithZone:(NSZone*)arg1;
-(void).cxx_destruct;
@end