/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:13:00 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface LineTMessageBox : NSObject {
	NSString* __ID; 
	NSString* __channelId; 
	long long __lastSeq; 
	long long __unreadCount; 
	long long __lastModifiedTime; 
	int __status; 
	int __midType; 
	NSArray* __lastMessages; 
	struct {
		unsigned int lastSeq:1;
		unsigned int unreadCount:1;
		unsigned int lastModifiedTime:1;
		unsigned int status:1;
		unsigned int midType:1;
	} __isSet; 
}
@property (nonatomic,retain) NSString* ID; 				//@synthesize _ID=__ID - In the implementation block
@property (nonatomic,retain) NSString* channelId; 				//@synthesize _channelId=__channelId - In the implementation block
@property (assign,nonatomic) long long lastSeq; 				//@synthesize _lastSeq=__lastSeq - In the implementation block
@property (assign,nonatomic) long long unreadCount; 				//@synthesize _unreadCount=__unreadCount - In the implementation block
@property (assign,nonatomic) long long lastModifiedTime; 				//@synthesize _lastModifiedTime=__lastModifiedTime - In the implementation block
@property (assign,nonatomic) int status; 				//@synthesize _status=__status - In the implementation block
@property (assign,nonatomic) int midType; 				//@synthesize _midType=__midType - In the implementation block
@property (nonatomic,retain) NSArray* lastMessages; 				//@synthesize _lastMessages=__lastMessages - In the implementation block
-(void)setMidType:(int)arg1;
-(void)setChannelId:(id)arg1;
-(void)read:(id)arg1;
-(void)setLastSeq:(long long)arg1;
-(void)setLastModifiedTime:(long long)arg1;
-(void)setLastMessages:(id)arg1;
-(void)setStatus:(int)arg1;
-(void)setID:(id)arg1;
-(void)setUnreadCount:(long long)arg1;
-(void).cxx_destruct;
-(void)write:(id)arg1;
@end