/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:11:27 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface LinePaymentReservationResult : NSObject {
	NSString* __orderId; 
	NSString* __confirmUrl; 
	NSDictionary* __extras; 
	struct {
	} __isSet; 
}
@property (nonatomic,retain) NSString* orderId; 				//@synthesize _orderId=__orderId - In the implementation block
@property (nonatomic,retain) NSString* confirmUrl; 				//@synthesize _confirmUrl=__confirmUrl - In the implementation block
@property (nonatomic,retain) NSDictionary* extras; 				//@synthesize _extras=__extras - In the implementation block
-(void)read:(id)arg1;
-(void)setOrderId:(id)arg1;
-(void)setConfirmUrl:(id)arg1;
-(void)setExtras:(id)arg1;
-(void).cxx_destruct;
-(void)write:(id)arg1;
@end