/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:13:19 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface LineSNSProvider : NSObject {
	int _idType; 
	NSString* _name; 
	UIImage* _ciImage; 
	UIImage* _smallCIImage; 
}
@property (assign,nonatomic) int idType; 				//@synthesize idType=_idType - In the implementation block
@property (nonatomic,retain) NSString* name; 				//@synthesize name=_name - In the implementation block
@property (nonatomic,retain) UIImage* ciImage; 				//@synthesize ciImage=_ciImage - In the implementation block
@property (nonatomic,retain) UIImage* smallCIImage; 				//@synthesize smallCIImage=_smallCIImage - In the implementation block
+(id)providerForIDType:(int)arg1 name:(id)arg2 ciImage:(id)arg3 smallCIImnage:(id)arg4;
+(BOOL)allowsToSyncFriendsWithProvider:(id)arg1;
+(void)setAllowsToSyncFriends:(BOOL)arg1 provider:(id)arg2;
+(void)resetLastSyncTimeWithProvider:(id)arg1;
-(BOOL)isSocialGraphAvaiable;
-(BOOL)hasAccount;
-(void)syncFriendsListUsingCompletionBlock:(id)arg1;
-(void)integrateWithCompletionBlock:(id)arg1;
-(void)separateWithCompletionBlock:(id)arg1;
-(id)synchronizedTime;
-(BOOL)isLoggedIn;
-(void)setIdType:(int)arg1;
-(void)setCiImage:(id)arg1;
-(void)setSmallCIImage:(id)arg1;
-(BOOL)isLineAccount;
-(void)postInvitationMessageToSNSUser:(id)arg1;
-(id)accessToken;
-(void)setName:(id)arg1;
-(id)userID;
-(void).cxx_destruct;
@end