/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:12:42 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface LinePublicKey : NSObject {
	int __keyAlgorithm; 
	int __keySize; 
	NSData* __keyData; 
	long long __createdTime; 
	struct {
		unsigned int keyAlgorithm:1;
		unsigned int keySize:1;
		unsigned int createdTime:1;
	} __isSet; 
}
@property (assign,nonatomic) int keyAlgorithm; 				//@synthesize _keyAlgorithm=__keyAlgorithm - In the implementation block
@property (assign,nonatomic) int keySize; 				//@synthesize _keySize=__keySize - In the implementation block
@property (nonatomic,retain) NSData* keyData; 				//@synthesize _keyData=__keyData - In the implementation block
@property (assign,nonatomic) long long createdTime; 				//@synthesize _createdTime=__createdTime - In the implementation block
-(void)read:(id)arg1;
-(void)setCreatedTime:(long long)arg1;
-(void)setKeyAlgorithm:(int)arg1;
-(void)setKeySize:(int)arg1;
-(void)setKeyData:(id)arg1;
-(void).cxx_destruct;
-(void)write:(id)arg1;
@end