/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:11:51 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <NSCoding.h>

@interface LineTicket : NSObject <NSCoding> {
	NSString* __ID; 
	long long __expirationTime; 
	int __maxUseCount; 
	struct {
		unsigned int expirationTime:1;
		unsigned int maxUseCount:1;
	} __isSet; 
}
@property (nonatomic,retain) NSString* ID; 				//@synthesize _ID=__ID - In the implementation block
@property (assign,nonatomic) long long expirationTime; 				//@synthesize _expirationTime=__expirationTime - In the implementation block
@property (nonatomic,copy) BOOL expirationTimeIsSet; 
@property (assign,nonatomic) int maxUseCount; 				//@synthesize _maxUseCount=__maxUseCount - In the implementation block
@property (nonatomic,copy) BOOL maxUseCountIsSet; 
-(void)read:(id)arg1;
-(void)setMaxUseCount:(int)arg1;
-(id)initWithCoder:(id)arg1;
-(void)encodeWithCoder:(id)arg1;
-(void)setID:(id)arg1;
-(void).cxx_destruct;
-(void)write:(id)arg1;
-(void)setExpirationTime:(long long)arg1;
@end