/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:15:53 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <LEGYConnectionInfoAcquisitorExternal.h>

@interface LineConnectionInfoAcquisitorExternal : NSObject <LEGYConnectionInfoAcquisitorExternal> {
}
-(id)countryCodeFromTelSIMLocale;
-(id)applicationInfo;
-(id)talkServerHosts;
-(id)lastSuccessfulHostWithKey:(id)arg1;
-(void)setLastSuccessfulHost:(id)arg1 withKey:(id)arg2;
-(id)cachedConnectionInfoWithKey:(id)arg1;
-(id)cachedConnectionInfoDate;
-(void)setCachedConnectionInfo:(id)arg1 withKey:(id)arg2;
-(void)resetCachedConnectionInfoDate;
-(id)carrierInfoForConnectionInfo;
-(void)save;
-(id)accessToken;
-(id)userAgent;
@end