/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:14:46 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <MBActorObserving.h>

@interface MBLikeUserView : UIView <MBActorObserving> {
	MBURLImageButton* mProfileImageButton; 
	UIImageView* mStickerImageView; 
	UIButton* mNickNameButton; 
	UIView* mUpLine; 
	UIView* mDownLine; 
	MBLike* mLike; 
	id mImageCallback; 
}
+(id)likeUserView;
-(void)actorDidLoadNickname:(id)arg1;
-(void)actorDidLoadImage:(id)arg1;
-(void)setLike:(id)arg1;
-(void)setProfileImage;
-(id)like;
-(id)initWithFrame:(CGRect)arg1;
-(void)dealloc;
-(void)layoutSubviews;
-(void).cxx_destruct;
@end