/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:13:43 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol MFMessageComposeViewControllerDelegate
@required
-(void)messageComposeViewController(id):arg1 didFinishWithResult(int):arg2 ;
-(void)messageComposeViewController(id):arg1 didFinishWithResult(int):arg2 ;
@end
