/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:09:33 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface NJAnimation : NSObject {
}
+(void)fadeOut:(id)arg1 remove:(id)arg2;
+(void)addLeftTransitionAnimation:(id)arg1;
+(void)addRightTransitionAnimation:(id)arg1;
+(void)addSubviewWithCurlupAnimation:(id)arg1 nextView:(id)arg2;
+(void)removeViewWithCurlDownAnimation:(id)arg1 nextView:(id)arg2;
+(void)addUpTransitionAnimation:(id)arg1;
+(void)addDownTransitionAnimation:(id)arg1;
+(void)fadeIn:(id)arg1 add:(id)arg2;
@end