/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:10:05 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UIGestureRecognizerDelegate.h>

@interface NLBuddyVideoHeaderView : UIView <UIGestureRecognizerDelegate> {
	BOOL _isFirstPreparedToPlay; 
	unsigned _appearType; 
	NLBuddyOnAirModel* _onAirModel; 
	int _currentOrientation; 
	id<NLBuddyVideoHeaderViewDelegate> _delegate; 
	unsigned _playbackStatus; 
	UIImageView* _titleBgView; 
	UILabel* _buddyNameLabel; 
	UIImageView* _centerLiveIcon; 
	UILabel* _castInfoLabel; 
	UILabel* _attendeeCountLabel; 
	UIImageView* _divIcon; 
	NLActiveHitButton* _videoQualityButton; 
	NLActiveHitButton* _closeButton; 
	NLActiveHitButton* _rotateButton; 
	UILabel* _timeLabel; 
	UIImageView* _leftLiveIcon; 
	NLGCDTimer* _disappearTimer; 
	NLGCDTimer* _playTimer; 
}
@property (assign,nonatomic) unsigned appearType; 				//@synthesize appearType=_appearType - In the implementation block
@property (nonatomic,retain) NLBuddyOnAirModel* onAirModel; 				//@synthesize onAirModel=_onAirModel - In the implementation block
@property (assign,nonatomic) int currentOrientation; 				//@synthesize currentOrientation=_currentOrientation - In the implementation block
@property (assign,nonatomic) id<NLBuddyVideoHeaderViewDelegate> delegate; 				//@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) unsigned playbackStatus; 				//@synthesize playbackStatus=_playbackStatus - In the implementation block
@property (nonatomic,retain) UIImageView* titleBgView; 				//@synthesize titleBgView=_titleBgView - In the implementation block
@property (nonatomic,retain) UILabel* buddyNameLabel; 				//@synthesize buddyNameLabel=_buddyNameLabel - In the implementation block
@property (nonatomic,retain) UIImageView* centerLiveIcon; 				//@synthesize centerLiveIcon=_centerLiveIcon - In the implementation block
@property (nonatomic,retain) UILabel* castInfoLabel; 				//@synthesize castInfoLabel=_castInfoLabel - In the implementation block
@property (nonatomic,retain) UILabel* attendeeCountLabel; 				//@synthesize attendeeCountLabel=_attendeeCountLabel - In the implementation block
@property (nonatomic,retain) UIImageView* divIcon; 				//@synthesize divIcon=_divIcon - In the implementation block
@property (nonatomic,retain) NLActiveHitButton* videoQualityButton; 				//@synthesize videoQualityButton=_videoQualityButton - In the implementation block
@property (nonatomic,retain) NLActiveHitButton* closeButton; 				//@synthesize closeButton=_closeButton - In the implementation block
@property (nonatomic,retain) NLActiveHitButton* rotateButton; 				//@synthesize rotateButton=_rotateButton - In the implementation block
@property (nonatomic,retain) UILabel* timeLabel; 				//@synthesize timeLabel=_timeLabel - In the implementation block
@property (nonatomic,retain) UIImageView* leftLiveIcon; 				//@synthesize leftLiveIcon=_leftLiveIcon - In the implementation block
@property (assign,nonatomic) BOOL isFirstPreparedToPlay; 				//@synthesize isFirstPreparedToPlay=_isFirstPreparedToPlay - In the implementation block
@property (nonatomic,retain) NLGCDTimer* disappearTimer; 				//@synthesize disappearTimer=_disappearTimer - In the implementation block
@property (nonatomic,retain) NLGCDTimer* playTimer; 				//@synthesize playTimer=_playTimer - In the implementation block
+(id)videoHeaderView;
-(void)setOnAirModel:(id)arg1;
-(void)setTimeLabel:(id)arg1;
-(void)setCloseButton:(id)arg1;
-(void)setRotateButton:(id)arg1;
-(void)setCurrentOrientation:(int)arg1;
-(void)setPlaybackStatus:(unsigned)arg1;
-(void)setAppearType:(unsigned)arg1;
-(void)resumeOrSuspendPlayTimerWithAppearType:(unsigned)arg1;
-(void)hiddenSubviewsForCurrentAppearType;
-(void)fireTimeLabelTimer;
-(void)fireDisappearTimer;
-(void)changeMenuType;
-(void)presentCurrentTouchType;
-(void)setDisappearTimer:(id)arg1;
-(void)setPlayTimer:(id)arg1;
-(void)applyModel;
-(void)cancelDisappearTimer;
-(void)didPlay;
-(void)didStop;
-(void)didPause;
-(void)layoutTitleFirstLineAreaWithSize:(CGSize)arg1;
-(void)layoutTitleSecondLineAreaWithSize:(CGSize)arg1;
-(void)layoutBottomAreaWithSize:(CGSize)arg1;
-(void)initVariables;
-(void)tappedBuddyVideoHeaderView:(id)arg1;
-(void)actionCloseButton;
-(void)actionRotateButton;
-(void)actionVideoQualityButton;
-(void)setIsFirstPreparedToPlay:(BOOL)arg1;
-(void)setTitleBgView:(id)arg1;
-(void)setBuddyNameLabel:(id)arg1;
-(void)setCenterLiveIcon:(id)arg1;
-(void)setCastInfoLabel:(id)arg1;
-(void)setAttendeeCountLabel:(id)arg1;
-(void)setDivIcon:(id)arg1;
-(void)setVideoQualityButton:(id)arg1;
-(void)setLeftLiveIcon:(id)arg1;
-(id)initWithFrame:(CGRect)arg1;
-(void)dealloc;
-(void)setDelegate:(id)arg1;
-(void)layoutSubviews;
-(BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
-(void).cxx_destruct;
@end