/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:10:56 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PSTCollectionViewUpdateItem : NSObject {
	NSIndexPath* _initialIndexPath; 
	NSIndexPath* _finalIndexPath; 
	int _updateAction; 
	id _gap; 
}
@property (nonatomic,copy) NSIndexPath* indexPathBeforeUpdate; 				//@synthesize initialIndexPath=_initialIndexPath - In the implementation block
@property (nonatomic,copy) NSIndexPath* indexPathAfterUpdate; 				//@synthesize finalIndexPath=_finalIndexPath - In the implementation block
@property (nonatomic,copy) int updateAction; 				//@synthesize updateAction=_updateAction - In the implementation block
-(void)setNewIndexPath:(id)arg1;
-(id)description;
-(int)action;
-(int)inverseCompareIndexPaths:(id)arg1;
-(int)compareIndexPaths:(id)arg1;
-(BOOL)isSectionOperation;
-(id)newIndexPath;
-(id)initWithOldIndexPath:(id)arg1 newIndexPath:(id)arg2;
-(void)setGap:(id)arg1;
-(id)gap;
-(id)initWithAction:(int)arg1 forIndexPath:(id)arg2;
-(id)initWithInitialIndexPath:(id)arg1 finalIndexPath:(id)arg2 updateAction:(int)arg3;
-(void).cxx_destruct;
@end