/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:11:43 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface SAFmfLocation : SALocation {
}
@property (nonatomic,retain) NSNumber* distance; 
@property (nonatomic,copy) NSString* emailAddress; 
@property (nonatomic,retain) SAPersonAttribute* friend; 
@property (nonatomic,retain) NSNumber* locationDate; 
+(id)locationWithDictionary:(id)arg1 context:(id)arg2;
-(id)groupIdentifier;
-(void)setEmailAddress:(id)arg1;
-(void)setDistance:(id)arg1;
-(id)encodedClassName;
-(void)updateUsingSet:(id)arg1 add:(id)arg2 remove:(id)arg3;
-(void)setFriend:(id)arg1;
-(void)setLocationDate:(id)arg1;
@end