/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:10:24 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <SAAceSerializable.h>

@interface SAPersonAttribute : AceObject <SAAceSerializable> {
}
@property (nonatomic,copy) NSString* data; 
@property (nonatomic,copy) NSString* displayText; 
@property (nonatomic,retain) SAPerson* object; 
@property (nonatomic,retain) id<SAAceSerializable> typedData; 
+(id)personAttribute;
+(id)personAttributeWithDictionary:(id)arg1 context:(id)arg2;
-(id)groupIdentifier;
-(void)setData:(id)arg1;
-(void)setObject:(id)arg1;
-(void)setDisplayText:(id)arg1;
-(id)encodedClassName;
-(void)setTypedData:(id)arg1;
@end