//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class CLGeocoder, NSDate, NSDictionary, NSString;

@interface _MPMeCardGeocoderAddress : NSObject <NSCoding>
{
    NSDictionary *_addressDictionary;
    NSString *_entityID;
    NSString *_label;
    CLGeocoder *_geocoder;
    int _state;
    int _tries;
    NSDate *_lastGeocodeAttempt;
    NSDictionary *_locationDictionary;
    _Bool _cancelingGeocode;
    NSDate *_geocodeAfter;
}

@property(readonly) NSDate *geocodeAfter; // @synthesize geocodeAfter=_geocodeAfter;
@property(readonly) int state; // @synthesize state=_state;
@property(readonly) NSDate *lastGeocodeAttempt; // @synthesize lastGeocodeAttempt=_lastGeocodeAttempt;
@property(readonly) NSDictionary *addressDictionary; // @synthesize addressDictionary=_addressDictionary;
@property(readonly) NSDictionary *locationDictionary; // @synthesize locationDictionary=_locationDictionary;
- (id)description;
- (_Bool)expired;
- (id)nextGeocodeAttempt;
- (void)cancelGeocode;
- (void)attemptGeocodeWithCompletionBlock:(CDUnknownBlockType)arg1;
- (void)recalculateGeocodeAfterDate;
- (_Bool)checkGeocodeAfterDateForSanity;
- (id)createGeocodeAfterDate;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithAddressDictionary:(id)arg1 entityID:(id)arg2 label:(id)arg3;

@end

