//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TPPhonePad.h"

@interface PHStaticDialerPad : TPPhonePad
{
    int _dialerType;
}

@property int dialerType; // @synthesize dialerType=_dialerType;
- (struct CGSize)intrinsicContentSize;
- (float)_yFudge;
- (id)_highlightedImage;
- (id)_keypadImage;
- (id)_pressedImage;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithDialerType:(int)arg1;

@end

