/*
 * This header is generated by weak_classdump 0.2
 * on Sunday, June 22, 2014 at 3:33:23 AM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface DDLogMessage : NSObject {
	int logLevel; 
	int logFlag; 
	int logContext; 
	NSString* logMsg; 
	NSDate* timestamp; 
	r* file; 
	r* className; 
	r* function; 
	int lineNumber; 
	unsigned machThreadID; 
	BOOL[65] threadName; 
	NSString* logTag; 
	char* queueLabel; 
	NSString* threadID; 
	NSString* fileName; 
	NSString* methodName; 
	NSString* classNameNSString; 
	NSString* threadNameNSString; 
}
-(id)initWithLogMsg:(id)arg1 level:(int)arg2 flag:(int)arg3 context:(int)arg4 tag:(id)arg5 file:(r*)arg6 className:(r*)arg7 function:(r*)arg8 line:(int)arg9;
-(id)initWithLogMsg:(id)arg1 level:(int)arg2 flag:(int)arg3 context:(int)arg4 file:(r*)arg5 className:(r*)arg6 function:(r*)arg7 line:(int)arg8;
-(id)threadName;
-(id)methodName;
-(void)dealloc;
-(id)className;
-(id)fileName;
-(id)threadID;
@end