/*
 * This header is generated by weak_classdump 0.2
 * on Sunday, June 22, 2014 at 3:34:43 AM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface FBAnnouncerBaseImplementation : NSObject {
	NSMutableArray* _subscriptions; 
	BOOL _isAtomic; 
	?* _executeWork; 
	id _onFirstSubscriptionAdded; 
	id _onLastSubscriptionRemoved; 
}
-(id)initAtomic:(BOOL)arg1 firstSubscriptionBlock:(id)arg2 lastSubscriptionBlock:(id)arg3;
-(void)removeSubscription:(id)arg1;
-(void)addSubscription:(id)arg1;
-(void)enumerateSubscriptionsUsingBlock:(id)arg1;
-(id)init;
-(void).cxx_destruct;
@end