/*
 * This header is generated by weak_classdump 0.2
 * on Sunday, June 22, 2014 at 3:33:48 AM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface FBRecentActivitySentinelManager : NSObject {
}
+(id)recentActivities:(int)arg1;
+(void)significantEventDidOccur:(id)arg1 module:(id)arg2 extra:(id)arg3;
+(void)setupSentinelsIfNeeded;
+(void)addBugReportingSentinel;
@end