/*
 * This header is generated by weak_classdump 0.2
 * on Sunday, June 22, 2014 at 3:33:45 AM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface FBSwizzle : NSObject {
	Class cls; 
	SEL selector; 
	SEL mangledSelector; 
	struct objc_method* method; 
	struct objc_method* mangledMethod; 
	unsigned ID; 
	BOOL instance; 
}
-(id)initWithClass:(Class)arg1 selector:(SEL)arg2;
-(BOOL)isEqual:(id)arg1;
-(unsigned)hash;
-(id)description;
@end