/*
 * This header is generated by weak_classdump 0.2
 * on Sunday, June 22, 2014 at 3:34:48 AM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <GTMLogWriter.h>

@interface GTMLogger : NSObject <GTMLogWriter> {
	id<GTMLogWriter> writer_; 
	id<GTMLogFormatter> formatter_; 
	id<GTMLogFilter> filter_; 
}
+(id)standardLogger;
+(id)loggerWithWriter:(id)arg1 formatter:(id)arg2 filter:(id)arg3;
+(void)setSharedLogger:(id)arg1;
+(id)standardLoggerWithStderr;
+(id)standardLoggerWithStdoutAndStderr;
+(id)standardLoggerWithPath:(id)arg1;
+(id)sharedLogger;
+(id)logger;
-(void)logFuncInfo:(r*)arg1 msg:(id)arg2;
-(id)initWithWriter:(id)arg1 formatter:(id)arg2 filter:(id)arg3;
-(void)logInternalFunc:(r*)arg1 format:(id)arg2 valist:(void*)arg3 level:(int)arg4;
-(void)logAssert:(id)arg1;
-(void)logFuncDebug:(r*)arg1 msg:(id)arg2;
-(void)logFuncError:(r*)arg1 msg:(id)arg2;
-(void)logFuncAssert:(r*)arg1 msg:(id)arg2;
-(void)logMessage:(id)arg1 level:(int)arg2;
-(void)dealloc;
-(id)init;
-(void)setFilter:(id)arg1;
-(void)logInfo:(id)arg1;
-(id)writer;
-(void)setWriter:(id)arg1;
-(void)logError:(id)arg1;
-(void)logDebug:(id)arg1;
-(void)setFormatter:(id)arg1;
-(id)formatter;
-(id)filter;
@end