/*
 * This header is generated by weak_classdump 0.2
 * on Sunday, June 22, 2014 at 3:34:47 AM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol GTMLogFormatter
@required
-(id)stringForFunc(id):arg1 withFormat(id):arg2 valist(*):arg3 level(void):arg4 ;
-(id)stringForFunc(id):arg1 withFormat(id):arg2 valist(*):arg3 level(void):arg4 ;
@end
