/*
 * This header is generated by weak_classdump 0.2
 * on Sunday, June 22, 2014 at 3:35:12 AM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface IGArcLayer : CALayer {
}
@property (assign,nonatomic,@dynamic) float progress; 
+(BOOL)needsDisplayForKey:(id)arg1;
-(void)setProgress:(double)arg1;
-(id)actionForKey:(id)arg1;
-(void)drawInContext:(struct CGContext*)arg1;
@end