/*
 * This header is generated by weak_classdump 0.2
 * on Sunday, June 22, 2014 at 3:34:46 AM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface IGDirectedShareUserView : UIView {
	IGProfilePictureImageView* _imageView; 
	UIImageView* _seenStateImageView; 
	IGDynamics1D* _transformAnimator; 
}
@property (nonatomic,retain) IGProfilePictureImageView* imageView; 				//@synthesize imageView=_imageView - In the implementation block
@property (nonatomic,retain) UIImageView* seenStateImageView; 				//@synthesize seenStateImageView=_seenStateImageView - In the implementation block
@property (assign,nonatomic,__weak) IGDynamics1D* transformAnimator; 				//@synthesize transformAnimator=_transformAnimator - In the implementation block
-(void)setSeenStateImageViewVisible:(BOOL)arg1 animated:(BOOL)arg2;
-(void)setTransformAnimator:(id)arg1;
-(void)setSeenState:(int)arg1 animated:(BOOL)arg2;
-(void)setSeenStateImageView:(id)arg1;
-(id)initWithFrame:(CGRect)arg1;
-(void)dealloc;
-(void)layoutSubviews;
-(void)setImageView:(id)arg1;
-(void)setDimmed:(BOOL)arg1 animated:(BOOL)arg2;
-(void).cxx_destruct;
@end