/*
 * This header is generated by weak_classdump 0.2
 * on Sunday, June 22, 2014 at 3:35:41 AM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <IGCoreTextLinkHandler.h>

@interface IGFeedItemTextCell : IGSimpleTableViewCell <IGCoreTextLinkHandler> {
	UIImageView* _iconView; 
	IGCoreTextView* _coreTextView; 
	IGFeedItem* _feedItem; 
	IGCommentModel* _comment; 
	int _cellType; 
	IGTimelineViewManager* _dataSource; 
	UINavigationController* _navigationController; 
}
@property (nonatomic,retain) IGFeedItem* feedItem; 				//@synthesize feedItem=_feedItem - In the implementation block
@property (nonatomic,retain) IGCommentModel* comment; 				//@synthesize comment=_comment - In the implementation block
@property (assign,nonatomic) int cellType; 				//@synthesize cellType=_cellType - In the implementation block
@property (assign,nonatomic,__weak) IGTimelineViewManager* dataSource; 				//@synthesize dataSource=_dataSource - In the implementation block
@property (assign,nonatomic,__weak) UINavigationController* navigationController; 				//@synthesize navigationController=_navigationController - In the implementation block
+(float)heightWithStyledString:(id)arg1;
-(void)setFeedItem:(id)arg1;
-(void)coreTextView:(id)arg1 didTapOnString:(id)arg2 URL:(id)arg3;
-(void)coreTextView:(id)arg1 didLongTapOnString:(id)arg2 URL:(id)arg3;
-(void)buildCommentReplyWithUser:(id)arg1;
-(void)updateIconWithType:(int)arg1;
-(void)pushCommentsPrefilledWithText:(id)arg1;
-(void)setComment:(id)arg1;
-(void)dealloc;
-(void)setBackgroundColor:(id)arg1;
-(void)setDataSource:(id)arg1;
-(id)initWithReuseIdentifier:(id)arg1;
-(void)setNavigationController:(id)arg1;
-(void)setCellType:(int)arg1;
-(void).cxx_destruct;
@end