/*
 * This header is generated by weak_classdump 0.2
 * on Sunday, June 22, 2014 at 3:35:40 AM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol IGFindFriendsHelperDelegate
@required
-(void)findFriendsHelper(id):arg1 didFailToAuthorizeWithMessage(id):arg2 ;
-(void)findFriendsHelper(id):arg1 didAuthorizeWithDataRequest(id):arg2 ;
-(void)findFriendsHelper(id):arg1 didFailToAuthorizeWithMessage(id):arg2 ;
-(void)findFriendsHelper(id):arg1 didAuthorizeWithDataRequest(id):arg2 ;
@end
