/*
 * This header is generated by weak_classdump 0.2
 * on Sunday, June 22, 2014 at 3:34:47 AM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface IGGroupedTableViewHeaderView : UIView {
	UIView* _accessoryView; 
	UILabel* _titleLabel; 
	UILabel* _textLabel; 
}
+(float)heightWithTitle:(id)arg1 text:(id)arg2;
+(float)textLabelXWithAccessoryViewWidth:(float)arg1;
+(float)textWidthWithAccessoryViewWidth:(float)arg1;
+(CGSize)titleLabelSizeWithTitle:(id)arg1 width:(float)arg2;
+(CGSize)textLabelSizeWithText:(id)arg1 width:(float)arg2;
+(float)minHeightForAccessoryViewHeight:(float)arg1;
+(float)heightWithTitle:(id)arg1 text:(id)arg2 accessoryViewOfSize:(CGSize)arg3;
-(id)initWithTitle:(id)arg1 text:(id)arg2;
-(id)initWithTitle:(id)arg1 text:(id)arg2 accessoryView:(id)arg3;
-(void)configureTitleLabelWithTitle:(id)arg1;
-(void)configureTextLabelWithText:(id)arg1;
-(void)doLayout;
-(void).cxx_destruct;
@end