/*
 * This header is generated by weak_classdump 0.2
 * on Sunday, June 22, 2014 at 3:33:10 AM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface IGSegmentedControl : UIView {
	NSArray* _buttons; 
	int _selectedIndex; 
	id<IGSegmentedControlDelegate> _delegate; 
	UIImageView* _bgView; 
	UIImageView* _selectionView; 
	UIPanGestureRecognizer* _panRecognizer; 
	struct UIEdgeInsets _insets; 
}
@property (nonatomic,retain) NSArray* buttons; 				//@synthesize buttons=_buttons - In the implementation block
@property (assign,nonatomic) struct UIEdgeInsets insets; 				//@synthesize insets=_insets - In the implementation block
@property (assign,nonatomic) int selectedIndex; 				//@synthesize selectedIndex=_selectedIndex - In the implementation block
@property (assign,nonatomic,__weak) id<IGSegmentedControlDelegate> delegate; 				//@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) UIImageView* bgView; 				//@synthesize bgView=_bgView - In the implementation block
@property (nonatomic,retain) UIImageView* selectionView; 				//@synthesize selectionView=_selectionView - In the implementation block
@property (nonatomic,retain) UIPanGestureRecognizer* panRecognizer; 				//@synthesize panRecognizer=_panRecognizer - In the implementation block
-(void)panGesture:(id)arg1;
-(void)setPanRecognizer:(id)arg1;
-(void)onSegmentTapped:(id)arg1;
-(void)moveSelectionViewAnimated:(BOOL)arg1;
-(void)setBgView:(id)arg1;
-(void)setSelectionView:(id)arg1;
-(id)initWithFrame:(CGRect)arg1;
-(void)setDelegate:(id)arg1;
-(id)hitTest:(CGPoint)arg1 withEvent:(id)arg2;
-(void)layoutSubviews;
-(void)setTitles:(id)arg1;
-(void)setSelectedIndex:(int)arg1;
-(void)setImages:(id)arg1;
-(void)setInsets:(struct UIEdgeInsets)arg1;
-(void)setSelectedIndex:(int)arg1 animated:(BOOL)arg2;
-(void).cxx_destruct;
-(void)setButtons:(id)arg1;
@end