/*
 * This header is generated by weak_classdump 0.2
 * on Sunday, June 22, 2014 at 3:35:04 AM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface IGSurveyQuestion : NSObject {
	BOOL _showPrimerView; 
	int _answerStyle; 
	NSString* _title; 
	NSString* _subtitle; 
	NSArray* _possibleAnswers; 
	NSString* _surveyID; 
	NSString* _trackingToken; 
	NSString* _headerText; 
}
@property (assign,nonatomic) int answerStyle; 				//@synthesize answerStyle=_answerStyle - In the implementation block
@property (nonatomic,retain) NSString* title; 				//@synthesize title=_title - In the implementation block
@property (nonatomic,retain) NSString* subtitle; 				//@synthesize subtitle=_subtitle - In the implementation block
@property (nonatomic,retain) NSArray* possibleAnswers; 				//@synthesize possibleAnswers=_possibleAnswers - In the implementation block
@property (nonatomic,retain) NSString* surveyID; 				//@synthesize surveyID=_surveyID - In the implementation block
@property (nonatomic,retain) NSString* trackingToken; 				//@synthesize trackingToken=_trackingToken - In the implementation block
@property (nonatomic,retain) NSString* headerText; 				//@synthesize headerText=_headerText - In the implementation block
@property (assign,nonatomic) BOOL showPrimerView; 				//@synthesize showPrimerView=_showPrimerView - In the implementation block
+(id)questionForServerMessage:(id)arg1;
+(id)mockSurveyJSON;
-(void)setTrackingToken:(id)arg1;
-(void)setAnswerStyle:(int)arg1;
-(void)setPossibleAnswers:(id)arg1;
-(void)setSurveyID:(id)arg1;
-(void)setHeaderText:(id)arg1;
-(void)setShowPrimerView:(BOOL)arg1;
-(void)setTitle:(id)arg1;
-(void)setSubtitle:(id)arg1;
-(void).cxx_destruct;
@end