/*
 * This header is generated by weak_classdump 0.2
 * on Sunday, June 22, 2014 at 3:35:46 AM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface IGUserFeedNetworkSource : IGFeedNetworkSource {
	IGUser* _user; 
}
@property (nonatomic,retain) IGUser* user; 				//@synthesize user=_user - In the implementation block
-(void)onNewItemAvailable:(id)arg1;
-(id)initWithUser:(id)arg1;
-(void)setUser:(id)arg1;
-(void)dealloc;
-(void).cxx_destruct;
@end