/*
 * This header is generated by weak_classdump 0.2
 * on Sunday, June 22, 2014 at 3:34:25 AM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface SAEncyclopediaEntitySnippet : SAUISnippet {
}
@property (nonatomic,copy) NSArray* encyclopediaEntities; 
@property (nonatomic,copy) NSArray* suggestedEntities; 
+(id)snippet;
+(id)snippetWithDictionary:(id)arg1 context:(id)arg2;
-(id)groupIdentifier;
-(id)encodedClassName;
-(void)setEncyclopediaEntities:(id)arg1;
-(void)setSuggestedEntities:(id)arg1;
@end