/*
 * This header is generated by weak_classdump 0.2
 * on Sunday, June 22, 2014 at 3:36:04 AM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <SAServerBoundCommand.h>

@interface SAMicroblogSocialCredentialResult : SABaseCommand <SAServerBoundCommand> {
}
@property (nonatomic,retain) SAMicroblogSocialCredential* socialCredential; 
@property (nonatomic,@dynamic,copy) NSString* aceId; 
@property (nonatomic,@dynamic,copy) NSString* refId; 
+(id)socialCredentialResult;
+(id)socialCredentialResultWithDictionary:(id)arg1 context:(id)arg2;
-(id)groupIdentifier;
-(id)encodedClassName;
-(void)setSocialCredential:(id)arg1;
@end