/*
 * This header is generated by weak_classdump 0.2
 * on Sunday, June 22, 2014 at 3:35:05 AM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol SASettingAppSettingCommand
@property (nonatomic,copy) NSString* appWithSettingsId; 
@property (nonatomic,copy) NSString* location; 
@required
-(id)location;
-(id)appWithSettingsId;
-(void)setAppWithSettingsId(id):arg1 ;
-(void)setLocation(id):arg1 ;
-(id)location;
-(id)appWithSettingsId;
-(void)setAppWithSettingsId(id):arg1 ;
-(void)setLocation(id):arg1 ;
@end
