/*
 * This header is generated by weak_classdump 0.2
 * on Sunday, June 22, 2014 at 3:36:13 AM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol IGCommentCellDelegate
@optional
-(void)commentCell(id):arg1 locationTapped(id):arg2 ;
@required
-(void)commentCellDidShowActions(id):arg1 ;
-(void)commentCellUserTapped(id):arg1 ;
-(void)commentCellReplyButtonTapped(id):arg1 ;
-(void)commentCell(id):arg1 didLongTapOnUser(id):arg2 ;
-(void)commentCellDeleteButtonTapped(id):arg1 ;
-(void)commentCellDidShowActions(id):arg1 ;
-(void)commentCellUserTapped(id):arg1 ;
-(void)commentCellReplyButtonTapped(id):arg1 ;
-(void)commentCell(id):arg1 didLongTapOnUser(id):arg2 ;
-(void)commentCellDeleteButtonTapped(id):arg1 ;
@end
