/*
 * This header is generated by weak_classdump 0.2
 * on Sunday, June 22, 2014 at 3:33:26 AM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <NSCoding.h>

@interface IGDirectShareRecentRecipientSet : NSObject <NSCoding> {
	float _frequency; 
	NSSet* _users; 
}
@property (assign,nonatomic) float frequency; 				//@synthesize frequency=_frequency - In the implementation block
@property (nonatomic,retain) NSSet* users; 				//@synthesize users=_users - In the implementation block
-(id)initWithCoder:(id)arg1;
-(void)encodeWithCoder:(id)arg1;
-(id)initWithDictionary:(id)arg1;
-(void)setFrequency:(float)arg1;
-(void)setUsers:(id)arg1;
-(void).cxx_destruct;
@end