/*
 * This header is generated by weak_classdump 0.2
 * on Sunday, June 22, 2014 at 3:35:43 AM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface IGLoggedOutSessionManager : NSObject {
}
+(id)loggedOutSessionData;
+(void)removeLoggedOutSessionData;
+(id)generateAndSaveLoggedOutSessionData;
-(void)onAppBecomeActive:(id)arg1;
-(void)onEndLoggedOutSession:(id)arg1;
-(void)onLogout:(id)arg1;
-(void)dealloc;
-(id)init;
@end