/*
 * This header is generated by weak_classdump 0.2
 * on Sunday, June 22, 2014 at 3:36:03 AM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface IGRangedDataListener : NSObject {
	BOOL _headerSent; 
	BOOL _done; 
	id _dataReceived; 
	id _completion; 
	struct _NSRange _range; 
	long long _readOffset; 
}
@property (assign,nonatomic) struct _NSRange range; 				//@synthesize range=_range - In the implementation block
@property (assign,nonatomic) long long readOffset; 				//@synthesize readOffset=_readOffset - In the implementation block
@property (nonatomic,copy) id dataReceived; 				//@synthesize dataReceived=_dataReceived - In the implementation block
@property (nonatomic,copy) id completion; 				//@synthesize completion=_completion - In the implementation block
@property (nonatomic,copy) BOOL headerSent; 				//@synthesize headerSent=_headerSent - In the implementation block
@property (assign,nonatomic) BOOL done; 				//@synthesize done=_done - In the implementation block
-(id)initWithDataRange:(struct _NSRange)arg1 dataReceived:(id)arg2 completion:(id)arg3;
-(void)sendHeader:(id)arg1;
-(void)setReadOffset:(long long)arg1;
-(void)setDataReceived:(id)arg1;
-(id)description;
-(void)setCompletion:(id)arg1;
-(void)setRange:(struct _NSRange)arg1;
-(void)setDone:(BOOL)arg1;
-(void).cxx_destruct;
@end