/*
 * This header is generated by weak_classdump 0.2
 * on Sunday, June 22, 2014 at 3:34:48 AM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface IGTapButton : UIButton {
	struct UIOffset _tapPadding; 
}
@property (assign,nonatomic) struct UIOffset tapPadding; 				//@synthesize tapPadding=_tapPadding - In the implementation block
-(void)setTapPadding:(struct UIOffset)arg1;
-(id)initWithFrame:(CGRect)arg1;
-(BOOL)pointInside:(CGPoint)arg1 withEvent:(id)arg2;
@end