/*
 * This header is generated by weak_classdump 0.2
 * on Sunday, June 22, 2014 at 3:36:43 AM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol IGVideoPlayerViewProtocol
@property (nonatomic,copy) NSURL* URL; 
@property (nonatomic,copy) int state; 
@property (nonatomic,copy) UIView* playerView; 
@property (assign,nonatomic,__weak) id<IGFeedVideoPlayerDelegate> delegate; 
@required
-(void)loadVideoForURL(id):arg1 ;
-(void)resetPlayer;
-(void)playImmediately;
-(void)playWhenReady;
-(float)currentTime;
-(id)playerView;
-(void)setDelegate(id):arg1 ;
-(id)delegate;
-(int)state;
-(float)duration;
-(id)URL;
-(void)reset;
-(void)stop;
-(void)pause;
-(void)loadVideoForURL(id):arg1 ;
-(void)resetPlayer;
-(void)playImmediately;
-(void)playWhenReady;
-(float)currentTime;
-(id)playerView;
-(void)setDelegate(id):arg1 ;
-(id)delegate;
-(int)state;
-(float)duration;
-(id)URL;
-(void)reset;
-(void)stop;
-(void)pause;
@end
