/*
 * This header is generated by weak_classdump 0.2
 * on Sunday, June 22, 2014 at 3:33:57 AM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <MKAnnotation.h>

@interface MapPin : NSObject <MKAnnotation> {
	NSString* _title; 
	NSString* _subtitle; 
	struct {
		double latitude;
		double longitude;
	} _coordinate; 
}
@property (assign,nonatomic) struct coordinate; 				//@synthesize coordinate=_coordinate - In the implementation block
@property (nonatomic,copy) NSString* title; 				//@synthesize title=_title - In the implementation block
@property (nonatomic,copy) NSString* subtitle; 				//@synthesize subtitle=_subtitle - In the implementation block
-(id)initWithCoordinates:(struct )arg1 placeName:(id)arg2 description:(id)arg3;
-(void)setTitle:(id)arg1;
-(void)setSubtitle:(id)arg1;
-(void)setCoordinate:(struct )arg1;
-(void).cxx_destruct;
@end