/*
 * This header is generated by weak_classdump 0.2
 * on Sunday, June 22, 2014 at 3:35:40 AM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface SAUIDomainObjectPickerSelection : SAStartRequest {
}
@property (nonatomic,retain) SAUIDomainObjectPicker* domainObjectPicker; 
@property (nonatomic,retain) SADomainObject* selectedItem; 
+(id)domainObjectPickerSelection;
+(id)domainObjectPickerSelectionWithDictionary:(id)arg1 context:(id)arg2;
-(id)groupIdentifier;
-(void)setSelectedItem:(id)arg1;
-(id)encodedClassName;
-(void)setDomainObjectPicker:(id)arg1;
@end