/*
 * This header is generated by weak_classdump 0.2
 * on Sunday, June 22, 2014 at 3:35:10 AM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol UIImagePickerControllerDelegate
@optional
-(void)imagePickerControllerDidCancel(id):arg1 ;
-(void)imagePickerController(id):arg1 didFinishPickingMediaWithInfo(id):arg2 ;
-(void)imagePickerController(id):arg1 didFinishPickingImage(id):arg2 editingInfo(id):arg3 ;
@end
