/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:12:14 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface _LLDeallocHandle : NSObject {
	id _block; 
}
-(id)initWithBlock:(id)arg1;
-(void)dealloc;
-(void).cxx_destruct;
@end