/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:12:58 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface LCNoticeErrorView : UIView {
	UIImageView* mAttentionImageView; 
	UILabel* mTitleLabel; 
	UILabel* mMessageLabel; 
	UIButton* mReloadButton; 
}
-(id)initWithDelegate:(id)arg1 isPortrate:(BOOL)arg2;
-(void)setFrameToLandscape;
-(void)setFrameToPortrait;
-(void)layoutPortraitSubviews;
-(void)layoutLandscapeSubviews;
-(id)initWithFrame:(CGRect)arg1;
-(void)dealloc;
-(void)layoutSubviews;
@end