/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:14:29 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol UIActionSheetDelegate
@optional
-(void)actionSheet(id):arg1 clickedButtonAtIndex(int):arg2 ;
-(void)actionSheetCancel(id):arg1 ;
-(void)willPresentActionSheet(id):arg1 ;
-(void)didPresentActionSheet(id):arg1 ;
-(void)actionSheet(id):arg1 willDismissWithButtonIndex(int):arg2 ;
-(void)actionSheet(id):arg1 didDismissWithButtonIndex(int):arg2 ;
@end

@protocol UINavigationControllerDelegate
@optional
-(void)navigationController(id):arg1 willShowViewController(id):arg2 animated(BOOL):arg3 ;
-(void)navigationController(id):arg1 didShowViewController(id):arg2 animated(BOOL):arg3 ;
-(id)navigationController(id):arg1 animationControllerForOperation(int):arg2 fromViewController(id):arg3 toViewController(id):arg4 ;
-(id)navigationController(id):arg1 interactionControllerForAnimationController(id):arg2 ;
-(unsigned)navigationControllerSupportedInterfaceOrientations(id):arg1 ;
-(int)navigationControllerPreferredInterfaceOrientationForPresentation(id):arg1 ;
@end

@protocol UIImagePickerControllerDelegate
@optional
-(void)imagePickerControllerDidCancel(id):arg1 ;
-(void)imagePickerController(id):arg1 didFinishPickingMediaWithInfo(id):arg2 ;
-(void)imagePickerController(id):arg1 didFinishPickingImage(id):arg2 editingInfo(id):arg3 ;
@end

@protocol FriendsPickerViewControllerDelegate
@optional
-(void)friendsPickerViewControllerDidCancel(id):arg1 ;
@required
-(void)friendsPickerViewController(id):arg1 didFinishPickingItems(id):arg2 ;
-(void)friendsPickerViewController(id):arg1 didFinishPickingItems(id):arg2 ;
@end

@protocol LGImagePickerDelegate
@optional
-(void)lgImagePickerController(id):arg1 didSavedAlbumAssetsRefreshedWithLastAssets(id):arg2 ;
-(void)lgImagePickerController(id):arg1 didSavedAlbumAssetsRefreshedAfterDate(id):arg2 ;
-(void)lgImagePickerControllerDidSelectOverPlayTimeVideo(id):arg1 ;
-(void)lgImagePickerControllerDidReachMaxLimit(id):arg1 ;
-(void)lgImagePickerController(id):arg1 didClickWithAreaId(id):arg2 action(id):arg3 ;
-(void)lgImagePickerController(id):arg1 didMoveOnGalleryEnd(int):arg2 assetsCount(int):arg3 ;
-(BOOL)lgImagePickerController(id):arg1 shouldSelectAssetForRatio(float):arg2 ;
@required
-(void)lgImagePickerController(id):arg1 didFinishPickingMediaWithInfos(id):arg2 ;
-(void)lgImagePickerControllerDidCancel(id):arg1 ;
-(void)lgImagePickerController(id):arg1 didFinishPickingMediaWithInfos(id):arg2 ;
-(void)lgImagePickerControllerDidCancel(id):arg1 ;
@end
