/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:16:06 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface LineHomeScheme : NSObject {
}
+(BOOL)canBeHandledWithURLString:(id)arg1;
+(void)executeSchemeFromURL:(id)arg1 fromSourceApplication:(id)arg2 withOptions:(unsigned)arg3;
+(void)beforeExecuteSchemeWithOptions:(unsigned)arg1;
+(id)extractParametersFromSchemeUrl:(id)arg1;
+(void)routeMsgWithParameters:(id)arg1 type:(id)arg2 inViewController:(id)arg3;
+(void)routeMainWithParameters:(id)arg1 type:(id)arg2 inViewController:(id)arg3;
+(void)routeProfileWithParameters:(id)arg1 type:(id)arg2 inViewController:(id)arg3;
+(void)routePostWithParameters:(id)arg1 type:(id)arg2 inViewController:(id)arg3;
+(id)convertUserID:(id)arg1 byType:(id)arg2;
+(void)searchMIDWithUserID:(id)arg1 completionBlock:(id)arg2 inViewController:(id)arg3;
+(id)lineHomeScheme;
+(void)routeWithAction:(id)arg1 type:(id)arg2 parameters:(id)arg3;
+(int)scheme;
@end