/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:16:18 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface MBAPIRequest : NSObject {
	NSURL* mBaseURL; 
	NSString* mPath; 
	NSMutableDictionary* mQuery; 
	int mRequestContentType; 
	int mServerType; 
	unsigned mOption; 
}
@property (nonatomic,copy) NSString* path; 
@property (nonatomic,copy) int serverType; 
@property (assign,nonatomic) int requestContentType; 
@property (assign,nonatomic) unsigned option; 
+(id)timelineListAPIPath:(id)arg1;
+(id)timelineAPIPath:(id)arg1;
+(id)timelineSAPIPath:(id)arg1;
+(id)homeAPIPath:(id)arg1;
+(id)homeUserPopupAPIPath:(id)arg1;
+(id)homeTalkRoomAPIPath:(id)arg1;
+(id)deviceOperatingSystem;
+(id)activityGetRequest;
+(id)activityListRequest;
+(id)likeCreateRequest;
+(id)likeDeleteRequest;
+(id)likeListRequest;
+(id)likeUserListRequest;
+(id)commentCreateRequest;
+(id)commentDeleteRequest;
+(id)commentListRequest;
+(id)blockAddRequest;
+(id)blockRemoveRequest;
+(id)blockListRequest;
+(id)autoOpenInitRequest;
+(id)autoOpenRequest;
+(id)udpateAutoOpenRequest;
+(id)addHideRequest;
+(id)delHideRequest;
+(id)hideRequest;
+(id)statusNewPostRequest;
+(id)statusInfoRequest;
+(id)mergeActivityListRequest;
+(id)createMyhomeGroupRequest;
+(id)deleteMyhomeGroupRequest;
+(id)updateMyhomeGroupRequest;
+(id)membersMyhomeGroupRequest;
+(id)memberUpdateMyhomeGroupRequest;
+(id)syncMyhomeGroupRequest;
+(id)syncMemberMyhomeGroupRequest;
+(id)myhomeInfoGetRequest;
+(id)myhomeUpdateCoverImageRequest;
+(id)postCreateRequest;
+(id)postUpdateRequest;
+(id)postShareToTalkRoomRequest;
+(id)postDeleteRequest;
+(id)postGetRequest;
+(id)postPhotoGetRequest;
+(id)postListRequest;
+(id)postStatusRequestWithPostID:(id)arg1 userMID:(id)arg2;
+(id)userPopupRequest;
+(id)userPopupDetailRequest;
+(id)hasNewPostWithMID:(id)arg1;
+(void)initialize;
-(id)initWithBaseURL:(id)arg1 serverType:(int)arg2 path:(id)arg3;
-(void)setRequestContentType:(int)arg1;
-(void)setValue:(id)arg1 forQueryKey:(id)arg2;
-(id)valueForQueryKey:(id)arg1;
-(id)description;
-(void)setOption:(unsigned)arg1;
-(void).cxx_destruct;
@end