/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:11:01 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface NLActiveHitButton : UIButton {
	float extraHitMarginValue; 
}
@property (assign,nonatomic) float extraHitMarginValue; 
-(void)setExtraHitMarginValue:(float)arg1;
-(id)initWithCoder:(id)arg1;
-(BOOL)pointInside:(CGPoint)arg1 withEvent:(id)arg2;
-(id)init;
@end