/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:15:43 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface NotificationSoundSelectionViewController : ItemSelectionViewController {
	NSMutableDictionary* _cachedSounds; 
}
@property (nonatomic,retain) NSMutableDictionary* cachedSounds; 				//@synthesize cachedSounds=_cachedSounds - In the implementation block
-(void)selectItem:(id)arg1;
-(id)titleForRowAtIndexPath:(id)arg1;
-(void)setCachedSounds:(id)arg1;
-(void)dealloc;
-(void)viewDidLoad;
-(void).cxx_destruct;
@end