/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:14:42 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface NotificationBarView : UIView {
	NMAttributedLabel* msgLabel; 
	UIImageView* lineIcon_; 
	UIImageView* bgView_; 
	NotificationItem* currentItem_; 
}
+(void)onTimer:(id)arg1;
+(id)getBaseView;
+(void)baseViewFrameForCurrentOrientation:(id)arg1;
+(id)notificationBarView;
+(CGRect)screenBoundsForCurrentOrientation;
+(void)addContentQueue:(id)arg1;
+(id)nextItem;
+(void)hideWindow;
+(void)onRemainTimer:(id)arg1;
+(void)removeItemsForMid:(id)arg1;
+(id)showNotificationBarForUserMID:(id)arg1 chatMID:(id)arg2 message:(id)arg3 name:(id)arg4 opType:(int)arg5;
+(void)setShowInterval:(double)arg1;
+(void)initialize;
+(void)setShowDuration:(double)arg1;
+(id)queue;
+(void)showWindow;
-(void)tappedNotificationBarView:(id)arg1;
-(void)didChangeStatusBarOrientation;
-(void)drawCurrentItem;
-(void)setInitialStatus;
-(void)startAnimationIfNeed;
-(id)getAttributedString:(id)arg1 width:(float)arg2;
-(void)boundRectAttributedString:(id)arg1 width:(float)arg2 result:(CGRect*)arg3;
-(void)setDisplayStatus;
-(void)setLastStatus;
-(id)getMessageAttrs;
-(id)initWithFrame:(CGRect)arg1;
-(void)dealloc;
-(BOOL)pointInside:(CGPoint)arg1 withEvent:(id)arg2;
-(void)setFrame:(CGRect)arg1;
-(void)showStatusBar;
-(void).cxx_destruct;
-(void)setContent:(id)arg1;
@end