/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:15:39 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface SAMicroblogSnippet : SAUISnippet {
}
@property (nonatomic,copy) NSArray* microblogs; 
+(id)snippet;
+(id)snippetWithDictionary:(id)arg1 context:(id)arg2;
-(id)groupIdentifier;
-(id)encodedClassName;
-(void)setMicroblogs:(id)arg1;
@end