/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:08:42 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface SANoteObject : SADomainObject {
}
@property (nonatomic,copy) NSString* contents; 
@property (nonatomic,copy) NSDate* createdDate; 
@property (nonatomic,copy) NSDate* lastModifiedDate; 
@property (nonatomic,copy) NSString* title; 
+(id)object;
+(id)objectWithDictionary:(id)arg1 context:(id)arg2;
-(void)setLastModifiedDate:(id)arg1;
-(id)groupIdentifier;
-(void)setTitle:(id)arg1;
-(void)setContents:(id)arg1;
-(void)setCreatedDate:(id)arg1;
-(id)encodedClassName;
-(void)updateUsingSet:(id)arg1 add:(id)arg2 remove:(id)arg3;
@end