/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:16:05 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface SAUIButton : SAAceView {
}
@property (nonatomic,copy) NSArray* commands; 
@property (nonatomic,copy) NSString* text; 
+(id)buttonWithDictionary:(id)arg1 context:(id)arg2;
+(id)button;
-(id)groupIdentifier;
-(void)setText:(id)arg1;
-(void)setCommands:(id)arg1;
-(id)encodedClassName;
@end