/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:11:10 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <SAAceSerializable.h>

@interface SAUIConfirmationOption : AceObject <SAAceSerializable> {
}
@property (assign,nonatomic) BOOL active; 
@property (nonatomic,copy) NSArray* commands; 
@property (nonatomic,copy) NSString* label; 
@property (nonatomic,copy) NSString* type; 
+(id)confirmationOption;
+(id)confirmationOptionWithDictionary:(id)arg1 context:(id)arg2;
-(id)groupIdentifier;
-(void)setType:(id)arg1;
-(void)setLabel:(id)arg1;
-(void)setActive:(BOOL)arg1;
-(void)setCommands:(id)arg1;
-(id)encodedClassName;
@end