/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:11:26 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol StickerShopSegmentControllerDelegate
@optional
-(void)tappedRightButton(id):arg1 ;
@required
-(void)changeSegment(id):arg1 ;
-(void)changeSegment(id):arg1 ;
@end
