/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:22:10 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface _PTSAppearanceCondition : NSObject {
	NSString* _conditionKeyPath; 
	NSPredicate* _conditionPredicate; 
}
@property (nonatomic,retain) NSString* conditionKeyPath; 				//@synthesize conditionKeyPath=_conditionKeyPath - In the implementation block
@property (nonatomic,retain) NSPredicate* conditionPredicate; 				//@synthesize conditionPredicate=_conditionPredicate - In the implementation block
+(id)appearanceConditionWithPredicate:(id)arg1;
-(void)addKeyPathPrefix:(id)arg1;
-(BOOL)evaluateWithSettings:(id)arg1;
-(void)setConditionPredicate:(id)arg1;
-(void)setConditionKeyPath:(id)arg1;
-(void).cxx_destruct;
@end