/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:18:03 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <PLCrashReportFormatter.h>

@interface BITPLCrashReportTextFormatter : NSObject <PLCrashReportFormatter> {
	int _textFormat; 
	unsigned _stringEncoding; 
}
+(id)formatStackFrame:(id)arg1 frameIndex:(unsigned)arg2 report:(id)arg3 lp64:(BOOL)arg4;
+(id)stringValueForCrashReport:(id)arg1 withTextFormat:(int)arg2;
-(id)formatReport:(id)arg1 error:(id*)arg2;
-(id)initWithTextFormat:(int)arg1 stringEncoding:(unsigned)arg2;
@end