/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:18:05 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface BITPLCrashReportRegisterInfo : NSObject {
	NSString* _registerName; 
	unsigned long long _registerValue; 
}
@property (nonatomic,copy) NSString* registerName; 				//@synthesize registerName=_registerName - In the implementation block
@property (nonatomic,copy) unsigned long long registerValue; 				//@synthesize registerValue=_registerValue - In the implementation block
-(id)initWithRegisterName:(id)arg1 registerValue:(unsigned long long)arg2;
-(void)dealloc;
@end