/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:21:26 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <NSCoding.h>
#import <NSCopying.h>
#import <NSMutableCopying.h>

@interface CPTShadow : NSObject <NSCoding, NSCopying, NSMutableCopying> {
	CGSize shadowOffset; 
	float shadowBlurRadius; 
	CPTColor* shadowColor; 
}
@property (assign,nonatomic) CGSize shadowOffset; 
@property (assign,nonatomic) float shadowBlurRadius; 
@property (nonatomic,retain) CPTColor* shadowColor; 
-(void)setShadowInContext:(struct CGContext*)arg1;
-(void)dealloc;
-(id)initWithCoder:(id)arg1;
-(void)encodeWithCoder:(id)arg1;
-(id)init;
-(id)copyWithZone:(NSZone*)arg1;
-(void)setShadowColor:(id)arg1;
-(void)setShadowOffset:(CGSize)arg1;
-(void)setShadowBlurRadius:(float)arg1;
-(id)mutableCopyWithZone:(NSZone*)arg1;
@end