/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:26:07 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <NSCacheDelegate.h>

@interface FBCacheIndex : NSObject <NSCacheDelegate> {
	id<FBCacheIndexFileDelegate> _delegate; 
	NSCache* _cachedEntries; 
	unsigned _currentDiskUsage; 
	unsigned _diskCapacity; 
	struct sqlite3* _database; 
	struct sqlite3_stmt* _insertStatement; 
	struct sqlite3_stmt* _removeByKeyStatement; 
	struct sqlite3_stmt* _selectByKeyStatement; 
	struct sqlite3_stmt* _selectByKeyFragmentStatement; 
	struct sqlite3_stmt* _selectExcludingKeyFragmentStatement; 
	struct sqlite3_stmt* _trimStatement; 
	struct sqlite3_stmt* _updateStatement; 
	struct dispatch_queue_s* _databaseQueue; 
}
@property (assign) id delegate; 				//@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,copy) unsigned currentDiskUsage; 				//@synthesize currentDiskUsage=_currentDiskUsage - In the implementation block
@property (assign,nonatomic) unsigned diskCapacity; 				//@synthesize diskCapacity=_diskCapacity - In the implementation block
@property (assign,nonatomic) unsigned entryCacheCountLimit; 
@property (nonatomic,copy) struct dispatch_queue_s* databaseQueue; 				//@synthesize databaseQueue=_databaseQueue - In the implementation block
-(void)_fetchCurrentDiskUsage;
-(id)_entryForKey:(id)arg1;
-(void)_writeEntryInDatabase:(id)arg1;
-(void)_trimDatabase;
-(void)_removeEntryFromDatabaseForKey:(id)arg1;
-(id)_readEntriesFromDatabase:(id)arg1 excludingFragment:(BOOL)arg2;
-(id)_readEntryFromDatabase:(id)arg1;
-(void)_updateEntryInDatabaseForKey:(id)arg1 entry:(id)arg2;
-(id)_createCacheEntityInfo:(struct sqlite3_stmt*)arg1;
-(void)_dropTrimmingTable;
-(void)_flushOrphanedFiles;
-(id)initWithCacheFolder:(id)arg1;
-(void)setEntryCacheCountLimit:(unsigned)arg1;
-(id)fileNameForKey:(id)arg1;
-(id)storeFileForKey:(id)arg1 withData:(id)arg2;
-(void)removeEntries:(id)arg1 excludingFragment:(BOOL)arg2;
-(void)cache:(id)arg1 willEvictObject:(id)arg2;
-(void)setDiskCapacity:(unsigned)arg1;
-(void)removeEntryForKey:(id)arg1;
-(void)dealloc;
-(void)setDelegate:(id)arg1;
@end