/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:18:44 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol UISearchDisplayDelegate
@optional
-(void)searchDisplayController(id):arg1 willUnloadSearchResultsTableView(id):arg2 ;
-(void)searchDisplayController(id):arg1 willShowSearchResultsTableView(id):arg2 ;
-(void)searchDisplayController(id):arg1 didShowSearchResultsTableView(id):arg2 ;
-(void)searchDisplayController(id):arg1 willHideSearchResultsTableView(id):arg2 ;
-(void)searchDisplayController(id):arg1 didHideSearchResultsTableView(id):arg2 ;
-(void)searchDisplayControllerDidBeginSearch(id):arg1 ;
-(void)searchDisplayControllerDidEndSearch(id):arg1 ;
-(void)searchDisplayControllerWillBeginSearch(id):arg1 ;
-(void)searchDisplayControllerWillEndSearch(id):arg1 ;
-(BOOL)searchDisplayController(id):arg1 shouldReloadTableForSearchString(id):arg2 ;
-(BOOL)searchDisplayController(id):arg1 shouldReloadTableForSearchScope(int):arg2 ;
-(void)searchDisplayController(id):arg1 didLoadSearchResultsTableView(id):arg2 ;
@end

@protocol UISearchBarDelegate
@optional
-(void)searchBar(id):arg1 textDidChange(id):arg2 ;
-(void)searchBar(id):arg1 selectedScopeButtonIndexDidChange(int):arg2 ;
-(BOOL)searchBarShouldBeginEditing(id):arg1 ;
-(BOOL)searchBarShouldEndEditing(id):arg1 ;
-(void)searchBarCancelButtonClicked(id):arg1 ;
-(void)searchBarBookmarkButtonClicked(id):arg1 ;
-(void)searchBarResultsListButtonClicked(id):arg1 ;
-(void)searchBarTextDidBeginEditing(id):arg1 ;
-(void)searchBarTextDidEndEditing(id):arg1 ;
-(void)searchBarSearchButtonClicked(id):arg1 ;
-(BOOL)searchBar(id):arg1 shouldChangeTextInRange({):arg2 replacementText(_):arg3 ;
@end

@protocol FBDialogDelegate
@optional
-(void)dialogDidComplete(id):arg1 ;
-(void)dialogCompleteWithUrl(id):arg1 ;
-(void)dialogDidNotCompleteWithUrl(id):arg1 ;
-(void)dialogDidNotComplete(id):arg1 ;
-(void)dialog(id):arg1 didFailWithError(id):arg2 ;
-(BOOL)dialog(id):arg1 shouldOpenURLInExternalBrowser(id):arg2 ;
@end
