/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:25:54 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface FBGraphObjectArray : NSMutableArray {
	NSMutableArray* _jsonArray; 
}
-(void)graphObjectifyAll;
-(id)initWrappingArray:(id)arg1;
-(id)graphObjectifyAtIndex:(unsigned)arg1;
-(void)dealloc;
-(unsigned)count;
-(id)objectAtIndex:(unsigned)arg1;
-(void)addObject:(id)arg1;
-(void)removeLastObject;
-(id)reverseObjectEnumerator;
-(void)insertObject:(id)arg1 atIndex:(unsigned)arg2;
-(void)removeObjectAtIndex:(unsigned)arg1;
-(id)objectEnumerator;
-(void)replaceObjectAtIndex:(unsigned)arg1 withObject:(id)arg2;
@end