/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:25:11 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface FBSettings : NSObject {
}
+(id)loggingBehavior;
+(void)autoPublishInstall:(id)arg1;
+(BOOL)shouldAutoPublishInstall;
+(void)publishInstall:(id)arg1;
+(void)setLoggingBehavior:(id)arg1;
+(void)setShouldAutoPublishInstall:(BOOL)arg1;
@end