/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:19:01 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface FMMediaClockFormat : FMEnum {
}
+(id)CLOCK1;
+(id)CLOCK2;
+(id)CLOCKTEXT1;
+(id)CLOCKTEXT2;
+(id)CLOCKTEXT3;
+(id)valueOf:(id)arg1;
+(id)values;
@end