/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:23:12 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface FriendsTrackToplistsReply_Builder : PBGeneratedMessage_Builder {
	FriendsTrackToplistsReply* result; 
}
@property (retain) FriendsTrackToplistsReply* result; 
-(id)buildPartial;
-(id)mergeFromCodedInputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
-(id)mergeFrom:(id)arg1;
-(id)internalGetResult;
-(id)clone;
-(id)setTracksArray:(id)arg1;
-(id)tracksAtIndex:(unsigned)arg1;
-(id)addTracks:(id)arg1;
-(id)setTracksValues:(id*)arg1 count:(unsigned)arg2;
-(id)clearTracks;
-(id)defaultInstance;
-(void)dealloc;
-(id)init;
-(id)clear;
-(void)setResult:(id)arg1;
-(id)build;
-(id)tracks;
@end