/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:17:46 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <GaiaDestinationPickerViewControllerDelegate.h>
#import <UIAlertViewDelegate.h>
#import <SPTGaiaDeviceStateManagerObserver.h>
#import <SPFeature.h>
#import <GaiaFeature.h>

@interface GaiaFeatureImplementation : NSObject <GaiaDestinationPickerViewControllerDelegate, UIAlertViewDelegate, SPTGaiaDeviceStateManagerObserver, SPFeature, GaiaFeature> {
	struct scoped_ptr<spTPMRemotePlayer> _playerPlayer; 
	struct GaiaFeatureImplementationCpp _cpp; 
	id<BaseFeature> _baseUI; 
	id<LegacyFeature> _legacy; 
	id<NowPlayingFeature> _nowPlaying; 
	id<SettingsFeature> _settings; 
	SPTGaiaDeviceManager* _deviceManager; 
	GaiaLocalAudioSessionController* _audioSessionController; 
	GaiaVolumeController* _volumeController; 
	GaiaMessageBarController* _messageBarController; 
	GaiaPlaybackGrabberController* _playbackGrabberController; 
	GaiaBackgroundController* _backgroundController; 
	SPTGaiaDevicePickerViewController* _devicePickerViewController; 
	SPNavigationController* _devicePickerNavigationController; 
	GaiaDestinationPickerViewController* _destinationPickerViewController; 
	SPNavigationController* _destinationPickerNavigationController; 
	UIPopoverController* _destinationPickerPopoverController; 
	GaiaPlayerControl* _gaiaPlayerControl; 
	GaiaPlayerControl* _gaiaBarControl; 
}
@property (assign,nonatomic,__weak) id<BaseFeature> baseUI; 				//@synthesize baseUI=_baseUI - In the implementation block
@property (assign,nonatomic,__weak) id<LegacyFeature> legacy; 				//@synthesize legacy=_legacy - In the implementation block
@property (assign,nonatomic,__weak) id<NowPlayingFeature> nowPlaying; 				//@synthesize nowPlaying=_nowPlaying - In the implementation block
@property (assign,nonatomic,__weak) id<SettingsFeature> settings; 				//@synthesize settings=_settings - In the implementation block
@property (nonatomic,retain) SPTGaiaDeviceManager* deviceManager; 				//@synthesize deviceManager=_deviceManager - In the implementation block
@property (nonatomic,retain) GaiaLocalAudioSessionController* audioSessionController; 				//@synthesize audioSessionController=_audioSessionController - In the implementation block
@property (nonatomic,retain) GaiaVolumeController* volumeController; 				//@synthesize volumeController=_volumeController - In the implementation block
@property (nonatomic,retain) GaiaMessageBarController* messageBarController; 				//@synthesize messageBarController=_messageBarController - In the implementation block
@property (nonatomic,retain) GaiaPlaybackGrabberController* playbackGrabberController; 				//@synthesize playbackGrabberController=_playbackGrabberController - In the implementation block
@property (nonatomic,retain) GaiaBackgroundController* backgroundController; 				//@synthesize backgroundController=_backgroundController - In the implementation block
@property (nonatomic,retain) SPTGaiaDevicePickerViewController* devicePickerViewController; 				//@synthesize devicePickerViewController=_devicePickerViewController - In the implementation block
@property (nonatomic,retain) SPNavigationController* devicePickerNavigationController; 				//@synthesize devicePickerNavigationController=_devicePickerNavigationController - In the implementation block
@property (nonatomic,retain) GaiaDestinationPickerViewController* destinationPickerViewController; 				//@synthesize destinationPickerViewController=_destinationPickerViewController - In the implementation block
@property (nonatomic,retain) SPNavigationController* destinationPickerNavigationController; 				//@synthesize destinationPickerNavigationController=_destinationPickerNavigationController - In the implementation block
@property (nonatomic,retain) UIPopoverController* destinationPickerPopoverController; 				//@synthesize destinationPickerPopoverController=_destinationPickerPopoverController - In the implementation block
@property (nonatomic,retain) GaiaPlayerControl* gaiaPlayerControl; 				//@synthesize gaiaPlayerControl=_gaiaPlayerControl - In the implementation block
@property (nonatomic,retain) GaiaPlayerControl* gaiaBarControl; 				//@synthesize gaiaBarControl=_gaiaBarControl - In the implementation block
+(id)featureIdentifier;
+(id)featureDependencies;
-(void)setMessageBarController:(id)arg1;
-(void)configureWithFeatures:(id)arg1;
-(id)provideGaiaSettings;
-(id)provideSettingsSectionForViewController:(id)arg1;
-(void)setupGaiaCore;
-(id)provideDestinationPickerViewController;
-(void)setupGaiaTheme;
-(void)setupGaiaUI;
-(void)setAudioSessionController:(id)arg1;
-(void)setVolumeController:(id)arg1;
-(void)setDestinationPickerViewController:(id)arg1;
-(void)setDestinationPickerNavigationController:(id)arg1;
-(void)setDestinationPickerPopoverController:(id)arg1;
-(void)setGaiaBarControl:(id)arg1;
-(void)setBackgroundController:(id)arg1;
-(void)gaiaPlayerControlAction;
-(void)gaiaBarControlAction;
-(void)setPlaybackGrabberController:(id)arg1;
-(void)setDevicePickerViewController:(id)arg1;
-(void)setDevicePickerNavigationController:(id)arg1;
-(void)presentDevicePicker;
-(void)presentDestinationPicker:(id)arg1 view:(id)arg2;
-(BOOL)shouldShowGaiaPicker;
-(id)provideGaiaButton;
-(id)provideGaiaBarButton;
-(id)provideGaiaDeviceStateManager;
-(void)deviceStateManager:(id)arg1 device:(id)arg2 onlineStatusDidChange:(BOOL)arg3;
-(void)productStateDidChangeNotification:(id)arg1;
-(void)userDidDismissDestinationPicker:(id)arg1;
-(void)setGaiaPlayerControl:(id)arg1;
-(void)setBaseUI:(id)arg1;
-(void)unload;
-(id).cxx_construct;
-(void)load;
-(void)setSettings:(id)arg1;
-(void)setDeviceManager:(id)arg1;
-(void)setNowPlaying:(id)arg1;
-(void)setLegacy:(id)arg1;
-(void).cxx_destruct;
@end