/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:21:17 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <NSCopying.h>

@interface KKIndexPath : NSObject <NSCopying> {
	unsigned _index; 
	unsigned _section; 
}
@property (assign,nonatomic) unsigned section; 				//@synthesize section=_section - In the implementation block
@property (assign,nonatomic) unsigned index; 				//@synthesize index=_index - In the implementation block
+(id)indexPathForIndex:(unsigned)arg1 inSection:(unsigned)arg2;
+(id)zeroIndexPath;
+(id)indexPathWithNSIndexPath:(id)arg1;
+(id)indexPathsWithNSIndexPaths:(id)arg1;
+(id)nonexistantIndexPath;
-(id)initWithIndex:(unsigned)arg1 section:(unsigned)arg2;
-(id)initWithNSIndexPath:(id)arg1;
-(id)NSIndexPath;
-(BOOL)isEqual:(id)arg1;
-(unsigned)hash;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1;
-(int)compare:(id)arg1;
-(void)setSection:(unsigned)arg1;
-(void)setIndex:(unsigned)arg1;
@end