/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:25:25 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <NSCoding.h>

@interface LoginPLIStatusModel : NSObject <NSCoding> {
	BOOL _pli; 
	NSString* _country; 
	NSString* _pli_url; 
}
@property (nonatomic,copy) NSString* country; 				//@synthesize country=_country - In the implementation block
@property (assign,nonatomic) BOOL pli; 				//@synthesize pli=_pli - In the implementation block
@property (nonatomic,copy) NSString* pli_url; 				//@synthesize pli_url=_pli_url - In the implementation block
-(void)setPli:(BOOL)arg1;
-(void)setPli_url:(id)arg1;
-(void)setCountry:(id)arg1;
-(id)initWithCoder:(id)arg1;
-(void)encodeWithCoder:(id)arg1;
-(void).cxx_destruct;
@end