/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:22:46 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface NowPlayingBarInformationPreviewView : NowPlayingBarInformationView {
	BOOL _textRoll; 
	SPTrack* _track; 
	NowPlayingBarInformationPreviewBarView* _barView; 
	NSTimer* _shufflePlayTimer; 
}
@property (nonatomic,retain) SPTrack* track; 				//@synthesize track=_track - In the implementation block
@property (nonatomic,retain) NowPlayingBarInformationPreviewBarView* barView; 				//@synthesize barView=_barView - In the implementation block
@property (assign,nonatomic) BOOL textRoll; 				//@synthesize textRoll=_textRoll - In the implementation block
@property (nonatomic,retain) NSTimer* shufflePlayTimer; 				//@synthesize shufflePlayTimer=_shufflePlayTimer - In the implementation block
-(void)setTextRoll:(BOOL)arg1;
-(void)setBarView:(id)arg1;
-(void)shufflePlayTimerFired:(id)arg1;
-(void)setShufflePlayTimer:(id)arg1;
-(void)dealloc;
-(id)initWithTrack:(id)arg1;
-(void)setTrack:(id)arg1;
-(void).cxx_destruct;
@end