/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:24:37 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol SPFeature
@optional
+(id)featureDependencies;
-(void)load;
@required
+(id)featureIdentifier;
-(void)configureWithFeatures(id):arg1 ;
-(void)unload;
-(void)configureWithFeatures(id):arg1 ;
-(void)unload;
@end

@protocol NowPlayingFeature
@required
-(id)provideNowPlayingSettings;
-(id)provideNowPlayingManager;
-(id)providePlayerView;
-(id)providePlayerBarView;
-(id)provideNowPlayingSettings;
-(id)provideNowPlayingManager;
-(id)providePlayerView;
-(id)providePlayerBarView;
@end
