/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:25:12 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface NSKVONotifying_SPTNowPlayingBarModel : SPTNowPlayingBarModel {
}
-(void)setContextURL:(id)arg1;
-(void)setPlaying:(BOOL)arg1;
-(void)setDisplayedMetadata:(id)arg1;
-(Class)class;
-(void)dealloc;
-(BOOL)_isKVOA;
@end