/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:22:53 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PlaylistFilterTextField : UITextField {
	UIImageView* _icon; 
}
@property (nonatomic,retain) UIImageView* icon; 				//@synthesize icon=_icon - In the implementation block
-(id)createCustomClearButton;
-(void)textDidChange;
-(id)initWithFrame:(CGRect)arg1;
-(void)dealloc;
-(BOOL)resignFirstResponder;
-(CGRect)editingRectForBounds:(CGRect)arg1;
-(CGRect)textRectForBounds:(CGRect)arg1;
-(void)setIcon:(id)arg1;
-(CGRect)rightViewRectForBounds:(CGRect)arg1;
-(CGRect)placeholderRectForBounds:(CGRect)arg1;
-(void)clear;
-(void)drawPlaceholderInRect:(CGRect)arg1;
-(void).cxx_destruct;
@end