/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:22:27 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <NSCopying.h>

@interface PTSRowAction : NSObject <NSCopying> {
	BOOL _deselectRowOnSuccess; 
	id _handler; 
}
@property (nonatomic,copy) id handler; 				//@synthesize handler=_handler - In the implementation block
@property (assign,nonatomic) BOOL deselectRowOnSuccess; 				//@synthesize deselectRowOnSuccess=_deselectRowOnSuccess - In the implementation block
+(id)action;
+(id)actionWithHandler:(id)arg1;
-(id)init;
-(id)copyWithZone:(NSZone*)arg1;
-(void)setHandler:(id)arg1;
-(void)resolveTemplatesWithIndex:(unsigned)arg1;
-(void)setDeselectRowOnSuccess:(BOOL)arg1;
-(void).cxx_destruct;
@end