/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:25:15 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface SPSendTracksRequest : SPSessionRequest {
	NSArray* _tracks; 
	NSString* _message; 
	NSString* _username; 
	NSString* _facebookId; 
}
@property (nonatomic,copy) NSArray* tracks; 				//@synthesize tracks=_tracks - In the implementation block
@property (nonatomic,copy) NSString* message; 				//@synthesize message=_message - In the implementation block
@property (nonatomic,copy) NSString* username; 				//@synthesize username=_username - In the implementation block
@property (nonatomic,copy) NSString* facebookId; 				//@synthesize facebookId=_facebookId - In the implementation block
-(id)initWithTracks:(id)arg1 message:(id)arg2 toUsername:(id)arg3;
-(void)startWithSession:(struct Session*)arg1;
-(id)initWithTracks:(id)arg1 message:(id)arg2 toFacebookId:(id)arg3;
-(void)dealloc;
@end