/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:23:57 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface SPSocialDecorationData : NSObject {
	BOOL _subscribed; 
	NSString* _canonicalUsername; 
	NSString* _displayName; 
	NSString* _image; 
	NSString* _imageLarge; 
	NSString* _firstName; 
	NSString* _lastName; 
	NSString* _facebookUID; 
}
@property (nonatomic,retain) NSString* canonicalUsername; 				//@synthesize canonicalUsername=_canonicalUsername - In the implementation block
@property (nonatomic,retain) NSString* displayName; 				//@synthesize displayName=_displayName - In the implementation block
@property (nonatomic,retain) NSString* image; 				//@synthesize image=_image - In the implementation block
@property (nonatomic,retain) NSString* imageLarge; 				//@synthesize imageLarge=_imageLarge - In the implementation block
@property (nonatomic,retain) NSString* firstName; 				//@synthesize firstName=_firstName - In the implementation block
@property (nonatomic,retain) NSString* lastName; 				//@synthesize lastName=_lastName - In the implementation block
@property (nonatomic,retain) NSString* facebookUID; 				//@synthesize facebookUID=_facebookUID - In the implementation block
@property (assign,nonatomic) BOOL subscribed; 				//@synthesize subscribed=_subscribed - In the implementation block
-(void)setCanonicalUsername:(id)arg1;
-(void)setImageLarge:(id)arg1;
-(void)setFacebookUID:(id)arg1;
-(id)initWithCanonicalUsername:(id)arg1 displayName:(id)arg2 image:(id)arg3 imageLarge:(id)arg4 firstName:(id)arg5 lastName:(id)arg6 fbUID:(id)arg7 subscribed:(BOOL)arg8;
-(void)setSubscribed:(BOOL)arg1;
-(void)setImage:(id)arg1;
-(void)setDisplayName:(id)arg1;
-(void)setFirstName:(id)arg1;
-(void)setLastName:(id)arg1;
-(void).cxx_destruct;
@end