/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:23:55 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <SPTAlbumsViewModelData.h>

@interface SPTAlbumsViewModelData : NSObject <SPTAlbumsViewModelData> {
	NSArray* _albums; 
	unsigned _albumsCount; 
	double _loadTime; 
}
@property (assign,nonatomic) double loadTime; 				//@synthesize loadTime=_loadTime - In the implementation block
@property (nonatomic,retain) NSArray* albums; 				//@synthesize albums=_albums - In the implementation block
@property (assign,nonatomic) unsigned albumsCount; 				//@synthesize albumsCount=_albumsCount - In the implementation block
-(void)setLoadTime:(double)arg1;
-(void)setAlbumsCount:(unsigned)arg1;
-(void)setAlbums:(id)arg1;
-(void).cxx_destruct;
@end