/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:23:56 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface SPTArtistAlbumsViewModel : SPTSingleRequestViewModel {
	NSURL* _artistURL; 
	unsigned _type; 
}
@property (nonatomic,copy) NSURL* artistURL; 				//@synthesize artistURL=_artistURL - In the implementation block
@property (assign,nonatomic) unsigned type; 				//@synthesize type=_type - In the implementation block
+(id)requestURLFromArtistURL:(id)arg1 type:(unsigned)arg2;
+(id)viewNameFromEnum:(unsigned)arg1;
+(void)preloadDataForArtist:(id)arg1 type:(unsigned)arg2 router:(id)arg3;
-(id)dataWithDictionary:(id)arg1;
-(id)albumsWithArray:(id)arg1;
-(id)initWithArtist:(id)arg1 type:(unsigned)arg2 router:(id)arg3 offlineModeState:(id)arg4;
-(id)parseResponse:(id)arg1 error:(id*)arg2;
-(void)setType:(unsigned)arg1;
-(void).cxx_destruct;
@end