/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:21:00 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <PlayableContextProtocol.h>
#import <SPObjectRepresentation.h>
#import <SPTHTTPImageLoaderDelegate.h>
#import <SPContentInsetViewController.h>
#import <SPTCollectionArtistsModelDelegate.h>

@interface SPTCollectionArtistsViewController : UITableViewController <PlayableContextProtocol, SPObjectRepresentation, SPTHTTPImageLoaderDelegate, SPContentInsetViewController, SPTCollectionArtistsModelDelegate> {
	SPTCollectionArtistsModel* _model; 
	SPTHTTPImageLoader* _imageLoader; 
	id<PlayableContextProtocolDelegate> _contextDelegate; 
	SPTInfoView* _infoView; 
	int _savedSeparatorStyle; 
}
@property (nonatomic,retain) SPTInfoView* infoView; 				//@synthesize infoView=_infoView - In the implementation block
@property (assign,nonatomic) int savedSeparatorStyle; 				//@synthesize savedSeparatorStyle=_savedSeparatorStyle - In the implementation block
@property (assign,nonatomic) id<PlayableContextProtocolDelegate> contextDelegate; 				//@synthesize contextDelegate=_contextDelegate - In the implementation block
@property (nonatomic,copy) NSURL* URL; 
@property (assign,nonatomic) BOOL automaticallyAdjustsScrollViewInsets; 
-(void)imageLoader:(id)arg1 didFinishLoadingImage:(id)arg2 forURL:(id)arg3 context:(id)arg4 loadedSynchronously:(BOOL)arg5;
-(id)viewEventURI;
-(id)getContext;
-(void)setContextDelegate:(id)arg1;
-(void)sp_updateContentInsets;
-(void)setInfoView:(id)arg1;
-(unsigned)p_offlineSyncStatusForArtistAtIndex:(unsigned)arg1;
-(void)artistsModelDidUpdate:(id)arg1;
-(void)metadataDidUpdate:(id)arg1 forArtist:(id)arg2;
-(void)updateInfoView:(BOOL)arg1;
-(void)discoverButtonTapped;
-(void)setSavedSeparatorStyle:(int)arg1;
-(id)initWithModel:(id)arg1;
-(void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
-(void)tableView:(id)arg1 didEndDisplayingCell:(id)arg2 forRowAtIndexPath:(id)arg3;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
-(int)numberOfSectionsInTableView:(id)arg1;
-(void)viewDidLayoutSubviews;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1;
-(void).cxx_destruct;
@end