/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:26:09 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <SPTCellAccessoryView.h>

@interface SPTGaiaIconView : UIView <SPTCellAccessoryView> {
	int _currentState; 
	int _type; 
	CAShapeLayer* _arc; 
	CAShapeLayer* _speaker; 
	CAShapeLayer* _soundWave1; 
	CAShapeLayer* _soundWave2; 
	CAShapeLayer* _soundWave3; 
	CALayer* _pathLayer; 
	CAGradientLayer* _gradientLayer; 
	CALayer* _shadowLayer; 
	unsigned _activityAnimationRepeatCount; 
}
@property (assign,nonatomic) int state; 				//@synthesize currentState=_currentState - In the implementation block
@property (nonatomic,copy) int type; 				//@synthesize type=_type - In the implementation block
@property (nonatomic,retain) CAShapeLayer* arc; 				//@synthesize arc=_arc - In the implementation block
@property (nonatomic,retain) CAShapeLayer* speaker; 				//@synthesize speaker=_speaker - In the implementation block
@property (nonatomic,retain) CAShapeLayer* soundWave1; 				//@synthesize soundWave1=_soundWave1 - In the implementation block
@property (nonatomic,retain) CAShapeLayer* soundWave2; 				//@synthesize soundWave2=_soundWave2 - In the implementation block
@property (nonatomic,retain) CAShapeLayer* soundWave3; 				//@synthesize soundWave3=_soundWave3 - In the implementation block
@property (nonatomic,retain) CALayer* pathLayer; 				//@synthesize pathLayer=_pathLayer - In the implementation block
@property (nonatomic,retain) CAGradientLayer* gradientLayer; 				//@synthesize gradientLayer=_gradientLayer - In the implementation block
@property (nonatomic,retain) CALayer* shadowLayer; 				//@synthesize shadowLayer=_shadowLayer - In the implementation block
@property (assign,nonatomic) unsigned activityAnimationRepeatCount; 				//@synthesize activityAnimationRepeatCount=_activityAnimationRepeatCount - In the implementation block
-(void)setState:(int)arg1 animated:(BOOL)arg2;
-(void)setGradientLayer:(id)arg1;
-(void)stopActivityAnimation:(BOOL)arg1;
-(void)startActivityAnimation;
-(void)performShakeAnimationWithCallback:(id)arg1;
-(void)setupArc;
-(void)setupSpeaker;
-(void)setupSoundWave1;
-(void)setupSoundWave2;
-(void)setupSoundWave3;
-(void)setupStyleForState:(int)arg1;
-(void)showArcAndSoundWaves:(BOOL)arg1 animated:(BOOL)arg2;
-(void)startActivityAnimationWithRepeatCount:(unsigned)arg1 beginTime:(double)arg2;
-(int)styleForState:(int)arg1;
-(void)setActivityAnimationRepeatCount:(unsigned)arg1;
-(void)setArc:(id)arg1;
-(void)setSpeaker:(id)arg1;
-(void)setSoundWave1:(id)arg1;
-(void)setSoundWave2:(id)arg1;
-(void)setSoundWave3:(id)arg1;
-(void)setPathLayer:(id)arg1;
-(void)setShadowLayer:(id)arg1;
-(void)setFrame:(CGRect)arg1;
-(void)setState:(int)arg1;
-(id)initWithType:(int)arg1;
-(void)animationDidStop:(id)arg1 finished:(BOOL)arg2;
-(void)removeAllAnimations;
-(void).cxx_destruct;
@end