/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:26:11 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface SPTGaiaIconButton : UIButton {
	SPTGaiaIconView* _iconView; 
}
@property (nonatomic,retain) SPTGaiaIconView* iconView; 				//@synthesize iconView=_iconView - In the implementation block
+(id)buttonWithIconView:(id)arg1 target:(id)arg2 action:(SEL)arg3;
-(id)initWithIconView:(id)arg1 target:(id)arg2 action:(SEL)arg3;
-(void)setIconView:(id)arg1;
-(void).cxx_destruct;
@end