/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:23:12 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol AddToPlaylistDelegate
@optional
-(void)addToPlaylist(id):arg1 addedTracks(id):arg2 toPlaylist(id):arg3 ;
-(void)addToPlaylistDismissed(id):arg1 ;
@end

@protocol SPTCoverArtProvidingController
@required
-(id)presentationControlView;
-(id)presentationArtImageView;
-(id)presentationArtImage;
-(id)presentationControlView;
-(id)presentationArtImageView;
-(id)presentationArtImage;
@end

@protocol SPTNowPlayingModelDelegate
@required
-(void)nowPlayingModelDidUpdateCollection(id):arg1 ;
-(void)nowPlayingModelDidChangeEntityType(id):arg1 ;
-(void)nowPlayingModel(id):arg1 didChangeTrackWithAnimation(int):arg2 newTrack(BOOL):arg3 interactively(BOOL):arg4 ;
-(void)nowPlayingModelDidUpdateDuration(id):arg1 ;
-(void)nowPlayingModelDidUpdateMetadata(id):arg1 ;
-(void)nowPlayingModelDidUpdateCollection(id):arg1 ;
-(void)nowPlayingModelDidChangeEntityType(id):arg1 ;
-(void)nowPlayingModel(id):arg1 didChangeTrackWithAnimation(int):arg2 newTrack(BOOL):arg3 interactively(BOOL):arg4 ;
-(void)nowPlayingModelDidUpdateDuration(id):arg1 ;
-(void)nowPlayingModelDidUpdateMetadata(id):arg1 ;
@end
