/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:23:24 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <SPTThemableView.h>

@interface SPTNowPlayingControlsContainerView : UIView <SPTThemableView> {
	id<SPTThemableViewLayoutDelegate> _layoutDelegate; 
	SPTNowPlayingLeftControlsContainerView* _leftControlsContainerView; 
	SPTNowPlayingPlayButton* _playButton; 
	UIButton* _nextButton; 
	UIButton* _connectButton; 
	NSArray* _verticalLeftControlsContainerViewLayoutConstraints; 
	NSArray* _verticalPlayButtonLayoutConstraints; 
	NSArray* _verticalConnectButtonLayoutConstraints; 
	NSArray* _horizontalLayoutConstraints; 
}
@property (nonatomic,retain) SPTNowPlayingLeftControlsContainerView* leftControlsContainerView; 				//@synthesize leftControlsContainerView=_leftControlsContainerView - In the implementation block
@property (nonatomic,retain) SPTNowPlayingPlayButton* playButton; 				//@synthesize playButton=_playButton - In the implementation block
@property (nonatomic,retain) UIButton* nextButton; 				//@synthesize nextButton=_nextButton - In the implementation block
@property (nonatomic,retain) UIButton* connectButton; 				//@synthesize connectButton=_connectButton - In the implementation block
@property (nonatomic,retain) NSArray* verticalLeftControlsContainerViewLayoutConstraints; 				//@synthesize verticalLeftControlsContainerViewLayoutConstraints=_verticalLeftControlsContainerViewLayoutConstraints - In the implementation block
@property (nonatomic,retain) NSArray* verticalPlayButtonLayoutConstraints; 				//@synthesize verticalPlayButtonLayoutConstraints=_verticalPlayButtonLayoutConstraints - In the implementation block
@property (nonatomic,retain) NSArray* verticalConnectButtonLayoutConstraints; 				//@synthesize verticalConnectButtonLayoutConstraints=_verticalConnectButtonLayoutConstraints - In the implementation block
@property (nonatomic,retain) NSArray* horizontalLayoutConstraints; 				//@synthesize horizontalLayoutConstraints=_horizontalLayoutConstraints - In the implementation block
@property (assign,nonatomic,__weak) id<SPTThemableViewLayoutDelegate> layoutDelegate; 				//@synthesize layoutDelegate=_layoutDelegate - In the implementation block
-(void)applyThemeLayout;
-(void)setLayoutDelegate:(id)arg1;
-(id)initWithFrame:(CGRect)arg1 andConnectButton:(id)arg2;
-(void)setHorizontalLayoutConstraints:(id)arg1;
-(void)setVerticalLeftControlsContainerViewLayoutConstraints:(id)arg1;
-(void)setVerticalPlayButtonLayoutConstraints:(id)arg1;
-(void)setVerticalConnectButtonLayoutConstraints:(id)arg1;
-(void)setLeftControlsContainerView:(id)arg1;
-(void)setConnectButton:(id)arg1;
-(void)setPlayButton:(id)arg1;
-(void)dealloc;
-(id)description;
-(void)setNextButton:(id)arg1;
-(void).cxx_destruct;
@end