/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:24:21 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <SPTThemableView.h>

@interface SPTNowPlayingBarPlayButton : UIButton <SPTThemableView> {
	BOOL _playing; 
	id<SPTThemableViewLayoutDelegate> _layoutDelegate; 
	struct UIEdgeInsets _touchInsets; 
}
@property (assign,getter=isPlaying,nonatomic) BOOL playing; 				//@synthesize playing=_playing - In the implementation block
@property (assign,nonatomic) struct UIEdgeInsets touchInsets; 				//@synthesize touchInsets=_touchInsets - In the implementation block
@property (assign,nonatomic,__weak) id<SPTThemableViewLayoutDelegate> layoutDelegate; 				//@synthesize layoutDelegate=_layoutDelegate - In the implementation block
+(id)button;
-(void)applyThemeLayout;
-(void)setLayoutDelegate:(id)arg1;
-(void)setTouchInsets:(struct UIEdgeInsets)arg1;
-(id)initWithFrame:(CGRect)arg1;
-(void)dealloc;
-(BOOL)pointInside:(CGPoint)arg1 withEvent:(id)arg2;
-(id)description;
-(void)setPlaying:(BOOL)arg1;
-(void).cxx_destruct;
@end