/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:23:04 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <SPTThemableView.h>

@interface SPTNowPlayingTitleButton : UIButton <SPTThemableView> {
	id<SPTThemableViewLayoutDelegate> _layoutDelegate; 
	unsigned _icon; 
}
@property (assign,nonatomic) unsigned icon; 				//@synthesize icon=_icon - In the implementation block
@property (assign,nonatomic,__weak) id<SPTThemableViewLayoutDelegate> layoutDelegate; 				//@synthesize layoutDelegate=_layoutDelegate - In the implementation block
-(void)applyThemeLayout;
-(void)setLayoutDelegate:(id)arg1;
-(id)initWithIcon:(unsigned)arg1;
-(void)dealloc;
-(void)setIcon:(unsigned)arg1;
-(void).cxx_destruct;
@end