/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:24:33 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface SPTWelcomeWrapperViewController : UIViewController {
	struct UIEdgeInsets _standardInsets; 
	BOOL _savedStandardInsets; 
	NSLayoutConstraint* _contentLockToTopTopConstraint; 
	NSLayoutConstraint* _contentCenterYConstraint; 
	BOOL _shouldCenterContentView; 
	UIViewController* _contentController; 
	UIScrollView* _scrollView; 
}
@property (nonatomic,copy) UIViewController* contentController; 				//@synthesize contentController=_contentController - In the implementation block
@property (nonatomic,copy) UIScrollView* scrollView; 				//@synthesize scrollView=_scrollView - In the implementation block
@property (nonatomic,copy) BOOL shouldCenterContentView; 				//@synthesize shouldCenterContentView=_shouldCenterContentView - In the implementation block
-(id)initWithContentController:(id)arg1;
-(CGRect)focusRectWhenKeybardShow;
-(void)updateScrollviewContentSize;
-(void)animateKeyboard:(id)arg1 show:(BOOL)arg2;
-(id)navigationItem;
-(void)viewDidLayoutSubviews;
-(id)title;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)loadView;
-(void)viewDidAppear:(BOOL)arg1;
-(void)viewDidDisappear:(BOOL)arg1;
-(void)keyboardWillShow:(id)arg1;
-(void)keyboardWillHide:(id)arg1;
-(void).cxx_destruct;
@end