/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:17:54 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <PlayableContextProtocol.h>

@interface UpsellShuffleContextViewController : UpsellStandardViewController <PlayableContextProtocol> {
	id<PlayableContextProtocolDelegate> contextDelegate; 
	SPTrackContext* _context; 
	UIButton* _secondaryButton; 
	id<Player> _player; 
}
@property (nonatomic,copy) SPTrackContext* context; 				//@synthesize context=_context - In the implementation block
@property (nonatomic,retain) UIButton* secondaryButton; 				//@synthesize secondaryButton=_secondaryButton - In the implementation block
@property (assign,nonatomic,__weak) id<Player> player; 				//@synthesize player=_player - In the implementation block
@property (assign,nonatomic) id<PlayableContextProtocolDelegate> contextDelegate; 
@property (nonatomic,copy) NSURL* URL; 
-(id)getContext;
-(void)setContextDelegate:(id)arg1;
-(id)mutableDictionaryWithShuffleTAInterfaceData;
-(id)ta_ShuffleJSONDictionary;
-(void)ta_pressSecondaryButton;
-(id)initWithTitle:(id)arg1 withMessage:(id)arg2 withPrimaryButtonTitle:(id)arg3 withViewEventURI:(id)arg4 withLogCenter:(id)arg5 context:(id)arg6 trackIndex:(id)arg7 player:(id)arg8;
-(void)setSecondaryButton:(id)arg1;
-(void).cxx_destruct;
-(void)setPlayer:(id)arg1;
@end