/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, March 22, 2014 at 2:44:32 PM Central European Standard Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface AutoScalingDescribeScalingProcessTypesRequest : AmazonServiceRequestConfig {
}
-(void)dealloc;
-(id)init;
-(id)description;
@end