/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, March 22, 2014 at 3:01:58 PM Central European Standard Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface EC2AllocateAddressResponse : EC2Response {
	NSString* publicIp; 
	NSString* domain; 
	NSString* allocationId; 
}
@property (nonatomic,retain) NSString* publicIp; 
@property (nonatomic,retain) NSString* domain; 
@property (nonatomic,retain) NSString* allocationId; 
-(void)setPublicIp:(id)arg1;
-(void)setAllocationId:(id)arg1;
-(void)dealloc;
-(id)init;
-(id)description;
-(void)setDomain:(id)arg1;
-(void)setException:(id)arg1;
@end