/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, March 22, 2014 at 2:45:26 PM Central European Standard Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface EC2DescribeInstancesRequest : AmazonServiceRequestConfig {
	NSMutableArray* instanceIds; 
	NSMutableArray* filters; 
}
@property (nonatomic,retain) NSMutableArray* instanceIds; 
@property (nonatomic,retain) NSMutableArray* filters; 
-(void)addInstanceId:(id)arg1;
-(void)setInstanceIds:(id)arg1;
-(void)dealloc;
-(id)init;
-(id)description;
-(void)setFilters:(id)arg1;
-(void)addFilter:(id)arg1;
@end