/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, March 22, 2014 at 3:02:28 PM Central European Standard Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface EC2PriceSchedule : NSObject {
	NSNumber* term; 
	NSNumber* price; 
	NSString* currencyCode; 
	_Bool active; 
	_Bool activeIsSet; 
}
@property (nonatomic,retain) NSNumber* term; 
@property (nonatomic,retain) NSNumber* price; 
@property (nonatomic,retain) NSString* currencyCode; 
@property (assign,nonatomic) _Bool active; 
@property (nonatomic,copy) _Bool activeIsSet; 
-(void)setTerm:(id)arg1;
-(void)dealloc;
-(id)init;
-(id)description;
-(void)setActive:(_Bool)arg1;
-(void)setCurrencyCode:(id)arg1;
-(void)setPrice:(id)arg1;
@end