/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, March 22, 2014 at 3:01:39 PM Central European Standard Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface EC2ReservedInstancesListing : NSObject {
	NSString* reservedInstancesListingId; 
	NSString* reservedInstancesId; 
	NSDate* createDate; 
	NSDate* updateDate; 
	NSString* status; 
	NSString* statusMessage; 
	NSMutableArray* instanceCounts; 
	NSMutableArray* priceSchedules; 
	NSMutableArray* tags; 
	NSString* clientToken; 
}
@property (nonatomic,retain) NSString* reservedInstancesListingId; 
@property (nonatomic,retain) NSString* reservedInstancesId; 
@property (nonatomic,retain) NSDate* createDate; 
@property (nonatomic,retain) NSDate* updateDate; 
@property (nonatomic,retain) NSString* status; 
@property (nonatomic,retain) NSString* statusMessage; 
@property (nonatomic,retain) NSMutableArray* instanceCounts; 
@property (nonatomic,retain) NSMutableArray* priceSchedules; 
@property (nonatomic,retain) NSMutableArray* tags; 
@property (nonatomic,retain) NSString* clientToken; 
-(void)addTag:(id)arg1;
-(void)addPriceSchedule:(id)arg1;
-(void)setReservedInstancesId:(id)arg1;
-(void)setPriceSchedules:(id)arg1;
-(void)setClientToken:(id)arg1;
-(void)setReservedInstancesListingId:(id)arg1;
-(void)addInstanceCount:(id)arg1;
-(void)setCreateDate:(id)arg1;
-(void)setUpdateDate:(id)arg1;
-(void)setInstanceCounts:(id)arg1;
-(void)dealloc;
-(id)init;
-(id)description;
-(void)setStatus:(id)arg1;
-(void)setTags:(id)arg1;
-(void)setStatusMessage:(id)arg1;
@end