/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, March 22, 2014 at 3:01:52 PM Central European Standard Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface EC2ReportInstanceStatusRequest : AmazonServiceRequestConfig {
	NSMutableArray* instances; 
	NSString* status; 
	NSDate* startTime; 
	NSDate* endTime; 
	NSMutableArray* reasonCodes; 
	NSString* descriptionValue; 
}
@property (nonatomic,retain) NSMutableArray* instances; 
@property (nonatomic,retain) NSString* status; 
@property (nonatomic,retain) NSDate* startTime; 
@property (nonatomic,retain) NSDate* endTime; 
@property (nonatomic,retain) NSMutableArray* reasonCodes; 
@property (nonatomic,retain) NSString* descriptionValue; 
-(void)addInstance:(id)arg1;
-(void)setInstances:(id)arg1;
-(void)setDescriptionValue:(id)arg1;
-(void)addReasonCode:(id)arg1;
-(void)setReasonCodes:(id)arg1;
-(void)dealloc;
-(id)init;
-(void)setStartTime:(id)arg1;
-(void)setStatus:(id)arg1;
-(void)setEndTime:(id)arg1;
@end