/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, March 22, 2014 at 3:00:26 PM Central European Standard Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface ElasticLoadBalancingSourceSecurityGroup : NSObject {
	NSString* ownerAlias; 
	NSString* groupName; 
}
@property (nonatomic,retain) NSString* ownerAlias; 
@property (nonatomic,retain) NSString* groupName; 
-(void)setOwnerAlias:(id)arg1;
-(void)dealloc;
-(id)init;
-(id)description;
-(void)setGroupName:(id)arg1;
@end