/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, March 22, 2014 at 3:02:37 PM Central European Standard Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface ElasticLoadBalancingCreateLoadBalancerListenersRequest : AmazonServiceRequestConfig {
	NSString* loadBalancerName; 
	NSMutableArray* listeners; 
}
@property (nonatomic,retain) NSString* loadBalancerName; 
@property (nonatomic,retain) NSMutableArray* listeners; 
-(id)initWithLoadBalancerName:(id)arg1 andListeners:(id)arg2;
-(void)setLoadBalancerName:(id)arg1;
-(void)setListeners:(id)arg1;
-(void)dealloc;
-(id)init;
-(id)description;
-(void)addListener:(id)arg1;
@end