/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, March 22, 2014 at 3:02:46 PM Central European Standard Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface ElasticLoadBalancingAppCookieStickinessPolicy : NSObject {
	NSString* policyName; 
	NSString* cookieName; 
}
@property (nonatomic,retain) NSString* policyName; 
@property (nonatomic,retain) NSString* cookieName; 
-(id)initWithPolicyName:(id)arg1 andCookieName:(id)arg2;
-(void)setCookieName:(id)arg1;
-(void)setPolicyName:(id)arg1;
-(void)dealloc;
-(id)init;
-(id)description;
@end