/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, March 22, 2014 at 2:45:12 PM Central European Standard Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface FBAppCall : NSObject {
	NSString* _ID; 
	NSError* _error; 
	FBDialogsData* _dialogData; 
	FBAppLinkData* _appLinkData; 
	FBAccessTokenData* _accessTokenData; 
}
@property (nonatomic,copy) NSString* ID; 				//@synthesize ID=_ID - In the implementation block
@property (nonatomic,retain) NSError* error; 				//@synthesize error=_error - In the implementation block
@property (nonatomic,retain) FBDialogsData* dialogData; 				//@synthesize dialogData=_dialogData - In the implementation block
@property (nonatomic,retain) FBAppLinkData* appLinkData; 				//@synthesize appLinkData=_appLinkData - In the implementation block
@property (nonatomic,retain) FBAccessTokenData* accessTokenData; 				//@synthesize accessTokenData=_accessTokenData - In the implementation block
+(void)handleDidBecomeActive;
+(id)appCallFromApplinkArgs_v2:(id)arg1 applinkArgs:(id)arg2 createTimeUTC:(id)arg3 originalQueryParameters:(id)arg4;
+(BOOL)handleOpenURL:(id)arg1 sourceApplication:(id)arg2 withSession:(id)arg3 fallbackHandler:(id)arg4;
+(BOOL)tryOpenSession:(id)arg1 withAccessToken:(id)arg2;
+(BOOL)invokeHandler:(id)arg1 withAccessToken:(id)arg2 appLinkData:(id)arg3;
+(void)invokeHandler:(id)arg1 withError:(id)arg2;
+(void)handleDidBecomeActiveWithSession:(id)arg1;
+(id)appCallFromURL:(id)arg1;
+(BOOL)handleOpenURL:(id)arg1 sourceApplication:(id)arg2;
+(BOOL)handleOpenURL:(id)arg1 sourceApplication:(id)arg2 fallbackHandler:(id)arg3;
+(BOOL)handleOpenURL:(id)arg1 sourceApplication:(id)arg2 withSession:(id)arg3;
+(void)openDeferredAppLink:(id)arg1;
-(void)setAccessTokenData:(id)arg1;
-(id)initWithID:(id)arg1 enforceScheme:(BOOL)arg2 appID:(id)arg3 urlSchemeSuffix:(id)arg4;
-(void)setAppLinkData:(id)arg1;
-(BOOL)isEqualToAppCall:(id)arg1;
-(void)setDialogData:(id)arg1;
-(void)setError:(id)arg1;
-(void)dealloc;
-(id)init;
-(BOOL)isEqual:(id)arg1;
-(unsigned)hash;
-(id)description;
-(BOOL)isValid;
-(void)setID:(id)arg1;
-(id)init:(BOOL)arg1;
@end