/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, March 22, 2014 at 3:01:28 PM Central European Standard Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <PRTweenLerpPeriod.h>

@interface PRTweenCGPointLerpPeriod : PRTweenLerpPeriod <PRTweenLerpPeriod> {
}
+(id)periodWithStartCGPoint:(CGPoint)arg1 endCGPoint:(CGPoint)arg2 duration:(float)arg3;
-(CGPoint)startCGPoint;
-(CGPoint)endCGPoint;
-(id)tweenedValueForProgress:(float)arg1;
-(CGPoint)tweenedCGPoint;
-(void)setProgress:(float)arg1;
@end