/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, March 22, 2014 at 3:02:11 PM Central European Standard Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface S3BucketTaggingConfiguration : NSObject {
	NSArray* tagsets; 
}
@property (nonatomic,retain) NSArray* tagsets; 
-(id)toXml;
-(void)setTagsets:(id)arg1;
-(void)dealloc;
@end