/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, March 22, 2014 at 3:01:09 PM Central European Standard Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface S3GetObjectResponse : S3Response {
	NSMutableDictionary* metadata; 
	NSOutputStream* outputStream; 
	NSDate* lastModified; 
	NSString* contentType; 
	NSString* redirectLocation; 
}
@property (nonatomic,retain) NSDate* lastModified; 
@property (nonatomic,retain) NSString* contentType; 
@property (nonatomic,retain) NSString* redirectLocation; 
-(id)getMetadataForKey:(id)arg1;
-(void)setRedirectLocation:(id)arg1;
-(void)setLastModified:(id)arg1;
-(void)setValue:(id)arg1 forHTTPHeaderField:(id)arg2;
-(void)setOutputStream:(id)arg1;
-(void)dealloc;
-(id)init;
-(id)description;
-(void)connection:(id)arg1 didReceiveData:(id)arg2;
-(void)setContentType:(id)arg1;
@end