/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, March 22, 2014 at 2:45:16 PM Central European Standard Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface SNSGetSubscriptionAttributesRequestMarshaller : NSObject {
}
+(id)createRequest:(id)arg1;
@end