/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, March 22, 2014 at 3:01:35 PM Central European Standard Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface VNActivityCount : NSObject {
	NSNumber* _notifications; 
}
@property (nonatomic,retain) NSNumber* notifications; 				//@synthesize notifications=_notifications - In the implementation block
-(void)setNotifications:(id)arg1;
-(id)initWithJSON:(id)arg1;
-(int)totalCount;
-(void).cxx_destruct;
@end