/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, March 22, 2014 at 3:02:48 PM Central European Standard Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <VNAPIRequestDelegate.h>

@interface VNAPIManager : NSObject <VNAPIRequestDelegate> {
	NSString* _sessionKey; 
	NSString* _username; 
	NSString* _password; 
	NSString* _userID; 
	NSString* _email; 
	BOOL _isAuthenticated; 
	BOOL _reauthenticating; 
	BOOL _captchaing; 
	BOOL _gzipEnabled; 
	NSMutableArray* _queuedRequests; 
	AFHTTPClient* _client; 
}
@property (nonatomic,retain) NSString* sessionKey; 
@property (nonatomic,retain) NSString* username; 
@property (nonatomic,retain) NSString* password; 
@property (nonatomic,retain) NSString* userID; 
@property (nonatomic,retain) NSString* email; 
@property (nonatomic,copy) NSString* userAgent; 
@property (assign,nonatomic) BOOL reauthenticating; 				//@synthesize reauthenticating=_reauthenticating - In the implementation block
@property (assign,nonatomic) BOOL captchaing; 				//@synthesize captchaing=_captchaing - In the implementation block
@property (nonatomic,retain) NSMutableArray* queuedRequests; 				//@synthesize queuedRequests=_queuedRequests - In the implementation block
@property (assign) BOOL gzipEnabled; 				//@synthesize gzipEnabled=_gzipEnabled - In the implementation block
@property (nonatomic,retain) AFHTTPClient* client; 				//@synthesize client=_client - In the implementation block
+(id)sharedInstance;
-(void)addHeadersToRequest:(id)arg1;
-(void)modifyRequest:(id)arg1;
-(id)request:(id)arg1 endpoint:(id)arg2 parameters:(id)arg3 success:(id)arg4 error:(id)arg5 failed:(id)arg6;
-(id)request:(id)arg1 endpoint:(id)arg2 parameters:(id)arg3 authNeeded:(BOOL)arg4 success:(id)arg5 error:(id)arg6 failed:(id)arg7;
-(id)request:(id)arg1 endpoint:(id)arg2 parameters:(id)arg3 authNeeded:(BOOL)arg4 success:(id)arg5 error:(id)arg6 failed:(id)arg7 encoding:(int)arg8;
-(id)request:(id)arg1 endpoint:(id)arg2 parameters:(id)arg3 authNeeded:(BOOL)arg4 success:(id)arg5 error:(id)arg6 failed:(id)arg7 backgroundCacheUpdate:(BOOL)arg8;
-(id)request:(id)arg1 endpoint:(id)arg2 parameters:(id)arg3 authNeeded:(BOOL)arg4 success:(id)arg5 error:(id)arg6 failed:(id)arg7 encoding:(int)arg8 backgroundCacheUpdate:(BOOL)arg9;
-(void)requestNeedsAuth:(id)arg1;
-(void)setSessionKey:(id)arg1;
-(void)requestNeedsCaptcha:(id)arg1 andUrl:(id)arg2;
-(void)captchaComplete:(BOOL)arg1;
-(void)reauthenticationComplete:(BOOL)arg1;
-(id)unauthenticatedRequest:(id)arg1 endpoint:(id)arg2 parameters:(id)arg3 success:(id)arg4 error:(id)arg5 failed:(id)arg6;
-(id)request:(id)arg1 endpoint:(id)arg2 parameters:(id)arg3 success:(id)arg4 error:(id)arg5 failed:(id)arg6 encoding:(int)arg7;
-(id)request:(id)arg1 endpoint:(id)arg2 parameters:(id)arg3 success:(id)arg4 error:(id)arg5 failed:(id)arg6 backgroundCacheUpdate:(BOOL)arg7;
-(void)cancelRequests:(id)arg1 endpoint:(id)arg2;
-(void)setReauthenticating:(BOOL)arg1;
-(void)setCaptchaing:(BOOL)arg1;
-(void)setQueuedRequests:(id)arg1;
-(void)setGzipEnabled:(BOOL)arg1;
-(void)setPassword:(id)arg1;
-(id)init;
-(void)setEmail:(id)arg1;
-(void)setUserID:(id)arg1;
-(void)setUsername:(id)arg1;
-(void)setClient:(id)arg1;
-(void).cxx_destruct;
-(void)cancelAllRequests;
@end