/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, March 22, 2014 at 3:02:37 PM Central European Standard Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface VNCaptureFlowViewController : VNViewController {
	VNVideoCapture* _videoCapture; 
	VNDraft* _draft; 
	VNComposedAsset* _composedAsset; 
}
@property (nonatomic,retain) VNVideoCapture* videoCapture; 				//@synthesize videoCapture=_videoCapture - In the implementation block
@property (nonatomic,retain) VNDraft* draft; 				//@synthesize draft=_draft - In the implementation block
@property (nonatomic,retain) VNComposedAsset* composedAsset; 				//@synthesize composedAsset=_composedAsset - In the implementation block
-(void)setDraft:(id)arg1;
-(void)setVideoCapture:(id)arg1;
-(void)setComposedAsset:(id)arg1;
-(void)prepareForSegue:(id)arg1 sender:(id)arg2;
-(void)hide;
-(void).cxx_destruct;
@end