/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, March 22, 2014 at 3:00:49 PM Central European Standard Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <NSCoding.h>
#import <NSCopying.h>

@interface VNCut : NSObject <NSCoding, NSCopying> {
	int _capturePosition; 
	UIImage* _thumbnail; 
	VNMediaFile* _file; 
	struct {
		long long value;
		int timescale;
		unsigned flags;
		long long epoch;
	} _videoStartTime; 
	struct {
		long long value;
		int timescale;
		unsigned flags;
		long long epoch;
	} _videoEndTime; 
	struct {
		long long value;
		int timescale;
		unsigned flags;
		long long epoch;
	} _audioStartTime; 
	struct {
		long long value;
		int timescale;
		unsigned flags;
		long long epoch;
	} _audioEndTime; 
	struct {
		long long value;
		int timescale;
		unsigned flags;
		long long epoch;
	} _audioCrossfadeEndTime; 
	struct {
		long long value;
		int timescale;
		unsigned flags;
		long long epoch;
	} _startTimestamp; 
}
@property (assign,nonatomic) struct duration; 
@property (nonatomic,copy) int capturePosition; 				//@synthesize capturePosition=_capturePosition - In the implementation block
@property (nonatomic,retain) UIImage* thumbnail; 				//@synthesize thumbnail=_thumbnail - In the implementation block
@property (nonatomic,retain) VNMediaFile* file; 				//@synthesize file=_file - In the implementation block
@property (nonatomic,copy) struct videoRange; 
@property (nonatomic,copy) struct audioRange; 
@property (nonatomic,copy) struct crossfadeRange; 
@property (nonatomic,copy) struct completeAudioRange; 
@property (assign,nonatomic) struct videoStartTime; 				//@synthesize videoStartTime=_videoStartTime - In the implementation block
@property (assign,nonatomic) struct videoEndTime; 				//@synthesize videoEndTime=_videoEndTime - In the implementation block
@property (assign,nonatomic) struct audioStartTime; 				//@synthesize audioStartTime=_audioStartTime - In the implementation block
@property (assign,nonatomic) struct audioEndTime; 				//@synthesize audioEndTime=_audioEndTime - In the implementation block
@property (assign,nonatomic) struct audioCrossfadeEndTime; 				//@synthesize audioCrossfadeEndTime=_audioCrossfadeEndTime - In the implementation block
@property (assign,nonatomic) struct startTimestamp; 				//@synthesize startTimestamp=_startTimestamp - In the implementation block
-(void)thumbnail:(id)arg1;
-(void)closeWriter:(id)arg1;
-(int)appendAudioSampleBuffer:(struct opaqueCMSampleBuffer*)arg1 crossfadeSample:(BOOL)arg2;
-(int)appendVideoSampleBuffer:(struct opaqueCMSampleBuffer*)arg1;
-(BOOL)openWriter:(id*)arg1;
-(BOOL)finalized;
-(void)imageAtTime:(struct )arg1 respectCapturePosition:(BOOL)arg2 completionBlock:(id)arg3;
-(int)writeSampleBuffer:(struct opaqueCMSampleBuffer*)arg1 ofType:(id)arg2;
-(id)initWithWorkingDirectory:(id)arg1 devicePosition:(int)arg2;
-(void)setVideoStartTime:(struct )arg1;
-(void)setVideoEndTime:(struct )arg1;
-(void)setAudioStartTime:(struct )arg1;
-(void)setAudioEndTime:(struct )arg1;
-(void)setAudioCrossfadeEndTime:(struct )arg1;
-(id)initWithCoder:(id)arg1;
-(void)encodeWithCoder:(id)arg1;
-(BOOL)isEqual:(id)arg1;
-(id)description;
-(void)setDuration:(struct )arg1;
-(id)copyWithZone:(NSZone*)arg1;
-(void)setThumbnail:(id)arg1;
-(void)setFile:(id)arg1;
-(void)setStartTimestamp:(struct )arg1;
-(void).cxx_destruct;
@end