/*
 * This header is generated by weak_classdump 0.2
 * on Saturday, March 22, 2014 at 3:02:00 PM Central European Standard Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface VNVenueHelper : NSObject {
	NSDictionary* _venueIconMapping; 
}
+(id)sharedInstance;
-(id)iconForVenue:(id)arg1 withType:(int)arg2;
-(id)imageName:(id)arg1 parent:(id)arg2 shortName:(id)arg3 name:(id)arg4;
-(id)imageWithCategory:(id)arg1 withType:(int)arg2;
-(id)suffixForType:(int)arg1;
-(BOOL)imageExists:(id)arg1;
-(id)iconForFeedVenue:(id)arg1 withType:(int)arg2;
-(id)iconForVenue:(id)arg1;
-(id)iconForFeedVenue:(id)arg1;
-(id)init;
-(void).cxx_destruct;
@end