/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:24:45 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <SPFeature.h>
#import <AdsFeature.h>

@interface AdsFeatureImplementation : NSObject <SPFeature, AdsFeature> {
	id<LegacyFeature> _legacy; 
	id<CosmosFeature> _cosmos; 
	id<SettingsFeature> _settings; 
	AdsManager* _adsManager; 
}
@property (assign,nonatomic,__weak) id<LegacyFeature> legacy; 				//@synthesize legacy=_legacy - In the implementation block
@property (assign,nonatomic,__weak) id<CosmosFeature> cosmos; 				//@synthesize cosmos=_cosmos - In the implementation block
@property (assign,nonatomic,__weak) id<SettingsFeature> settings; 				//@synthesize settings=_settings - In the implementation block
@property (nonatomic,retain) AdsManager* adsManager; 				//@synthesize adsManager=_adsManager - In the implementation block
@property (nonatomic,copy) BOOL isAdsEnabled; 
+(id)featureIdentifier;
+(id)featureDependencies;
-(BOOL)isTrialOrPremiumUser;
-(void)configureWithFeatures:(id)arg1;
-(void)setCosmos:(id)arg1;
-(id)provideSettingsSectionForViewController:(id)arg1;
-(BOOL)isWatchNowEnabled;
-(void)setAdsManager:(id)arg1;
-(id)provideAdsManager;
-(void)unload;
-(void)load;
-(void)setSettings:(id)arg1;
-(void)setLegacy:(id)arg1;
-(void).cxx_destruct;
@end