/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:22:06 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface ArtistViewSectionAlbum : ArtistViewSection {
	BOOL firstAlbumAfterSectionHeader; 
	BOOL _appearsOn; 
	SPAlbum* _album; 
	id<SPAlbumMetadata> _albumMetadata; 
}
@property (assign,getter=isFirstAlbumAfterSectionHeader,nonatomic) BOOL firstAlbumAfterSectionHeader; 
@property (nonatomic,retain) SPAlbum* album; 				//@synthesize album=_album - In the implementation block
@property (assign,getter=isAppearsOn,nonatomic) BOOL appearsOn; 				//@synthesize appearsOn=_appearsOn - In the implementation block
@property (nonatomic,retain) id<SPAlbumMetadata> albumMetadata; 				//@synthesize albumMetadata=_albumMetadata - In the implementation block
-(float)heightForHeader;
-(float)heightForRow:(int)arg1;
-(BOOL)sectionWithInlineHeader;
-(id)objectAtRow:(int)arg1;
-(void)setFirstAlbumAfterSectionHeader:(BOOL)arg1;
-(void)setAppearsOn:(BOOL)arg1;
-(void)setAlbumMetadata:(id)arg1;
-(id)headerView;
-(void)setAlbum:(id)arg1;
-(int)numberOfRowsInSection;
-(void).cxx_destruct;
@end