/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:24:07 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <SPCarouselDelegate.h>
#import <UIWebViewDelegate.h>

@interface BiographyViewControllerIPad : SPViewController <SPCarouselDelegate, UIWebViewDelegate> {
	UIScrollView* _scrollView; 
	UILabel* _titleLabel; 
	SPCarousel* _carousel; 
	UIWebView* _webView; 
	struct NSData* _artistId; 
	SPTask* _artistTask; 
	SPArtist* _artist; 
	NSArray* _pictures; 
	SPURL* _mainPicture; 
	NSString* _biography; 
}
@property (nonatomic,retain) UIScrollView* scrollView; 				//@synthesize scrollView=_scrollView - In the implementation block
@property (nonatomic,retain) UILabel* titleLabel; 				//@synthesize titleLabel=_titleLabel - In the implementation block
@property (nonatomic,retain) SPCarousel* carousel; 				//@synthesize carousel=_carousel - In the implementation block
@property (nonatomic,retain) UIWebView* webView; 				//@synthesize webView=_webView - In the implementation block
@property (nonatomic,retain) NSData* artistId; 				//@synthesize artistId=_artistId - In the implementation block
@property (nonatomic,retain) SPTask* artistTask; 				//@synthesize artistTask=_artistTask - In the implementation block
@property (nonatomic,retain) SPArtist* artist; 				//@synthesize artist=_artist - In the implementation block
@property (nonatomic,copy) NSArray* pictures; 				//@synthesize pictures=_pictures - In the implementation block
@property (nonatomic,retain) SPURL* mainPicture; 				//@synthesize mainPicture=_mainPicture - In the implementation block
@property (nonatomic,retain) NSString* biography; 				//@synthesize biography=_biography - In the implementation block
-(id)viewEventURI;
-(void)setBiography:(id)arg1;
-(int)stackedNavigationPageSize;
-(void)viewDidBecomeInactiveInStackedNavigation;
-(void)viewDidBecomeActiveInStackedNavigation;
-(void)setArtistId:(struct NSData*)arg1;
-(id)initWithArtistId:(struct NSData*)arg1;
-(void)setArtistTask:(id)arg1;
-(void)setPictures:(id)arg1;
-(void)setMainPicture:(id)arg1;
-(void)setCarousel:(id)arg1;
-(void)delayedStartLoading;
-(unsigned)numberOfItemsInSPCarousel:(id)arg1;
-(id)SPCarousel:(id)arg1 imageLinkObjectForItemAtIndex:(unsigned)arg2;
-(void)cancelLoading;
-(void)startLoading;
-(void)setArtist:(id)arg1;
-(void)dealloc;
-(void)setScrollView:(id)arg1;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)loadView;
-(void)viewDidDisappear:(BOOL)arg1;
-(void)setWebView:(id)arg1;
-(void)updateView;
-(BOOL)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(int)arg3;
-(void)webViewDidFinishLoad:(id)arg1;
-(id)initWithURL:(id)arg1;
-(void)setTitleLabel:(id)arg1;
-(void).cxx_destruct;
@end