/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:19:08 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface Bouncer_Metadata_Builder : PBGeneratedMessage_Builder {
	Bouncer_Metadata* result; 
}
@property (retain) Bouncer_Metadata* result; 
-(id)buildPartial;
-(id)mergeFromCodedInputStream:(id)arg1;
-(id)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
-(id)mergeFrom:(id)arg1;
-(id)internalGetResult;
-(id)clone;
-(id)setReactions:(id)arg1;
-(BOOL)hasReactions;
-(id)reactions;
-(id)mergeReactions:(id)arg1;
-(id)clearSummary;
-(id)setReactionsBuilder:(id)arg1;
-(id)clearReactions;
-(id)setReshareId:(id)arg1;
-(BOOL)hasReshareId;
-(id)reshareId;
-(id)clearReshareId;
-(id)defaultInstance;
-(void)dealloc;
-(id)init;
-(id)clear;
-(void)setResult:(id)arg1;
-(id)build;
-(BOOL)hasSummary;
-(id)summary;
-(id)setSummary:(id)arg1;
@end