/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:23:42 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol SPForegroundObserverDelegate
@required
-(void)foregroundObserverDidAwake(id):arg1 ;
-(void)foregroundObserverDidHibernate(id):arg1 ;
-(void)foregroundObserverDidAwake(id):arg1 ;
-(void)foregroundObserverDidHibernate(id):arg1 ;
@end

@protocol BrowseNewReleasesShuffledModelDelegate
@optional
-(void)newReleasesShuffledModel(id):arg1 didLoadWithError(id):arg2 ;
@end
