/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:22:41 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface BrowsePlayButton : UIButton {
	BOOL _playbackQueued; 
	int _state; 
	id<BrowsePlayButtonDelegate> _delegate; 
	int _buttonSize; 
	int _index; 
	UIActivityIndicatorView* _activityIndicator; 
}
@property (assign,nonatomic,__weak) id<BrowsePlayButtonDelegate> delegate; 				//@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) int state; 				//@synthesize state=_state - In the implementation block
@property (assign,nonatomic) int buttonSize; 				//@synthesize buttonSize=_buttonSize - In the implementation block
@property (assign,nonatomic) int index; 				//@synthesize index=_index - In the implementation block
@property (assign,nonatomic) BOOL playbackQueued; 				//@synthesize playbackQueued=_playbackQueued - In the implementation block
@property (nonatomic,retain) UIActivityIndicatorView* activityIndicator; 				//@synthesize activityIndicator=_activityIndicator - In the implementation block
-(void)tapped;
-(void)setImagesForSizeAndState;
-(void)setPlaybackQueued:(BOOL)arg1;
-(void)setDelegate:(id)arg1;
-(void)setState:(int)arg1;
-(id)initWithSize:(int)arg1;
-(void)setIndex:(int)arg1;
-(void)setActivityIndicator:(id)arg1;
-(void)setButtonSize:(int)arg1;
-(void).cxx_destruct;
@end