/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:23:10 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface BrowseHeaderLabel : UIView {
	UILabel* _header; 
	UIView* _demarcation; 
}
@property (nonatomic,retain) UILabel* header; 				//@synthesize header=_header - In the implementation block
@property (nonatomic,retain) UIView* demarcation; 				//@synthesize demarcation=_demarcation - In the implementation block
-(void)setDemarcation:(id)arg1;
-(id)initWithFrame:(CGRect)arg1;
-(void)setText:(id)arg1;
-(void)setHeader:(id)arg1;
-(void).cxx_destruct;
@end