/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:23:18 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface BrowsePlaylistItem : NSObject {
	NSURL* _link; 
	NSString* _imageId; 
	NSString* _title; 
}
@property (nonatomic,retain) NSURL* link; 				//@synthesize link=_link - In the implementation block
@property (nonatomic,retain) NSString* imageId; 				//@synthesize imageId=_imageId - In the implementation block
@property (nonatomic,retain) NSString* title; 				//@synthesize title=_title - In the implementation block
+(id)dataFromItemDictionary:(id)arg1;
-(void)setImageId:(id)arg1;
-(void)setTitle:(id)arg1;
-(void)setLink:(id)arg1;
-(void).cxx_destruct;
@end