/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:25:43 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface DDXMLElement : DDXMLNode {
}
+(id)elementWithName:(id)arg1 xmlns:(id)arg2;
+(id)nodeWithElementPrimitive:(struct _xmlNode*)arg1 owner:(id)arg2;
+(id)nodeWithPrimitive:(struct _xmlKind*)arg1 owner:(id)arg2;
-(void)sp_sinkArrays;
-(void)setXmlns:(id)arg1;
-(id)elementsForName:(id)arg1;
-(id)elementsForLocalName:(id)arg1 URI:(id)arg2;
-(id)namespaceForPrefix:(id)arg1;
-(void)addNamespace:(id)arg1;
-(id)elementForName:(id)arg1;
-(id)elementForName:(id)arg1 xmlns:(id)arg2;
-(id)xmlns;
-(id)prettyXMLString;
-(id)compactXMLString;
-(void)addAttributeWithName:(id)arg1 stringValue:(id)arg2;
-(id)attributesAsDictionary;
-(id)initWithPrimitive:(struct _xmlKind*)arg1 owner:(id)arg2;
-(id)initWithElementPrimitive:(struct _xmlNode*)arg1 owner:(id)arg2;
-(id)_elementsForName:(id)arg1 localName:(id)arg2 prefix:(id)arg3 uri:(id)arg4;
-(id)_recursiveResolvePrefixForURI:(id)arg1 atNode:(struct _xmlNode*)arg2;
-(void)_removeAttributeForName:(id)arg1;
-(void)_removeNamespaceForPrefix:(id)arg1;
-(void)_addNamespace:(id)arg1;
-(id)_recursiveResolveNamespaceForPrefix:(id)arg1 atNode:(struct _xmlNode*)arg2;
-(id)initWithName:(id)arg1 URI:(id)arg2;
-(id)initWithXMLString:(id)arg1 error:(id*)arg2;
-(BOOL)_hasAttributeWithName:(id)arg1;
-(void)removeAttributeForName:(id)arg1;
-(void)removeNamespaceForPrefix:(id)arg1;
-(id)namespaces;
-(void)setNamespaces:(id)arg1;
-(id)resolveNamespaceForName:(id)arg1;
-(id)resolvePrefixForNamespaceURI:(id)arg1;
-(void)removeChildAtIndex:(unsigned)arg1;
-(id)attributes;
-(void)setAttributes:(id)arg1;
-(id)initWithName:(id)arg1;
-(void)setChildren:(id)arg1;
-(void)addChild:(id)arg1;
-(void)addAttribute:(id)arg1;
-(id)attributeForName:(id)arg1;
-(id)initWithName:(id)arg1 stringValue:(id)arg2;
-(void)insertChild:(id)arg1 atIndex:(unsigned)arg2;
@end