/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:25:48 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol FBCacheIndexFileDelegate
@required
-(void)cacheIndex(id):arg1 writeFileWithName(id):arg2 data(id):arg3 ;
-(void)cacheIndex(id):arg1 deleteFileWithName(id):arg2 ;
-(void)cacheIndex(id):arg1 writeFileWithName(id):arg2 data(id):arg3 ;
-(void)cacheIndex(id):arg1 deleteFileWithName(id):arg2 ;
@end
