/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:18:09 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface FMTBTState : FMEnum {
}
+(id)valueOf:(id)arg1;
+(id)ROUTE_UPDATE_REQUEST;
+(id)ROUTE_ACCEPTED;
+(id)ROUTE_REFUSED;
+(id)ROUTE_CANCELLED;
+(id)values;
@end