/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:18:13 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface FMTTSChunk : FMRPCStruct {
}
@property (assign) NSString* text; 
@property (assign) FMSpeechCapabilities* type; 
-(id)init;
-(id)initWithDictionary:(id)arg1;
-(void)setType:(id)arg1;
-(void)setText:(id)arg1;
@end