/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:17:44 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <SyncCommunicationControllerDelegate.h>
#import <AlertControllerDelegate.h>

@interface FordSyncSessionController : NSObject <SyncCommunicationControllerDelegate, AlertControllerDelegate> {
	BOOL _seeking; 
	BOOL _wasPlayingWhenWentInaudible; 
	BOOL _wasPlayingWhenWentBackground; 
	BOOL _hasShownLoggedOutWarning; 
	SyncCommunicationController* _syncCommunication; 
	PlayController* _playController; 
	UIWindow* _distractionFreeWindow; 
	NSMutableArray* _pendingLinkRequests; 
	NSTimer* _temporaryTextTimer; 
	NSTimer* _trackTimerSyncTimer; 
	FordSyncCommandHandler* _commandHandler; 
	FordSyncPlaybackHelper* _playbackHelper; 
	struct {
		BOOL paused;
		BOOL seekEnabled;
		double lastForceUpdate;
	} _lastPlayState; 
}
@property (nonatomic,copy) BOOL loggedIn; 
@property (nonatomic,retain) SyncCommunicationController* syncCommunication; 				//@synthesize syncCommunication=_syncCommunication - In the implementation block
@property (nonatomic,retain) PlayController* playController; 				//@synthesize playController=_playController - In the implementation block
@property (nonatomic,retain) UIWindow* distractionFreeWindow; 				//@synthesize distractionFreeWindow=_distractionFreeWindow - In the implementation block
@property (nonatomic,retain) NSMutableArray* pendingLinkRequests; 				//@synthesize pendingLinkRequests=_pendingLinkRequests - In the implementation block
@property (nonatomic,retain) NSTimer* temporaryTextTimer; 				//@synthesize temporaryTextTimer=_temporaryTextTimer - In the implementation block
@property (nonatomic,retain) NSTimer* trackTimerSyncTimer; 				//@synthesize trackTimerSyncTimer=_trackTimerSyncTimer - In the implementation block
@property (assign,nonatomic) BOOL seeking; 				//@synthesize seeking=_seeking - In the implementation block
@property (assign,nonatomic) BOOL wasPlayingWhenWentInaudible; 				//@synthesize wasPlayingWhenWentInaudible=_wasPlayingWhenWentInaudible - In the implementation block
@property (assign,nonatomic) BOOL wasPlayingWhenWentBackground; 				//@synthesize wasPlayingWhenWentBackground=_wasPlayingWhenWentBackground - In the implementation block
@property (assign,nonatomic) struct lastPlayState; 				//@synthesize lastPlayState=_lastPlayState - In the implementation block
@property (assign,nonatomic) BOOL hasShownLoggedOutWarning; 				//@synthesize hasShownLoggedOutWarning=_hasShownLoggedOutWarning - In the implementation block
@property (nonatomic,retain) FordSyncCommandHandler* commandHandler; 				//@synthesize commandHandler=_commandHandler - In the implementation block
@property (nonatomic,retain) FordSyncPlaybackHelper* playbackHelper; 				//@synthesize playbackHelper=_playbackHelper - In the implementation block
+(void)handleError:(id)arg1 inMethod:(SEL)arg2 extra:(id)arg3;
+(id)keyPathsForValuesAffectingLoggedIn;
+(id)sharedInstance;
+(void)applicationDidFinishLaunching:(id)arg1;
+(void)load;
-(BOOL)alertControllerShouldDisplayAlert:(id)arg1;
-(void)setPlayController:(id)arg1;
-(void)deviceBatteryStateDidChangeNotification:(id)arg1;
-(void)loginWithLegacyFeature:(id)arg1 playbackFeature:(id)arg2 radioManager:(id)arg3;
-(void)syncWasDisconnected:(id)arg1;
-(void)sync:(id)arg1 didEncounterError:(id)arg2;
-(void)syncDidBecomeForeground:(id)arg1;
-(void)syncDidBecomeBackground:(id)arg1;
-(void)syncDidBecomeLimited:(id)arg1;
-(void)syncDidBecomeIdle:(id)arg1;
-(void)sync:(id)arg1 buttonUp:(int)arg2;
-(void)sync:(id)arg1 longPressedButton:(int)arg2;
-(void)sync:(id)arg1 pressedButton:(int)arg2;
-(void)sync:(id)arg1 didTriggerCommandWithId:(id)arg2 triggeredByVoice:(BOOL)arg3;
-(void)syncWasConnected:(id)arg1;
-(void)displayTemporaryText:(id)arg1 line2:(id)arg2 forDuration:(double)arg3;
-(void)cancelTemporaryText;
-(void)setPlaybackHelper:(id)arg1;
-(void)setSyncCommunication:(id)arg1;
-(void)setCommandHandler:(id)arg1;
-(void)setPendingLinkRequests:(id)arg1;
-(void)transportDisconnected:(id)arg1;
-(void)presentDistractionFreeUI;
-(void)setTemporaryTextTimer:(id)arg1;
-(void)setTrackTimerSyncTimer:(id)arg1;
-(void)updateNowPlayingMetadata;
-(void)handlePlayContextChanged;
-(void)stopTrackTimerSyncTimer;
-(void)startTrackTimerSyncTimer;
-(void)updateNowPlayingTimer;
-(void)setWasPlayingWhenWentInaudible:(BOOL)arg1;
-(void)setHasShownLoggedOutWarning:(BOOL)arg1;
-(void)dismissDistractionFreeUI;
-(void)setWasPlayingWhenWentBackground:(BOOL)arg1;
-(void)setDistractionFreeWindow:(id)arg1;
-(void)storeRecentContextWithName:(id)arg1 url:(id)arg2;
-(void)temporaryTextTimerFired:(id)arg1;
-(void)updateNowPlayingTimerFired:(id)arg1;
-(void)setLastPlayState:(struct )arg1;
-(void)dispatchRemoteControlEventToApplication:(int)arg1;
-(id)userDefaultsKeyForButton:(int)arg1;
-(void)setSeeking:(BOOL)arg1;
-(void)dealloc;
-(id)init;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
-(void)logout;
-(void).cxx_destruct;
@end