/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:26:15 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <SPTGaiaDeviceStateManagerObserver.h>
#import <PlayerAudioSessionDelegate.h>

@interface GaiaLocalAudioSessionController : NSObject <SPTGaiaDeviceStateManagerObserver, PlayerAudioSessionDelegate> {
	BOOL _audioSessionActive; 
	BOOL _remoteDisabled; 
	PlayController* _playController; 
	SPTGaiaDeviceManager* _deviceManager; 
}
@property (assign,getter=isAudioSessionActive,nonatomic) BOOL audioSessionActive; 				//@synthesize audioSessionActive=_audioSessionActive - In the implementation block
@property (assign,nonatomic,__weak) PlayController* playController; 				//@synthesize playController=_playController - In the implementation block
@property (assign,nonatomic,__weak) SPTGaiaDeviceManager* deviceManager; 				//@synthesize deviceManager=_deviceManager - In the implementation block
@property (assign,nonatomic) BOOL remoteDisabled; 				//@synthesize remoteDisabled=_remoteDisabled - In the implementation block
-(BOOL)playerShouldModifyAudioSession:(id)arg1;
-(void)setPlayController:(id)arg1;
-(void)deviceStateManager:(id)arg1 activeDeviceDidChange:(id)arg2;
-(void)setRemoteDisabled:(BOOL)arg1;
-(void)teardownSessionListeners;
-(void)updateCurrentDevice;
-(void)setupSessionListeners;
-(void)setAudioSessionActive:(BOOL)arg1;
-(void)audioSessionRouteChanged:(id)arg1;
-(id)initWithPlayController:(id)arg1 deviceManager:(id)arg2;
-(void)dealloc;
-(void)setDeviceManager:(id)arg1;
-(void).cxx_destruct;
@end