/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:18:48 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface HorizontalAlbumCell : UIButton {
	SPAsyncImageView* _cachedImage; 
	UILabel* _label1; 
	UILabel* _label2; 
	UILabel* _label3; 
	SPAlbum* _album; 
	SPTrack* _track; 
	unsigned _trackIndex; 
}
@property (nonatomic,copy) SPAsyncImageView* cachedImage; 				//@synthesize cachedImage=_cachedImage - In the implementation block
@property (nonatomic,copy) UILabel* label1; 				//@synthesize label1=_label1 - In the implementation block
@property (nonatomic,copy) UILabel* label2; 				//@synthesize label2=_label2 - In the implementation block
@property (nonatomic,copy) UILabel* label3; 				//@synthesize label3=_label3 - In the implementation block
@property (nonatomic,retain) SPAlbum* album; 				//@synthesize album=_album - In the implementation block
@property (nonatomic,retain) SPTrack* track; 				//@synthesize track=_track - In the implementation block
@property (assign,nonatomic) unsigned trackIndex; 				//@synthesize trackIndex=_trackIndex - In the implementation block
-(id)initWithFrame:(CGRect)arg1 labelCount:(int)arg2;
-(void)setTrackIndex:(unsigned)arg1;
-(void)setAlbum:(id)arg1;
-(void)setTrack:(id)arg1;
-(void).cxx_destruct;
@end