/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:25:47 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface InboxVCIPadPersonCell : SPTableViewCell {
	SPAsyncImageView* _itemImage; 
	UIImageView* _unreadView; 
	UIImageView* _frameView; 
}
@property (nonatomic,retain) SPAsyncImageView* itemImage; 				//@synthesize itemImage=_itemImage - In the implementation block
@property (nonatomic,retain) UIImageView* unreadView; 				//@synthesize unreadView=_unreadView - In the implementation block
@property (assign,nonatomic) BOOL unread; 
@property (nonatomic,retain) UIImageView* frameView; 				//@synthesize frameView=_frameView - In the implementation block
+(float)cellHeight;
-(void)setFrameView:(id)arg1;
-(void)setUnreadView:(id)arg1;
-(void)setUnread:(BOOL)arg1 animated:(BOOL)arg2;
-(void)layoutSubviews;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
-(void)setHighlighted:(BOOL)arg1 animated:(BOOL)arg2;
-(void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;
-(void)prepareForReuse;
-(void)setItemImage:(id)arg1;
-(void)setUnread:(BOOL)arg1;
-(void).cxx_destruct;
@end