/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:18:33 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface InviteAdView : UIControl {
	NSArray* _labels; 
	CALayer* _highlightLayer; 
	id target; 
	SEL selector; 
}
@property (assign,nonatomic) id target; 
@property (assign,nonatomic) SEL selector; 
-(void)setTextRows:(id)arg1;
-(id)initWithFrame:(CGRect)arg1;
-(void)dealloc;
-(void)layoutSubviews;
-(void)setTarget:(id)arg1;
-(void)setSelector:(SEL)arg1;
-(void)setHighlighted:(BOOL)arg1;
-(void)close;
@end