/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:21:19 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface KKGridViewUpdateStack : NSObject {
	struct __CFDictionary* _availableUpdates; 
	NSMutableArray* _itemsToUpdate; 
}
@property (nonatomic,copy) NSMutableArray* itemsToUpdate; 				//@synthesize itemsToUpdate=_itemsToUpdate - In the implementation block
-(BOOL)hasUpdateForIndexPath:(id)arg1;
-(id)updateForIndexPath:(id)arg1;
-(void)removeUpdateForIndexPath:(id)arg1;
-(BOOL)addUpdate:(id)arg1;
-(BOOL)addUpdate:(id)arg1 sortingAfterAdd:(BOOL)arg2;
-(void)_sortItems;
-(void)removeUpdate:(id)arg1;
-(void)addUpdates:(id)arg1;
-(id)nextUpdateFromIndexPath:(id)arg1 fallbackPath:(id)arg2;
-(id)init;
-(void).cxx_destruct;
@end