/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:25:16 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol LoginPLIControllerDelegate
@required
-(void)loginPLIController(id):arg1 failedWithUpdateWithError(id):arg2 ;
-(void)loginPLIControllerDidUpdate(id):arg1 ;
-(void)loginPLIController(id):arg1 failedWithUpdateWithError(id):arg2 ;
-(void)loginPLIControllerDidUpdate(id):arg1 ;
@end
