/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:21:36 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface LogLine : NSObject {
	NSString* _line; 
	UIColor* _color; 
}
@property (nonatomic,retain) NSString* line; 				//@synthesize line=_line - In the implementation block
@property (nonatomic,retain) UIColor* color; 				//@synthesize color=_color - In the implementation block
-(void)setColor:(id)arg1;
-(void)setLine:(id)arg1;
-(void).cxx_destruct;
@end