/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:24:46 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface MockLaserTag : LaserTag {
	NSString* _ppid; 
}
@property (nonatomic,retain) NSString* ppid; 				//@synthesize ppid=_ppid - In the implementation block
-(id)getAds;
-(id)generatePPID:(id)arg1;
-(void)setPpid:(id)arg1;
-(id)initWithUser:(id)arg1;
-(void).cxx_destruct;
@end