/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:22:17 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol NewPlaylistCellDelegate
@required
-(void)newPlaylistCell(id):arg1 createPlaylistNamed(id):arg2 ;
-(void)newPlaylistCellCancelled(id):arg1 ;
-(void)newPlaylistCell(id):arg1 selected(BOOL):arg2 animated(BOOL):arg3 ;
-(void)newPlaylistCell(id):arg1 createPlaylistNamed(id):arg2 ;
-(void)newPlaylistCellCancelled(id):arg1 ;
-(void)newPlaylistCell(id):arg1 selected(BOOL):arg2 animated(BOOL):arg3 ;
@end
