/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:24:08 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <SPTHTTPImageLoaderDelegate.h>
#import <PlayerTrackScrollPageView.h>
#import <SPTThemableView.h>

@interface NowPlayingTrackPageView : SPPageView <SPTHTTPImageLoaderDelegate, PlayerTrackScrollPageView, SPTThemableView> {
	BOOL _coverArtHidden; 
	id<SPTThemableViewLayoutDelegate> _layoutDelegate; 
	UIImageView* _imageView; 
	NSURL* _trackURL; 
	NSString* _trackTitle; 
	NSString* _artistTitle; 
	NSURL* _imageURL; 
	SPTHTTPImageLoader* _imageLoader; 
	UILabel* _artistLabel; 
	UILabel* _titleLabel; 
	SPKVObservation* _trackLoadedObserver; 
}
@property (assign,getter=isCoverArtHidden,nonatomic) BOOL coverArtHidden; 				//@synthesize coverArtHidden=_coverArtHidden - In the implementation block
@property (nonatomic,copy) CGRect coverArtAreaBounds; 
@property (nonatomic,retain) UIImageView* imageView; 				//@synthesize imageView=_imageView - In the implementation block
@property (nonatomic,retain) NSURL* trackURL; 				//@synthesize trackURL=_trackURL - In the implementation block
@property (nonatomic,copy) NSString* trackTitle; 				//@synthesize trackTitle=_trackTitle - In the implementation block
@property (nonatomic,copy) NSString* artistTitle; 				//@synthesize artistTitle=_artistTitle - In the implementation block
@property (nonatomic,retain) NSURL* imageURL; 				//@synthesize imageURL=_imageURL - In the implementation block
@property (nonatomic,retain) SPTHTTPImageLoader* imageLoader; 				//@synthesize imageLoader=_imageLoader - In the implementation block
@property (nonatomic,retain) UILabel* artistLabel; 				//@synthesize artistLabel=_artistLabel - In the implementation block
@property (nonatomic,retain) UILabel* titleLabel; 				//@synthesize titleLabel=_titleLabel - In the implementation block
@property (nonatomic,retain) SPKVObservation* trackLoadedObserver; 				//@synthesize trackLoadedObserver=_trackLoadedObserver - In the implementation block
@property (assign,nonatomic,__weak) id<SPTThemableViewLayoutDelegate> layoutDelegate; 				//@synthesize layoutDelegate=_layoutDelegate - In the implementation block
-(void)applyThemeLayout;
-(void)setLayoutDelegate:(id)arg1;
-(void)imageLoader:(id)arg1 didFinishLoadingImage:(id)arg2 forURL:(id)arg3 context:(id)arg4 loadedSynchronously:(BOOL)arg5;
-(void)setImageLoader:(id)arg1;
-(void)setTrackURL:(id)arg1;
-(void)setCoverArtHidden:(BOOL)arg1;
-(void)setTrackLoadedObserver:(id)arg1;
-(void)setTrackTitle:(id)arg1;
-(void)setArtistTitle:(id)arg1;
-(void)setArtistLabel:(id)arg1;
-(void)dealloc;
-(void)layoutSubviews;
-(id)initWithFrame:(CGRect)arg1 reuseIdentifier:(id)arg2;
-(void)setImageView:(id)arg1;
-(void)setTitleLabel:(id)arg1;
-(void)setImageURL:(id)arg1;
-(void).cxx_destruct;
@end