/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:23:23 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <NowPlayingBarInformationViewDelegate.h>

@interface NowPlayingBarInformationViewController : UIViewController <NowPlayingBarInformationViewDelegate> {
	NSString* _informationTitle; 
	SPTrack* _previewTrack; 
	NSTimer* _previewPositionTimer; 
	PlayController* _playController; 
	id<ShuffleControllerObjC> _shuffleController; 
}
@property (nonatomic,retain) NSString* informationTitle; 				//@synthesize informationTitle=_informationTitle - In the implementation block
@property (nonatomic,retain) SPTrack* previewTrack; 				//@synthesize previewTrack=_previewTrack - In the implementation block
@property (assign,nonatomic,__weak) NSTimer* previewPositionTimer; 				//@synthesize previewPositionTimer=_previewPositionTimer - In the implementation block
@property (assign,nonatomic,__weak) PlayController* playController; 				//@synthesize playController=_playController - In the implementation block
@property (assign,nonatomic,__weak) id<ShuffleControllerObjC> shuffleController; 				//@synthesize shuffleController=_shuffleController - In the implementation block
-(void)setPlayController:(id)arg1;
-(void)setShuffleController:(id)arg1;
-(id)initWithPlayController:(id)arg1 shuffleController:(id)arg2;
-(void)updatePreviewPosition:(id)arg1;
-(void)setPreviewPositionTimer:(id)arg1;
-(BOOL)nowPlayingBarInformationViewShouldClose:(id)arg1;
-(id)initWithPreviewTrack:(id)arg1 playController:(id)arg2 shuffleController:(id)arg3;
-(id)initWithInformationTitle:(id)arg1 playController:(id)arg2 shuffleController:(id)arg3;
-(void)setInformationTitle:(id)arg1;
-(void)setPreviewTrack:(id)arg1;
-(void)loadView;
-(void).cxx_destruct;
@end