/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:22:45 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface NowPlayingBarInformationView : UIView {
	id<NowPlayingBarInformationViewDelegate> _delegate; 
	UIButton* _closeBtn; 
	UILabel* _headingLabel; 
	UILabel* _messageLabel; 
	UIButton* _upsellBtn; 
}
@property (assign,nonatomic,__weak) id<NowPlayingBarInformationViewDelegate> delegate; 				//@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) BOOL showCloseButton; 
@property (nonatomic,retain) NSString* heading; 
@property (nonatomic,retain) NSString* message; 
@property (nonatomic,retain) UIButton* closeBtn; 				//@synthesize closeBtn=_closeBtn - In the implementation block
@property (nonatomic,retain) UILabel* headingLabel; 				//@synthesize headingLabel=_headingLabel - In the implementation block
@property (nonatomic,retain) UILabel* messageLabel; 				//@synthesize messageLabel=_messageLabel - In the implementation block
@property (nonatomic,retain) UIButton* upsellBtn; 				//@synthesize upsellBtn=_upsellBtn - In the implementation block
-(void)setShowCloseButton:(BOOL)arg1;
-(void)setUpsellBtn:(id)arg1;
-(void)upsellTouchedUpInside:(id)arg1;
-(void)setCloseBtn:(id)arg1;
-(void)closeTouchedUpInside:(id)arg1;
-(void)setHeadingLabel:(id)arg1;
-(void)resetLabelFrames;
-(void)setHeading:(id)arg1 message:(id)arg2 animated:(BOOL)arg3;
-(void)setMessageLabel:(id)arg1;
-(void)setDelegate:(id)arg1;
-(id)init;
-(void)removeFromSuperview;
-(void)setMessage:(id)arg1;
-(void)setHeading:(id)arg1;
-(void).cxx_destruct;
@end