/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:22:39 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PTSAddGroupSettingsRowAction : PTSRowAction {
	Class _settingsClass; 
	NSString* _groupKeyPath; 
}
@property (nonatomic,retain) Class settingsClass; 				//@synthesize settingsClass=_settingsClass - In the implementation block
@property (nonatomic,copy) NSString* groupKeyPath; 				//@synthesize groupKeyPath=_groupKeyPath - In the implementation block
+(id)actionWithGroupKeyPath:(id)arg1 settingsClass:(Class)arg2;
-(id)init;
-(id)copyWithZone:(NSZone*)arg1;
-(void)setGroupKeyPath:(id)arg1;
-(void)resolveTemplatesWithIndex:(unsigned)arg1;
-(void)setSettingsClass:(Class)arg1;
-(void).cxx_destruct;
@end