/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:20:58 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UITextFieldDelegate.h>

@interface PTSEditRowTableViewCell : PTSRowTableViewCell <UITextFieldDelegate> {
}
+(int)cellStyleForRow:(id)arg1;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
-(void)textFieldDidEndEditing:(id)arg1;
-(void)updateDisplayedValue;
-(id)textForValue:(id)arg1;
-(id)valueForText:(id)arg1;
@end