/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:21:13 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <_UISettingsKeyObserver.h>

@interface PTSImageSettings : _UISettings <_UISettingsKeyObserver> {
	BOOL _unarchiving; 
	UIImage* _image; 
	NSData* _pngData; 
	int _imageOrientation; 
	float _imageScale; 
}
@property (retain) UIImage* image; 				//@synthesize image=_image - In the implementation block
@property (retain) NSData* pngData; 				//@synthesize pngData=_pngData - In the implementation block
@property (assign) int imageOrientation; 				//@synthesize imageOrientation=_imageOrientation - In the implementation block
@property (assign) float imageScale; 				//@synthesize imageScale=_imageScale - In the implementation block
-(void)dealloc;
-(void)setImage:(id)arg1;
-(id)init;
-(void)applyArchiveValue:(id)arg1 forKey:(id)arg2;
-(id)archiveValueForKey:(id)arg1;
-(void)settings:(id)arg1 changedValueForKey:(id)arg2;
-(void)_updateImageData;
-(void)setImageScale:(float)arg1;
-(void)setImageOrientation:(int)arg1;
-(void)_updateImageProperties;
-(void)setPngData:(id)arg1;
-(void).cxx_destruct;
@end