/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:21:19 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PTSImagePreviewRowTableViewCell : PTSRowTableViewCell {
	UIImageView* _imageViewOnLight; 
	UIImageView* _imageViewOnDark; 
	UIView* _lightBackground; 
	UIView* _darkBackground; 
}
+(float)cellHeightForRow:(id)arg1;
+(void)_getCellHeight:(float*)arg1 leftFrame:(CGRect*)arg2 rightFrame:(CGRect*)arg3 forImage:(id)arg4 inBounds:(CGRect)arg5;
-(void)layoutSubviews;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
-(void)updateDisplayedValue;
-(void).cxx_destruct;
@end