/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:22:22 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol PTSModuleObserver
@required
-(void)module(id):arg1 didInsertRows(id):arg2 deleteRows(id):arg3 ;
-(void)moduleDidReload(id):arg1 ;
-(void)module(id):arg1 didInsertSections(id):arg2 deleteSections(id):arg3 ;
-(void)module(id):arg1 didInsertRows(id):arg2 deleteRows(id):arg3 ;
-(void)moduleDidReload(id):arg1 ;
-(void)module(id):arg1 didInsertSections(id):arg2 deleteSections(id):arg3 ;
@end
