/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:22:19 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PTSPushViewControllerRowAction : PTSRowAction {
	id _viewControllerCreator; 
}
@property (nonatomic,copy) id viewControllerCreator; 				//@synthesize viewControllerCreator=_viewControllerCreator - In the implementation block
+(id)actionWithViewControllerCreator:(id)arg1;
-(id)init;
-(id)copyWithZone:(NSZone*)arg1;
-(void)setViewControllerCreator:(id)arg1;
-(void).cxx_destruct;
@end