/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:22:36 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface PTSPushImagePickerRowAction : PTSPushViewControllerRowAction {
	NSString* _imageDirectoryPath; 
}
@property (nonatomic,copy) NSString* imageDirectoryPath; 				//@synthesize imageDirectoryPath=_imageDirectoryPath - In the implementation block
+(id)actionWithImageDirectoryPath:(id)arg1;
-(id)init;
-(id)copyWithZone:(NSZone*)arg1;
-(void)setImageDirectoryPath:(id)arg1;
-(void).cxx_destruct;
@end