/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:21:50 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <_UISettingsKeyPathObserver.h>
#import <_UISettingsGroupObserver.h>

@interface PTSSection : NSObject <_UISettingsKeyPathObserver, _UISettingsGroupObserver> {
	NSArray* _rows; 
	NSHashTable* _observers; 
	NSMutableArray* _allConcreteRows; 
	NSMutableArray* _enabledConcreteRows; 
	NSMutableDictionary* _concreteRowsByTemplateIndex; 
	NSMutableDictionary* _groupsByTemplateIndex; 
	NSString* _title; 
	_UISettings* _settings; 
	NSString* _submoduleKeyPath; 
	NSArray* _appearanceConditions; 
}
@property (nonatomic,retain) NSString* title; 				//@synthesize title=_title - In the implementation block
@property (nonatomic,retain) _UISettings* settings; 				//@synthesize settings=_settings - In the implementation block
@property (nonatomic,retain) NSString* submoduleKeyPath; 				//@synthesize submoduleKeyPath=_submoduleKeyPath - In the implementation block
@property (nonatomic,retain) NSArray* appearanceConditions; 				//@synthesize appearanceConditions=_appearanceConditions - In the implementation block
-(void)dealloc;
-(void)setTitle:(id)arg1;
-(void)removeObserver:(id)arg1;
-(unsigned)numberOfRows;
-(void)settings:(id)arg1 changedValueForKeyPath:(id)arg2;
-(void)settingsGroup:(id)arg1 didInsertSettings:(id)arg2 atIndex:(unsigned)arg3;
-(void)settingsGroup:(id)arg1 didRemoveSettings:(id)arg2 atIndex:(unsigned)arg3;
-(void)settingsGroup:(id)arg1 didMoveSettings:(id)arg2 fromIndex:(unsigned)arg3 toIndex:(unsigned)arg4;
-(void)setSettings:(id)arg1;
-(void)addObserver:(id)arg1;
-(id)rowAtIndex:(unsigned)arg1;
-(void)_assertNoGroupTemplateProperties:(id)arg1;
-(void)_reloadEnabledRows;
-(void)_fixRows:(id)arg1 fromIndex:(unsigned)arg2 withTemplate:(id)arg3;
-(void)_updateEnabledRows;
-(void)_sendInserts:(id)arg1 deletes:(id)arg2;
-(BOOL)_shouldEnableRow:(id)arg1;
-(void)_sendReload;
-(id)initWithRows:(id)arg1;
-(unsigned)indexOfRow:(id)arg1;
-(void)enumerateAllRowsUsingBlock:(id)arg1;
-(void)enumerateEnabledRowsUsingBlock:(id)arg1;
-(BOOL)hasEnabledEditableRows;
-(unsigned)destinationForRowAtIndex:(unsigned)arg1 withProposedDestination:(unsigned)arg2;
-(void)moveRowAtIndex:(unsigned)arg1 toIndex:(unsigned)arg2;
-(void)setSubmoduleKeyPath:(id)arg1;
-(void)setAppearanceConditions:(id)arg1;
-(void).cxx_destruct;
@end