/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:23:33 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <PTSHUDControl.h>
#import <_UISettingsKeyPathObserver.h>

@interface PTSSlider : UIView <PTSHUDControl, _UISettingsKeyPathObserver> {
	BOOL _enabled; 
	BOOL _showsValueLabel; 
	_UISettings* _settings; 
	NSString* _valueKeyPath; 
	int _alignment; 
	UISlider* _sliderControl; 
	UILabel* _titleLabel; 
	NSNumberFormatter* _valueLabelFormatter; 
	NSArray* _valueLabelStrings; 
	float _increment; 
	UILabel* _valueLabel; 
	UIButton* _upIncrementButton; 
	UIButton* _downIncrementButton; 
	NSArray* _subviewConstraints; 
	NSTimer* _buttonRepeatTimer; 
	struct {
		double mark;
		double limit;
	} _valueChangePublishTTL; 
}
@property (assign,nonatomic,__weak) _UISettings* settings; 				//@synthesize settings=_settings - In the implementation block
@property (nonatomic,copy) NSString* valueKeyPath; 				//@synthesize valueKeyPath=_valueKeyPath - In the implementation block
@property (assign,nonatomic) int alignment; 				//@synthesize alignment=_alignment - In the implementation block
@property (assign,nonatomic) BOOL enabled; 				//@synthesize enabled=_enabled - In the implementation block
@property (nonatomic,retain) UISlider* sliderControl; 				//@synthesize sliderControl=_sliderControl - In the implementation block
@property (nonatomic,retain) UILabel* titleLabel; 				//@synthesize titleLabel=_titleLabel - In the implementation block
@property (assign,nonatomic) BOOL showsValueLabel; 				//@synthesize showsValueLabel=_showsValueLabel - In the implementation block
@property (nonatomic,retain) NSNumberFormatter* valueLabelFormatter; 				//@synthesize valueLabelFormatter=_valueLabelFormatter - In the implementation block
@property (nonatomic,copy) NSArray* valueLabelStrings; 				//@synthesize valueLabelStrings=_valueLabelStrings - In the implementation block
@property (assign,nonatomic,@dynamic) float value; 
@property (assign,nonatomic,@dynamic) float minimumValue; 
@property (assign,nonatomic,@dynamic) float maximumValue; 
@property (assign,nonatomic) float increment; 				//@synthesize increment=_increment - In the implementation block
@property (nonatomic,retain) UILabel* valueLabel; 				//@synthesize valueLabel=_valueLabel - In the implementation block
@property (nonatomic,retain) UIButton* upIncrementButton; 				//@synthesize upIncrementButton=_upIncrementButton - In the implementation block
@property (nonatomic,retain) UIButton* downIncrementButton; 				//@synthesize downIncrementButton=_downIncrementButton - In the implementation block
@property (nonatomic,retain) NSArray* subviewConstraints; 				//@synthesize subviewConstraints=_subviewConstraints - In the implementation block
@property (nonatomic,retain) NSTimer* buttonRepeatTimer; 				//@synthesize buttonRepeatTimer=_buttonRepeatTimer - In the implementation block
@property (assign,nonatomic) struct valueChangePublishTTL; 				//@synthesize valueChangePublishTTL=_valueChangePublishTTL - In the implementation block
+(CGRect)defaultFrame;
+(id)sliderForSettings:(id)arg1 valueKeyPath:(id)arg2 title:(id)arg3 minimumValue:(float)arg4 maximumValue:(float)arg5;
-(void)valueChanged:(id)arg1;
-(void)setValueLabel:(id)arg1;
-(id)initWithFrame:(CGRect)arg1;
-(void)dealloc;
-(void)layoutSubviews;
-(id)methodSignatureForSelector:(SEL)arg1;
-(void)setValue:(float)arg1;
-(void)setAlignment:(int)arg1;
-(void)setEnabled:(BOOL)arg1;
-(CGSize)intrinsicContentSize;
-(id)forwardingTargetForSelector:(SEL)arg1;
-(void)setValue:(float)arg1 animated:(BOOL)arg2;
-(void)settings:(id)arg1 changedValueForKeyPath:(id)arg2;
-(void)setSettings:(id)arg1;
-(void)setTitleLabel:(id)arg1;
-(void)setSettings:(id)arg1 valueKeyPath:(id)arg2;
-(id)makeTitleLabel;
-(void)setValueKeyPath:(id)arg1;
-(void)setSubviewConstraints:(id)arg1;
-(void)setValueLabelFormatter:(id)arg1;
-(id)makeSliderControl;
-(void)setSliderControl:(id)arg1;
-(id)makeValueLabel;
-(void)upIncrementAction:(id)arg1;
-(id)makeIncrementButtonWithAction:(SEL)arg1 imageName:(id)arg2;
-(void)setUpIncrementButton:(id)arg1;
-(void)downIncrementAction:(id)arg1;
-(void)setDownIncrementButton:(id)arg1;
-(void)setValueChangePublishTTL:(struct )arg1;
-(void)publishValueChanged;
-(void)updateValueLabel;
-(void)setButtonRepeatTimer:(id)arg1;
-(void)stopIncrementRepeatAction;
-(void)setShowsValueLabel:(BOOL)arg1;
-(void)setValueLabelStrings:(id)arg1;
-(void)setIncrement:(float)arg1;
-(void).cxx_destruct;
@end