/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:24:51 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface SettingsDrilldownDetailViewController : SettingsViewController {
}
-(id)initWithSettingsSections:(id)arg1;
-(id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
@end