/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:21:15 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface SPAnimation : NSObject {
	BOOL _isRunning; 
	id _completion; 
}
+(id)animation;
-(void)__runWithCompletion:(id)arg1;
-(void)animationDidFinish;
-(void)run;
-(BOOL)isRunning;
-(void).cxx_destruct;
@end