/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:24:46 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface SPApHermesRequest : NSObject {
	struct MultiStringHermesQuery* _query; 
	id _callback; 
	struct SPApHermesRequestCpp _cpp; 
	SPApHermesController* _controller; 
}
@property (assign,nonatomic) struct MultiStringHermesQuery* query; 				//@synthesize query=_query - In the implementation block
@property (nonatomic,copy) id callback; 				//@synthesize callback=_callback - In the implementation block
@property (assign,nonatomic,__weak) SPApHermesController* controller; 				//@synthesize controller=_controller - In the implementation block
@property (nonatomic,copy) struct SPApHermesRequestCpp cpp; 				//@synthesize cpp=_cpp - In the implementation block
-(id)initWithRequest:(id)arg1 usingMethod:(id)arg2 payload:(id)arg3 whenDone:(id)arg4 controller:(id)arg5;
-(void)setQuery:(struct MultiStringHermesQuery*)arg1;
-(void)setCallback:(id)arg1;
-(void)dealloc;
-(void)invalidate;
-(void)done;
-(void)start;
-(id).cxx_construct;
-(void)setController:(id)arg1;
-(void).cxx_destruct;
@end