/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:26:16 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface SPArtist : SPObject {
}
@property (nonatomic,copy) SPURL* portraitImageLink; 
@property (nonatomic,copy) NSString* name; 
@property (nonatomic,copy) NSData* ident; 
@property (nonatomic,copy) SPURL* link; 
@property (getter=isLoaded,nonatomic,copy) BOOL loaded; 
@property (nonatomic,copy) int popularity; 
@property (nonatomic,copy) BOOL isBlocked; 
+(BOOL)artistIsBlocked:(struct NSData*)arg1;
+(id)artistFromLink:(id)arg1;
+(id)artistWithArtistInfo:(struct rArtistInfo*)arg1;
+(id)artistFromId:(struct NSData*)arg1 named:(id)arg2;
+(id)artistFromId:(struct NSData*)arg1;
-(struct RefCountedInterface*)cpp;
-(id)imageLinkOfSize:(int)arg1;
-(struct rArtistInfo*)artistInfo;
-(BOOL)isAvailable;
-(unsigned)hash;
@end