/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:17:36 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface SPAwaitCoroutine : NSObject {
	id _body; 
	SPTaskCompletionSource* _source; 
	id _yieldedValue; 
	BOOL _completed; 
	id _lastAwaitedValue; 
}
@property (nonatomic,retain) id lastAwaitedValue; 				//@synthesize lastAwaitedValue=_lastAwaitedValue - In the implementation block
+(id)awaitSentinel;
-(void)resumeAt:(int)arg1;
-(void)yieldValue:(id)arg1;
-(struct dispatch_queue_s*)queueFor:(id)arg1;
-(void)setLastAwaitedValue:(id)arg1;
-(id)init;
-(void)setBody:(id)arg1;
-(id)task;
-(void)finish;
-(void).cxx_destruct;
@end