/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:24:21 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface SPPictureGroup : NSObject {
	NSArray* _pictures; 
}
@property (nonatomic,retain) NSArray* pictures; 				//@synthesize pictures=_pictures - In the implementation block
-(void)setPictures:(id)arg1;
-(id)pictureForPictureSize:(BOOL)arg1;
-(id)initWithPictureGroup:(struct PictureGroup)arg1;
-(void).cxx_destruct;
@end