/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:25:09 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface SPPlaylistInfo : SPItemInfo {
}
-(id)initWithName:(id)arg1 url:(id)arg2 creatorName:(id)arg3;
-(void)dealloc;
@end