/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:24:35 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <SPOfflineStateProtocol.h>
#import <PlaylistFolderVCTableContentItem.h>
#import <SPPlaylistContainerItem.h>

@interface SPPlaylistPlaceholder : NSObject <SPOfflineStateProtocol, PlaylistFolderVCTableContentItem, SPPlaylistContainerItem> {
	NSString* _freeformDescription; 
	NSString* _imageIdent; 
	BOOL _collaborative; 
	NSString* _name; 
}
@property (nonatomic,copy) BOOL isAvailableOffline; 
@property (assign,nonatomic) BOOL makeAvailableOffline; 
@property (nonatomic,copy) int offlineState; 
@property (nonatomic,copy) float offlineProgress; 
@property (nonatomic,copy) SPPlaylistOfflineSyncStatus* offlineSyncStatus; 
@property (nonatomic,copy) NSString* name; 				//@synthesize name=_name - In the implementation block
@property (nonatomic,copy) SPURL* link; 
@property (nonatomic,copy) NSString* ownerCanonicalUsername; 
@property (nonatomic,copy) unsigned nodeType; 
-(BOOL)isStarred;
-(id)mutableTracks;
-(id)imageIdent;
-(BOOL)isWriteable;
-(id)userThatAddedTrackAtIndex:(unsigned)arg1;
-(unsigned)countOfTracks;
-(BOOL)isInbox;
-(BOOL)isLocalFiles;
-(BOOL)isToplist;
-(BOOL)isOwnedBySelf;
-(void)setMakeAvailableOffline:(BOOL)arg1;
-(id)subscribers;
-(BOOL)collaborative;
-(void)setCollaborative:(BOOL)arg1;
-(BOOL)trackIsSeenAtIndex:(unsigned)arg1;
-(id)freeformDescription;
-(int)numberOfSubscribers;
-(id)playlistFolderCellReuseIdentifierForEditing:(BOOL)arg1;
-(Class)playlistFolderCellClassForEditing:(BOOL)arg1;
-(BOOL)hasPlayableContentWhenOnline;
-(void)updateSubscribers;
-(BOOL)isSubscribable;
-(id)objectInTracksAtIndex:(unsigned)arg1;
-(BOOL)hasPlayableContentWhenOffline;
-(void)insertObject:(id)arg1 inTracksAtIndex:(unsigned)arg2;
-(void)removeObjectFromTracksAtIndex:(unsigned)arg1;
-(id)messageForTrackAtIndex:(unsigned)arg1;
-(id)dateAddedForTrackAtIndex:(unsigned)arg1;
-(void)setFreeformDescription:(id)arg1;
-(void)setImageIdent:(id)arg1;
-(unsigned)countOfTracksCached;
-(id)objectInSubscribersAtIndex:(unsigned)arg1;
-(id)subscribersAtIndexes:(id)arg1;
-(int)countOfSubscribers;
-(void)setTrackIsSeen:(BOOL)arg1 atIndex:(unsigned)arg2;
-(void)setTrackCreationTimeWithInternalSource:(id)arg1 userThatAddedTrack:(id)arg2 forTrackAtIndex:(unsigned)arg3;
-(void)setMessage:(id)arg1 forTrackAtIndex:(unsigned)arg2;
-(int)observedChangeSource;
-(id)observedAttributeChangeKey;
-(id)attributeForKey:(id)arg1 atIndex:(unsigned)arg2;
-(void)setValue:(id)arg1 forAttribute:(id)arg2 atIndex:(unsigned)arg3;
-(id)attributeKeysAtIndex:(unsigned)arg1;
-(void)setName:(id)arg1;
-(BOOL)isLoading;
-(id)delegates;
-(void).cxx_destruct;
-(BOOL)isSeparator;
@end