/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:26:05 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol SPOfflineStateProtocol
@property (nonatomic,copy) BOOL isAvailableOffline; 
@property (assign,nonatomic) BOOL makeAvailableOffline; 
@property (nonatomic,copy) int offlineState; 
@property (nonatomic,copy) float offlineProgress; 
@property (nonatomic,copy) SPPlaylistOfflineSyncStatus* offlineSyncStatus; 
@required
-(int)offlineState;
-(id)offlineSyncStatus;
-(float)offlineProgress;
-(BOOL)isAvailableOffline;
-(BOOL)makeAvailableOffline;
-(void)setMakeAvailableOffline(BOOL):arg1 ;
-(int)offlineState;
-(id)offlineSyncStatus;
-(float)offlineProgress;
-(BOOL)isAvailableOffline;
-(BOOL)makeAvailableOffline;
-(void)setMakeAvailableOffline(BOOL):arg1 ;
@end

@protocol PlaylistFolderVCTableContentItem
@required
-(id)playlistFolderCellReuseIdentifierForEditing(BOOL):arg1 ;
-(Class)playlistFolderCellClassForEditing(BOOL):arg1 ;
-(id)playlistFolderCellReuseIdentifierForEditing(BOOL):arg1 ;
-(Class)playlistFolderCellClassForEditing(BOOL):arg1 ;
@end

@protocol SPPlaylistContainerItem
@property (nonatomic,copy) NSString* name; 
@property (nonatomic,copy) SPURL* link; 
@property (nonatomic,copy) NSString* ownerCanonicalUsername; 
@property (nonatomic,copy) unsigned nodeType; 
@required
-(id)ownerCanonicalUsername;
-(void)setName(id):arg1 ;
-(id)name;
-(unsigned)nodeType;
-(id)link;
-(id)ownerCanonicalUsername;
-(void)setName(id):arg1 ;
-(id)name;
-(unsigned)nodeType;
-(id)link;
@end
