/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:23:44 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface SPSocialLookup : NSObject {
	struct unique_ptr<SocialLookupObjC, std__1default_delete<SocialLookupObjC> > _socialLookupObjC; 
	id<SPSocialLookupDelegate> _delegate; 
	SPCore* _core; 
}
@property (assign,nonatomic,__weak) id<SPSocialLookupDelegate> delegate; 				//@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic,__weak) SPCore* core; 				//@synthesize core=_core - In the implementation block
-(id)initWithCore:(id)arg1;
-(void)setCore:(id)arg1;
-(void)setDelegate:(id)arg1;
-(void)start;
-(id).cxx_construct;
-(void).cxx_destruct;
@end