/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:23:47 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <SPTArtistTrack.h>

@interface SPTArtistTrackImpl : SPTArtistEntityImpl <SPTArtistTrack> {
	id<SPTArtistAlbum> _album; 
	unsigned _playcount; 
}
@property (nonatomic,retain) id<SPTArtistAlbum> album; 				//@synthesize album=_album - In the implementation block
@property (assign,nonatomic) unsigned playcount; 				//@synthesize playcount=_playcount - In the implementation block
@property (nonatomic,copy) NSURL* uri; 
@property (nonatomic,copy) NSString* name; 
@property (nonatomic,copy) id<SPTArtistImage> image; 
@property (nonatomic,copy) id<SPTArtistImage> headerImage; 
-(void)setPlaycount:(unsigned)arg1;
-(void)setAlbum:(id)arg1;
-(void).cxx_destruct;
@end