/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:23:44 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <SPTHTTPImageDownloadDelegate.h>

@interface SPTHTTPImageLoader : NSObject <SPTHTTPImageDownloadDelegate> {
	id<SPTHTTPImageLoaderDelegate> _delegate; 
	NSMutableArray* _downloads; 
	NSCache* _cache; 
}
@property (assign,nonatomic,__weak) id<SPTHTTPImageLoaderDelegate> delegate; 				//@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) NSMutableArray* downloads; 				//@synthesize downloads=_downloads - In the implementation block
@property (nonatomic,retain) NSCache* cache; 				//@synthesize cache=_cache - In the implementation block
-(void)cancelAllDownloads;
-(void)loadImageForURL:(id)arg1 context:(id)arg2;
-(void)loadImageForURL:(id)arg1 context:(id)arg2 asynchronousCacheRequest:(BOOL)arg3;
-(void)imageDownloadDidFinish:(id)arg1;
-(void)imageDownload:(id)arg1 failedWithError:(id)arg2;
-(id)cachedImageForURL:(id)arg1;
-(id)annotatedImage:(id)arg1 fromCache:(BOOL)arg2 synchronous:(BOOL)arg3 duration:(double)arg4;
-(void)cacheImage:(id)arg1 forURL:(id)arg2;
-(void)cancelLoadingImageForURL:(id)arg1;
-(void)setDownloads:(id)arg1;
-(void)dealloc;
-(void)setDelegate:(id)arg1;
-(id)init;
-(void)setCache:(id)arg1;
-(void).cxx_destruct;
@end