/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:24:47 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol SPVASTRequestDelegate
@optional
-(void)request(id):arg1 didFailWithError(id):arg2 ;
@required
-(void)request(id):arg1 didFinishLoadingResponse(id):arg2 ;
-(void)request(id):arg1 didFinishLoadingResponse(id):arg2 ;
@end

@protocol SPTHTTPImageLoaderDelegate
@optional
-(void)imageLoader(id):arg1 didFailToLoadImageForURL(id):arg2 context(id):arg3 error(id):arg4 ;
@required
-(void)imageLoader(id):arg1 didFinishLoadingImage(id):arg2 forURL(id):arg3 context(id):arg4 loadedSynchronously(BOOL):arg5 ;
-(void)imageLoader(id):arg1 didFinishLoadingImage(id):arg2 forURL(id):arg3 context(id):arg4 loadedSynchronously(BOOL):arg5 ;
@end

@protocol SPTNowPlayingDurationViewDataSource
@required
-(double)durationViewCurrentPosition(id):arg1 ;
-(double)durationViewCurrentDuration(id):arg1 ;
-(BOOL)durationViewShouldAnimate(id):arg1 ;
-(BOOL)durationViewDisallowSeeking(id):arg1 ;
-(double)durationViewCurrentPosition(id):arg1 ;
-(double)durationViewCurrentDuration(id):arg1 ;
-(BOOL)durationViewShouldAnimate(id):arg1 ;
-(BOOL)durationViewDisallowSeeking(id):arg1 ;
@end
