/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:21:03 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface SPTProductStateMonitorController : NSObject {
	BOOL _showingLoadingHUD; 
	SessionController* _sessionController; 
	LoginStateController* _loginStateController; 
	TrialController* _trialController; 
	LogCenter* _logCenter; 
	SPKVObservation* _paymentStateObservation; 
	SPTask* _reloginTask; 
	SPTProgressView* _progressView; 
	NSTimer* _forcedReconnectTimer; 
	UIWindow* _loadingWindow; 
	UIImage* _cachedScreenshot; 
	int _cachedSupportedOrientation; 
	float _reconnectIncrement; 
}
@property (assign,nonatomic) BOOL showingLoadingHUD; 				//@synthesize showingLoadingHUD=_showingLoadingHUD - In the implementation block
@property (assign,nonatomic,__weak) SessionController* sessionController; 				//@synthesize sessionController=_sessionController - In the implementation block
@property (assign,nonatomic,__weak) LoginStateController* loginStateController; 				//@synthesize loginStateController=_loginStateController - In the implementation block
@property (assign,nonatomic,__weak) TrialController* trialController; 				//@synthesize trialController=_trialController - In the implementation block
@property (assign,nonatomic,__weak) LogCenter* logCenter; 				//@synthesize logCenter=_logCenter - In the implementation block
@property (nonatomic,retain) SPKVObservation* paymentStateObservation; 				//@synthesize paymentStateObservation=_paymentStateObservation - In the implementation block
@property (nonatomic,retain) SPTask* reloginTask; 				//@synthesize reloginTask=_reloginTask - In the implementation block
@property (nonatomic,retain) SPTProgressView* progressView; 				//@synthesize progressView=_progressView - In the implementation block
@property (nonatomic,retain) NSTimer* forcedReconnectTimer; 				//@synthesize forcedReconnectTimer=_forcedReconnectTimer - In the implementation block
@property (nonatomic,retain) UIWindow* loadingWindow; 				//@synthesize loadingWindow=_loadingWindow - In the implementation block
@property (nonatomic,retain) UIImage* cachedScreenshot; 				//@synthesize cachedScreenshot=_cachedScreenshot - In the implementation block
@property (assign,nonatomic) int cachedSupportedOrientation; 				//@synthesize cachedSupportedOrientation=_cachedSupportedOrientation - In the implementation block
@property (assign,nonatomic) float reconnectIncrement; 				//@synthesize reconnectIncrement=_reconnectIncrement - In the implementation block
+(id)defaultController;
-(id)initWithSessionController:(id)arg1 loginStateController:(id)arg2 trialController:(id)arg3;
-(void)relogUserForPremiumActivation;
-(void)setPaymentStateObservation:(id)arg1;
-(void)startObservingApplicationChanges;
-(void)startPollingPaymentState;
-(void)applicationWillEnterForegroundOrDidFinishLaunching;
-(float)reconnectInterval;
-(void)checkIfProductStateHasUpdatedAndPollIfNeeded:(id)arg1;
-(void)setForcedReconnectTimer:(id)arg1;
-(void)setReconnectIncrement:(float)arg1;
-(BOOL)isTrialOrPremiumUser;
-(void)removePaymentAndProductObservations;
-(void)removeApplicationObservations;
-(void)showLoadingHUD;
-(void)setReloginTask:(id)arg1;
-(void)hideLoadingHUD;
-(id)screenshotBackground;
-(void)setLoadingWindow:(id)arg1;
-(void)hideLoadingHUDAndInvalidateCache:(BOOL)arg1;
-(void)setCachedScreenshot:(id)arg1;
-(void)setCachedSupportedOrientation:(int)arg1;
-(void)startObservingPaymentAndProductChanges;
-(void)setShowingLoadingHUD:(BOOL)arg1;
-(void)setSessionController:(id)arg1;
-(void)setLoginStateController:(id)arg1;
-(void)setTrialController:(id)arg1;
-(void)setLogCenter:(id)arg1;
-(void)applicationWillResignActive;
-(void)setProgressView:(id)arg1;
-(void).cxx_destruct;
@end