/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:22:20 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface SPTThemeFontInterpreter : NSObject {
}
+(id)resolveDependenciesForSpecifier:(id)arg1 resolver:(id)arg2 reportErrors:(BOOL)arg3;
+(id)interpretFontSpecifierInternal:(id)arg1 withName:(id)arg2 forKey:(id)arg3 resolver:(id)arg4 reportErrors:(BOOL)arg5;
+(id)interpretDynamicFontSpecifier:(id)arg1 name:(id)arg2 forKey:(id)arg3 reportErrors:(BOOL)arg4;
+(id)interpretSystemFontSpecifier:(id)arg1 name:(id)arg2 size:(float)arg3 forKey:(id)arg4 reportErrors:(BOOL)arg5;
+(id)interpretNamedFontSpecifier:(id)arg1 name:(id)arg2 size:(float)arg3 forKey:(id)arg4 resolver:(id)arg5 reportErrors:(BOOL)arg6;
+(id)interpretNamedFontSpecifierIOS7:(id)arg1 name:(id)arg2 size:(float)arg3 forKey:(id)arg4 resolver:(id)arg5 reportErrors:(BOOL)arg6;
+(void)applySmallCapsSettings:(id)arg1 toFeatures:(id)arg2 size:(float*)arg3;
+(void)applyNumberSpacing:(id)arg1 toFeatures:(id)arg2 fontKey:(id)arg3 reportErrors:(BOOL)arg4;
+(id)interpretFontSpecifier:(id)arg1 forKey:(id)arg2 resolver:(id)arg3 reportErrors:(BOOL)arg4;
@end