/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:25:00 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface SPVASTTrackingEvent : NSObject {
	NSString* _event; 
	NSURL* _URL; 
}
@property (nonatomic,retain) NSString* event; 				//@synthesize event=_event - In the implementation block
@property (nonatomic,retain) NSURL* URL; 				//@synthesize URL=_URL - In the implementation block
-(id)description;
-(void)setURL:(id)arg1;
-(id)initWithNode:(id)arg1;
-(void)setEvent:(id)arg1;
-(void).cxx_destruct;
@end