/*
 * This header is generated by weak_classdump 0.2
 * on Wednesday, April 30, 2014 at 2:22:25 PM Central European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface SyncController : NSObject {
	SPTabBarItem* _item; 
	NSTimer* _updateSyncStateTimer; 
	BOOL _syncing; 
	id _progressObs; 
}
+(id)defaultController;
+(void)load;
-(void)startedSyncingNotification:(id)arg1;
-(void)stoppedSyncingNotification:(id)arg1;
-(void)progressChanged:(id)arg1 on:(id)arg2;
-(void)updateSyncState:(id)arg1;
-(void)updateSyncStateTimerFired:(id)arg1;
-(void)dealloc;
-(id)init;
-(void).cxx_destruct;
@end