/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:08:43 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface AMPVideoRenderView : UIView {
	struct AMPVideoRenderViewIvars* m; 
	CGSize mContentSize; 
	CGRect mContentBounds; 
}
@property (nonatomic,retain) UIColor* blendColor; 
@property (nonatomic,copy) CGSize contentSize; 
@property (nonatomic,copy) CGRect contentBounds; 
+(void)displayAll:(id)arg1;
+(void)applicationDidBecomeActive:(id)arg1;
+(void)initialize;
+(Class)layerClass;
+(void)load;
-(void)setupAll;
-(void)removeFromDisplayLoop;
-(void)disposeOpenGL;
-(void)setupOpenGL;
-(CGRect)backingBounds;
-(CGRect)convertRectFromBacking:(CGRect)arg1;
-(void)clearRenderBuffer;
-(void)setupMesh;
-(void)setupMatrix;
-(void)setupViewport;
-(void)contentGeometryChanged;
-(void)displayIt;
-(void)deleteRenderBuffer;
-(void)setupProgram;
-(void)setupTexture;
-(void)setupRenderBuffer;
-(void)addToDisplayLoop;
-(void)setBlendColor:(id)arg1;
-(void)renderWithBuffer:(const void**)arg1 size:(int)arg2 width:(int)arg3 height:(int)arg4 mirrored:(BOOL)arg5 orientation:(int)arg6;
-(CGRect)convertRectToBacking:(CGRect)arg1;
-(void)render;
-(id)initWithFrame:(CGRect)arg1;
-(void)dealloc;
-(id)initWithCoder:(id)arg1;
-(void)setContentMode:(int)arg1;
-(void)applicationDidBecomeActive:(id)arg1;
-(void)applicationWillResignActive:(id)arg1;
-(void)willMoveToWindow:(id)arg1;
-(CGRect)contentRect;
-(void)reshape;
-(void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
-(void)clear;
-(void)display;
@end