/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:13:44 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface LCError : NSError {
	int mErrorType; 
}
@property (assign,nonatomic) int errorType; 
+(id)errorWithType:(int)arg1 domain:(id)arg2 code:(int)arg3;
+(id)errorWithError:(id)arg1;
-(id)initWithType:(int)arg1 domain:(id)arg2 code:(int)arg3;
-(void)setErrorType:(int)arg1;
-(void)dealloc;
-(id)description;
-(id)initWithError:(id)arg1;
@end