/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:13:00 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface LCNoticeLinkProcessor : NSObject {
}
+(BOOL)isLANScheme:(id)arg1;
+(id)URLByTrimmingLANScheme:(id)arg1;
+(BOOL)isOpenExternalBrowserLANScheme:(id)arg1;
+(BOOL)isRequestUserInfoLANScheme:(id)arg1;
+(BOOL)validateHostURL:(id)arg1;
+(void)setLANUserInfoCookieWithDomain:(id)arg1;
+(BOOL)isCloseViewControllerLANScheme:(id)arg1;
+(BOOL)isOpenBoardViewControllerLANScheme:(id)arg1;
+(id)convertLinkPath:(int)arg1;
+(id)processBoardLinkWithURL:(id)arg1 noticeDelegate:(id)arg2;
+(id)processNotificationLinkWithURL:(id)arg1 noticeDelegate:(id)arg2;
+(id)processLinkWithURL:(id)arg1 linkPath:(int)arg2 noticeDelegate:(id)arg3;
@end