/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:12:21 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface LEGYFetchOpQueue : NSObject {
	NSManagedObjectContext* _writeManagedObjectContext; 
	NSManagedObjectModel* _managedObjectModel; 
	NSPersistentStoreCoordinator* _persistentStoreCoordinator; 
	LEGYFetchOpDao* fetchOpDao; 
	id _onAddedCallback; 
}
+(id)instance:(id)arg1;
-(id)initWithOnAddedCallback:(id)arg1;
-(id)writeManagedObjectContext;
-(void)append:(id)arg1 requestFetchOp:(id)arg2 withAsyncFetchOp:(BOOL)arg3;
-(id)get:(int)arg1;
-(void)deleteDone;
-(void)doneOperations:(id)arg1;
-(void)fail:(id)arg1 withError:(int)arg2;
-(id)managedObjectModel;
-(id)persistentStoreCoordinator;
-(void).cxx_destruct;
@end