/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:09:21 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <LGPhotoViewDataSource.h>
#import <LGImageCropDataSource.h>
#import <LGInstantViewDelegate.h>

@interface LGAssetsViewController : LGThumbnailsViewController <LGPhotoViewDataSource, LGImageCropDataSource, LGInstantViewDelegate> {
	BOOL _isAssetsFullyLoaded; 
	BOOL _isRequestingAssetsFullyLoaded; 
	LGAssetGroup* _group; 
	LGAssetSections* _assetSections; 
	LGMenuBarView* _bottomMenuBarView; 
	UIView* _dimdView; 
	UIView* _sortOptionView; 
	int _lastSelectButtonTag; 
	double _lastSelectTime; 
}
@property (nonatomic,retain) LGAssetGroup* group; 				//@synthesize group=_group - In the implementation block
@property (nonatomic,retain) LGAssetSections* assetSections; 				//@synthesize assetSections=_assetSections - In the implementation block
@property (nonatomic,retain) LGMenuBarView* bottomMenuBarView; 				//@synthesize bottomMenuBarView=_bottomMenuBarView - In the implementation block
@property (nonatomic,retain) UIView* dimdView; 				//@synthesize dimdView=_dimdView - In the implementation block
@property (nonatomic,retain) UIView* sortOptionView; 				//@synthesize sortOptionView=_sortOptionView - In the implementation block
@property (assign,nonatomic) BOOL isAssetsFullyLoaded; 				//@synthesize isAssetsFullyLoaded=_isAssetsFullyLoaded - In the implementation block
@property (assign,nonatomic) BOOL isRequestingAssetsFullyLoaded; 				//@synthesize isRequestingAssetsFullyLoaded=_isRequestingAssetsFullyLoaded - In the implementation block
@property (assign,nonatomic) double lastSelectTime; 				//@synthesize lastSelectTime=_lastSelectTime - In the implementation block
@property (assign,nonatomic) int lastSelectButtonTag; 				//@synthesize lastSelectButtonTag=_lastSelectButtonTag - In the implementation block
-(void)updateTableFooterViewFrame;
-(void)updateLastPhotoThumbnail:(id)arg1;
-(id)photoViewController;
-(void)setIsAssetsFullyLoaded:(BOOL)arg1;
-(void)updateForCurrentLanuage;
-(void)setBottomMenuBarView:(id)arg1;
-(void)loadAllAssets;
-(void)selectAllAsset;
-(void)setSortOptionView:(id)arg1;
-(void)setupSortOptionTitleView;
-(id)updateCheckedBadgeCountOfMenuBar:(BOOL)arg1;
-(void)repositionMenuBar;
-(void)reloadGalleryData;
-(unsigned)numberOfAssetsAtSection:(unsigned)arg1;
-(void)cleanUpShowSortOptionButton;
-(void)updateTableFooterForCurrentLanguage;
-(void)didTapShowSortOptionButton:(id)arg1;
-(void)didTapSortOptionButton:(id)arg1;
-(void)setIsRequestingAssetsFullyLoaded:(BOOL)arg1;
-(void)setDimdView:(id)arg1;
-(void)updateLastPhotoThumbnailOnMainThread;
-(void)setAssetSections:(id)arg1;
-(void)refreshDataAnimated:(BOOL)arg1;
-(id)assetWithSection:(unsigned)arg1 row:(unsigned)arg2;
-(void)showPhotoViewControllerForAssetURL:(id)arg1 backwardIndex:(int)arg2;
-(void)didAssetCheckBoxSelected:(id)arg1;
-(BOOL)showPhotoViewControllerWithSection:(int)arg1 row:(int)arg2 animated:(BOOL)arg3;
-(void)playVideo:(id)arg1;
-(void)setLastSelectTime:(double)arg1;
-(void)setLastSelectButtonTag:(int)arg1;
-(void)setupNavigationBar;
-(unsigned)numberOfAssetSections;
-(id)initWithAssetGroup:(id)arg1 assetsLibrary:(id)arg2;
-(unsigned)numberOfThumbnailsInSection:(unsigned)arg1;
-(void)lgAssetsLibraryDidGetAssetSections:(id)arg1;
-(void)didAssetSelected:(id)arg1;
-(id)nClickAreaId;
-(void)didChangePageDisappearValue;
-(void)resetSelectedAssets;
-(void)dealloc;
-(float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
-(float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
-(id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
-(id)tableView:(id)arg1 willSelectRowAtIndexPath:(id)arg2;
-(void)scrollViewDidScroll:(id)arg1;
-(int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
-(int)numberOfSectionsInTableView:(id)arg1;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)viewDidUnload;
-(id)groupName;
-(void)setGroup:(id)arg1;
-(unsigned)numberOfAssets;
-(void).cxx_destruct;
@end