/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:10:57 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface LineProductSimple : NSObject {
	NSString* __productId; 
	long long __packageId; 
	int __version; 
	BOOL __onSale; 
	long long __validUntil; 
	BOOL __grantedByDefault; 
	int __displayOrder; 
	struct {
		unsigned int packageId:1;
		unsigned int version:1;
		unsigned int onSale:1;
		unsigned int validUntil:1;
		unsigned int grantedByDefault:1;
		unsigned int displayOrder:1;
	} __isSet; 
}
@property (nonatomic,retain) NSString* productId; 				//@synthesize _productId=__productId - In the implementation block
@property (assign,nonatomic) long long packageId; 				//@synthesize _packageId=__packageId - In the implementation block
@property (assign,nonatomic) int version; 				//@synthesize _version=__version - In the implementation block
@property (assign,getter=isOnSale,nonatomic) BOOL onSale; 				//@synthesize _onSale=__onSale - In the implementation block
@property (assign,nonatomic) long long validUntil; 				//@synthesize _validUntil=__validUntil - In the implementation block
@property (assign,getter=isGrantedByDefault,nonatomic) BOOL grantedByDefault; 				//@synthesize _grantedByDefault=__grantedByDefault - In the implementation block
@property (assign,nonatomic) int displayOrder; 				//@synthesize _displayOrder=__displayOrder - In the implementation block
-(void)read:(id)arg1;
-(void)setGrantedByDefault:(BOOL)arg1;
-(void)setOnSale:(BOOL)arg1;
-(void)setProductId:(id)arg1;
-(void)setValidUntil:(long long)arg1;
-(void)setPackageId:(long long)arg1;
-(void)setDisplayOrder:(int)arg1;
-(void)setVersion:(int)arg1;
-(void).cxx_destruct;
-(void)write:(id)arg1;
@end