/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:08:56 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface LineMetaProfile : NSObject {
	long long __createTime; 
	NSString* __regionCode; 
	NSDictionary* __identities; 
	struct {
		unsigned int createTime:1;
	} __isSet; 
}
@property (assign,nonatomic) long long createTime; 				//@synthesize _createTime=__createTime - In the implementation block
@property (nonatomic,retain) NSString* regionCode; 				//@synthesize _regionCode=__regionCode - In the implementation block
@property (nonatomic,retain) NSDictionary* identities; 				//@synthesize _identities=__identities - In the implementation block
-(void)setRegionCode:(id)arg1;
-(void)read:(id)arg1;
-(void)setCreateTime:(long long)arg1;
-(void)setIdentities:(id)arg1;
-(void).cxx_destruct;
-(void)write:(id)arg1;
@end