/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:12:12 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface LineSQLiteQueryResult : NSObject {
	NSArray* rows_; 
	int rowsAffected_; 
	long long insertedID_; 
}
@property (nonatomic,retain) NSArray* rows; 
@property (assign,nonatomic) int rowAffected; 
@property (assign,nonatomic) long long insertedID; 
-(void)setRowAffected:(int)arg1;
-(void)setInsertedID:(long long)arg1;
-(void)setRows:(id)arg1;
-(void).cxx_destruct;
@end