/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:12:20 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface LineMainTabScheme : NSObject {
}
+(BOOL)isFriendSchemeWithURLString:(id)arg1;
+(BOOL)isChatSchemeWithURLString:(id)arg1;
+(BOOL)isTimelineSchemeWithURLString:(id)arg1;
+(BOOL)isAddFriendSchemeWithURLString:(id)arg1;
+(BOOL)isMoreSchemeWithURLString:(id)arg1;
+(id)friendScheme;
+(id)friendSchemeURL;
+(id)chatScheme;
+(id)chatSchemeURL;
+(id)timelineScheme;
+(id)timelineSchemeURL;
+(id)addFriendScheme;
+(id)addFriendSchemeURL;
+(id)moreScheme;
+(id)moreSchemeURL;
+(BOOL)canBeHandledWithURLString:(id)arg1;
+(void)executeSchemeFromURL:(id)arg1 fromSourceApplication:(id)arg2 withOptions:(unsigned)arg3;
+(void)beforeExecuteSchemeWithOptions:(unsigned)arg1;
+(int)scheme;
@end