/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:15:42 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface LineSticonTabView : LineStickerTabView {
	LineStickerTabButton* _kaomojiButton; 
}
@property (nonatomic,retain) LineStickerTabButton* kaomojiButton; 				//@synthesize kaomojiButton=_kaomojiButton - In the implementation block
-(id)initWithFrame:(CGRect)arg1 controllerView:(id)arg2 options:(unsigned)arg3;
-(void)selectKaomojiButton;
-(void)removeNewBadgeForPackage:(id)arg1;
-(int)stickerTabCount;
-(BOOL)shouldShowShopIcon;
-(void)setBackButtonAction;
-(void)setSticonToggleButtonAction;
-(void)addTailButtons;
-(void)initTabDatasource;
-(void)configureButton:(id)arg1 forPackage:(id)arg2;
-(void)moveTailButtonsWithSuperview:(id)arg1 offsetX:(float)arg2;
-(void)controlProgressViewWithPackage:(id)arg1 WithProgress:(float)arg2;
-(void)letControllerOpenPackage:(id)arg1;
-(void)stickerPackageDownloadStarted:(id)arg1;
-(void)stickerPackageJustDownloadEnded:(id)arg1;
-(void)stickerPackage:(id)arg1 downloaded:(float)arg2;
-(void)stickerPackageDownloadSuccess:(id)arg1;
-(void)stickerPackageDownloadCanceled:(id)arg1;
-(void)stickerPackageDownloadFailed:(id)arg1;
-(void)kaomojiButtonPressed:(id)arg1;
-(void)setKaomojiButton:(id)arg1;
-(void).cxx_destruct;
@end