/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:08:49 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface LineFriendChannelMatrix : NSObject {
	NSString* __channelId; 
	NSString* __representMid; 
	int __count; 
	int __point; 
	struct {
		unsigned int count:1;
		unsigned int point:1;
	} __isSet; 
}
@property (nonatomic,retain) NSString* channelId; 				//@synthesize _channelId=__channelId - In the implementation block
@property (nonatomic,retain) NSString* representMid; 				//@synthesize _representMid=__representMid - In the implementation block
@property (assign,nonatomic) int count; 				//@synthesize _count=__count - In the implementation block
@property (assign,nonatomic) int point; 				//@synthesize _point=__point - In the implementation block
-(void)setChannelId:(id)arg1;
-(void)read:(id)arg1;
-(void)setRepresentMid:(id)arg1;
-(void)setCount:(int)arg1;
-(void)setPoint:(int)arg1;
-(void).cxx_destruct;
-(void)write:(id)arg1;
@end