/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:10:22 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <LineAlbumDataSource.h>
#import <NLProfilePopupViewerDelegate.h>

@interface LineAlbumController : NSObject <LineAlbumDataSource, NLProfilePopupViewerDelegate> {
	NLProfilePopupViewer* _profilePopupViewer; 
	UIViewController* _viewController; 
}
@property (nonatomic,retain) NLProfilePopupViewer* profilePopupViewer; 				//@synthesize profilePopupViewer=_profilePopupViewer - In the implementation block
@property (nonatomic,retain) UIViewController* viewController; 				//@synthesize viewController=_viewController - In the implementation block
+(void)updateServerInfo;
+(void)updateMyProfile;
+(id)sharedInstance;
+(id)allocWithZone:(NSZone*)arg1;
+(void)initialize;
-(void)presentAlbumListOfGroup:(id)arg1 presentationStyle:(int)arg2 fromViewController:(id)arg3;
-(void)setProfilePopupViewer:(id)arg1;
-(int)photoSizeType;
-(void)profilePopupViewer:(id)arg1 willSelectButtonItem:(id)arg2;
-(void)profilePopupViewer:(id)arg1 didSelectButtonItem:(id)arg2;
-(id)lineAlbumChannelToken;
-(id)myMid;
-(id)myName;
-(void)lineUser:(id)arg1 completionBlock:(id)arg2;
-(void)presentAlbumListOfGroup:(id)arg1 object:(id)arg2 presentationStyle:(int)arg3 fromViewController:(id)arg4;
-(BOOL)isJoiningGroup:(id)arg1;
-(id)fileURLForStore:(id)arg1 subStore:(id)arg2;
-(id)albumNewItemExistNotificationName;
-(void)determineButtonItemsOfViewer:(id)arg1 fromUser:(id)arg2;
-(id)myProfileView;
-(void)showProfileView:(id)arg1;
-(id)userProfileViewByUser:(id)arg1;
-(void)showUserProfileViewWithMID:(id)arg1;
-(void)requestWithUrlRequest:(id)arg1 requestInfo:(id)arg2 response:(id)arg3;
-(void)thumbImage:(id)arg1 withResultBlock:(id)arg2;
-(void)showProfileImageDetailViewWithTitle:(id)arg1 thumbnailSource:(id)arg2;
-(void)resetAccessToken;
-(id)lineAccessToken;
-(void)sendEditImageToLineCamera:(id)arg1 mid:(id)arg2;
-(void)postImageToMyHome:(id)arg1 fromViewController:(id)arg2;
-(void)sendImageToOtherChatRoom:(id)arg1;
-(void)actionAlbumItemExist:(id)arg1;
-(void)actionChatRoomMoreMenuWillAppear:(id)arg1;
-(void)addObserversForLineNotification;
-(void)showProfilePopupView:(id)arg1;
-(void)profilePopupViewDidDisappear;
-(void)dealloc;
-(id)init;
-(id)copyWithZone:(NSZone*)arg1;
-(void)setViewController:(id)arg1;
-(id)groupMembers:(id)arg1;
-(void).cxx_destruct;
@end