/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:10:27 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface LineCoinPurchaseReservation : NSObject {
	NSString* __productId; 
	NSString* __country; 
	NSString* __currency; 
	NSString* __price; 
	int __appStoreCode; 
	NSString* __language; 
	int __pgCode; 
	NSString* __redirectUrl; 
	struct {
		unsigned int appStoreCode:1;
		unsigned int pgCode:1;
	} __isSet; 
}
@property (nonatomic,retain) NSString* productId; 				//@synthesize _productId=__productId - In the implementation block
@property (nonatomic,retain) NSString* country; 				//@synthesize _country=__country - In the implementation block
@property (nonatomic,retain) NSString* currency; 				//@synthesize _currency=__currency - In the implementation block
@property (nonatomic,retain) NSString* price; 				//@synthesize _price=__price - In the implementation block
@property (assign,nonatomic) int appStoreCode; 				//@synthesize _appStoreCode=__appStoreCode - In the implementation block
@property (nonatomic,retain) NSString* language; 				//@synthesize _language=__language - In the implementation block
@property (assign,nonatomic) int pgCode; 				//@synthesize _pgCode=__pgCode - In the implementation block
@property (nonatomic,retain) NSString* redirectUrl; 				//@synthesize _redirectUrl=__redirectUrl - In the implementation block
-(void)read:(id)arg1;
-(void)setProductId:(id)arg1;
-(void)setAppStoreCode:(int)arg1;
-(void)setPgCode:(int)arg1;
-(void)setRedirectUrl:(id)arg1;
-(void)setCountry:(id)arg1;
-(void)setLanguage:(id)arg1;
-(void)setCurrency:(id)arg1;
-(void)setPrice:(id)arg1;
-(void).cxx_destruct;
-(void)write:(id)arg1;
@end