/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:13:40 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface MBAPIHelper : NSObject {
}
+(id)currentVisibleViewController;
+(id)lineSocialGraphManager;
+(BOOL)isPhotoSizeSmall;
+(id)listPhotoConfig;
+(BOOL)isPhotoSizeSmallInPage;
+(id)listPhotoMultiConfig;
+(BOOL)listMovieAutoPlayNoti;
+(BOOL)listMovieAutoPlayConfig;
+(void)saveListMovieAutoPlayNoti;
+(id)lineDataSource;
+(void)setIsPhotoSizeSmallInPage;
+(void)syncMyHomeGroup;
+(void)setImageConfig:(id)arg1;
+(id)getCachedUserPopupWithMID:(id)arg1;
+(id)lineStickerDataSource;
+(void)updateMyHomeCache;
+(id)lineUIProvider;
+(id)listMovieConfig;
+(id)listSnapMovieConfig;
+(void)requestAutoOpen;
+(void)saveListMovieAutoPlayConfig:(BOOL)arg1;
+(void)sharePostToTalkRoomWithInfo:(id)arg1 completionBlock:(id)arg2;
+(id)getUserPopupWithMID:(id)arg1;
+(void)sharePostThmbnailWithOid:(id)arg1 type:(int)arg2 withResultBlock:(id)arg3;
+(id)escapedString:(id)arg1;
+(id)lineDelegate;
+(void)setLineDataSource:(id)arg1;
+(void)setLineUIProvider:(id)arg1;
+(void)setLineStickerDataSource:(id)arg1;
+(void)setLineSocialGraphManager:(id)arg1;
+(void)setNetworkService:(id)arg1;
+(void)needSyncMyHomeGroup;
+(void)setLineDelegate:(id)arg1;
+(void)hasNewPostWithMID:(id)arg1 block:(id)arg2;
+(id)createPostOptions;
+(void)createPostWithInfo:(id)arg1 sourceType:(id)arg2 errorBlock:(id)arg3;
+(id)updateCoverImageOptions;
+(void)updateCoverImageWithObjectID:(id)arg1 errorBlock:(id)arg2;
+(void)setNickname:(id)arg1 forMID:(id)arg2;
+(void)refreshProfileImageForMID:(id)arg1;
+(float)uploadImageQuality;
+(int)uploadImageSize;
+(id)obsInfoWithMediaOid:(id)arg1;
+(id)networkService;
+(void)fetchMyHomeCoverImage:(id)arg1 completion:(id)arg2;
+(void)deleteFriendWithMID:(id)arg1;
+(BOOL)stickerWithTextAlertConfig;
+(void)saveStickerWithTextAlertConfig;
+(void)initialize;
@end