/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:15:47 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface MBMyHomeGroupEditCell : MBTableViewActionCell {
	UILabel* mGroupName; 
	UIButton* mGroupCount; 
	UIButton* mEditButton; 
	NLMyhomeGroup* mGroup; 
}
-(void)layoutSubviews;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
-(void)setData:(id)arg1;
-(void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;
-(id)group;
-(void).cxx_destruct;
@end