/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:12:14 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface MBMyHomeErrorMessageView : MBMessageView {
	UIImageView* mTopImageView; 
	UIView* mBoardView; 
	UIImageView* mIconImageView; 
	UILabel* mMessageLabel; 
	float mHeight; 
}
+(id)errorMessageView;
-(id)initWithFrame:(CGRect)arg1;
-(void)layoutSubviews;
-(void)layout;
-(float)height;
-(void).cxx_destruct;
@end