/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:13:14 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface MBRecallInfo : NSObject {
	unsigned mStart; 
	unsigned mEnd; 
	NSString* mActorId; 
	MBActor* mActor; 
	BOOL mUserValid; 
}
@property (nonatomic,copy) unsigned start; 
@property (nonatomic,copy) unsigned end; 
@property (nonatomic,copy) NSString* actorId; 
@property (nonatomic,copy) MBActor* actor; 
@property (nonatomic,copy) BOOL userValid; 
+(id)initWithTextInfoArray:(id)arg1;
-(id)initWithRecallInfo:(id)arg1;
-(id)initWithCoder:(id)arg1;
-(void)encodeWithCoder:(id)arg1;
-(void).cxx_destruct;
@end