/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:14:24 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface MBStickerManager : NSObject {
	BOOL _isPlaySoundForAnimationSticker; 
	BOOL _isPlaySoundCommentForAnimationSticker; 
	NSString* _lastInsertedActivityID; 
	NSString* _lastInsertedActivityCommentID; 
}
@property (nonatomic,copy) NSString* lastInsertedActivityID; 				//@synthesize lastInsertedActivityID=_lastInsertedActivityID - In the implementation block
@property (assign,nonatomic) BOOL isPlaySoundForAnimationSticker; 				//@synthesize isPlaySoundForAnimationSticker=_isPlaySoundForAnimationSticker - In the implementation block
@property (nonatomic,copy) NSString* lastInsertedActivityCommentID; 				//@synthesize lastInsertedActivityCommentID=_lastInsertedActivityCommentID - In the implementation block
@property (assign,nonatomic) BOOL isPlaySoundCommentForAnimationSticker; 				//@synthesize isPlaySoundCommentForAnimationSticker=_isPlaySoundCommentForAnimationSticker - In the implementation block
+(id)sharedInstance;
+(id)allocWithZone:(NSZone*)arg1;
-(void)setLastInsertedActivityID:(id)arg1;
-(void)setIsPlaySoundForAnimationSticker:(BOOL)arg1;
-(void)setLastInsertedActivityCommentID:(id)arg1;
-(void)setIsPlaySoundCommentForAnimationSticker:(BOOL)arg1;
-(void)saveLastActivity:(id)arg1;
-(void)saveLastComment:(id)arg1;
-(void)clearLastActivity;
-(void)clearLastComment;
-(id)activityCommentID:(id)arg1 comment:(int)arg2;
-(id)copyWithZone:(NSZone*)arg1;
-(void).cxx_destruct;
@end