/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:14:38 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <MBActionable.h>

@interface MBTableViewActionCell : UITableViewCell <MBActionable> {
	MBAction* mAction; 
	NSIndexPath* _indexPath; 
}
@property (nonatomic,retain) NSIndexPath* indexPath; 				//@synthesize indexPath=_indexPath - In the implementation block
-(void)setActionWithName:(id)arg1 block:(id)arg2;
-(void)reLayout:(id)arg1 reload:(BOOL)arg2;
-(void)performActionWithName:(id)arg1 sender:(id)arg2 userInfo:(id)arg3;
-(BOOL)hasActions;
-(id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
-(void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;
-(void)setIndexPath:(id)arg1;
-(void).cxx_destruct;
@end