/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:12:08 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol UITextFieldDelegate
@optional
-(BOOL)textFieldShouldBeginEditing(id):arg1 ;
-(void)textFieldDidBeginEditing(id):arg1 ;
-(BOOL)textFieldShouldEndEditing(id):arg1 ;
-(void)textFieldDidEndEditing(id):arg1 ;
-(BOOL)textField(id):arg1 shouldChangeCharactersInRange({):arg2 replacementString(_):arg3 ;
-(BOOL)textFieldShouldClear(id):arg1 ;
-(BOOL)textFieldShouldReturn(id):arg1 ;
@end

@protocol MFMailComposeViewControllerDelegate
@optional
-(void)mailComposeController(id):arg1 didFinishWithResult(int):arg2 error(id):arg3 ;
@end
