/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:14:55 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface MoreTabImageView : UIView {
	UIImageView* imageView_; 
	ProfileImageView* profileImageView_; 
	UIActivityIndicatorView* act_; 
	LineFileDownload* currentDownload_; 
	UIImageView* iconNew_; 
	LineMoreItem* item_; 
	unsigned type_; 
	BOOL isNewIconEnabled; 
}
@property (nonatomic,copy) ProfileImageView* profileImageView; 
@property (assign,nonatomic) BOOL isNewIconEnabled; 
-(void)setItem:(id)arg1 forType:(unsigned)arg2;
-(void)setIsNewIconEnabled:(BOOL)arg1;
-(id)addFriendsIconImage;
-(id)timelineNewPostIconImage;
-(id)timelineIconImage;
-(id)settingIconImage;
-(id)stickerShopIconImage;
-(id)officalAccountsIconImage;
-(id)noticeIconImage;
-(id)lineAppIconImage;
-(id)gamesIconImage;
-(id)musicIconImage;
-(id)themeShopImage;
-(id)lineCallIconImage;
-(BOOL)hasThemeIconWithMoreItem:(id)arg1;
-(void)applyThemeIconWithMoreItem:(id)arg1;
-(id)timelineNewPostNotiIconImage;
-(id)timelineNewNotiIconImage;
-(BOOL)render;
-(id)initWithFrame:(CGRect)arg1;
-(void)setFrame:(CGRect)arg1;
-(void)layoutSubviews;
-(void).cxx_destruct;
@end