/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:09:53 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UIWebViewDelegate.h>

@interface NLAgeVerificationWebViewViewController : NLViewController <UIWebViewDelegate> {
	UIWebView* webView; 
	id<NLAgeVerificationDelegate> avDelegate; 
	NSMutableArray* _cachedLink; 
	int _carrierCode; 
	NSString* _sessionId; 
	NSString* _verificationToken; 
	id _networkActivityIndicatorHandle; 
}
@property (nonatomic,retain) UIWebView* webView; 
@property (assign,nonatomic) id<NLAgeVerificationDelegate> avDelegate; 
@property (nonatomic,retain) NSMutableArray* cachedLink; 				//@synthesize cachedLink=_cachedLink - In the implementation block
@property (assign,nonatomic) int carrierCode; 				//@synthesize carrierCode=_carrierCode - In the implementation block
@property (nonatomic,retain) NSString* sessionId; 				//@synthesize sessionId=_sessionId - In the implementation block
@property (nonatomic,retain) NSString* verificationToken; 				//@synthesize verificationToken=_verificationToken - In the implementation block
@property (nonatomic,retain) id networkActivityIndicatorHandle; 				//@synthesize networkActivityIndicatorHandle=_networkActivityIndicatorHandle - In the implementation block
-(void)onBackPressed:(id)arg1;
-(void)setCachedLink:(id)arg1;
-(void)setCarrierCode:(int)arg1;
-(void)setVerificationToken:(id)arg1;
-(void)retrieveAuthURL;
-(void)clearCookie;
-(void)loadWebViewWithURL:(id)arg1;
-(void)closeViewController;
-(BOOL)isRedirectDocomoURL:(id)arg1;
-(void)checkUserAgeWithVerifier:(id)arg1 redirectURL:(id)arg2;
-(BOOL)isCallbackURL:(id)arg1;
-(BOOL)regularExpression:(id)arg1 URL:(id)arg2;
-(void)setAvDelegate:(id)arg1;
-(void)setNetworkActivityIndicatorHandle:(id)arg1;
-(void)dealloc;
-(id)init;
-(void)didReceiveMemoryWarning;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1;
-(void)viewWillDisappear:(BOOL)arg1;
-(void)setWebView:(id)arg1;
-(void)close;
-(void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
-(BOOL)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(int)arg3;
-(void)webViewDidStartLoad:(id)arg1;
-(void)webViewDidFinishLoad:(id)arg1;
-(void)setSessionId:(id)arg1;
-(void).cxx_destruct;
@end