/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:14:21 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface NLCallTalkServerManager : NSObject {
}
+(BOOL)isNetworkAvailable;
+(id)arraySpotToUserInfo:(id)arg1 withRegionNumber:(id)arg2;
+(BOOL)isNetworkAvailable:(BOOL)arg1 completionBlock:(id)arg2;
+(void)listOfCategories:(id)arg1;
+(id)searchOfSearchSpotInfoWithRegion:(id)arg1 withPhoneNumber:(id)arg2 withCompletionBlock:(id)arg3;
+(id)searchOfSearchSpotInfoWithKeyWord:(id)arg1 withOptionGPS:(id)arg2 withOptionCategory:(int)arg3 withCompletionBlock:(id)arg4;
+(void)validateUserCredit:(id)arg1 withCompletionBlock:(id)arg2;
+(void)openSpotProfileViewWithUserMid:(id)arg1 withPhoneNumber:(id)arg2 withRegionNumber:(id)arg3;
@end