/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:13:54 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface NLCallNonStandardController : NLCallBaseViewController {
	BOOL _animatingVideoControlsVisibility; 
	BOOL _videoControlsHidden; 
	UIView* _viewLoading; 
	NSString* _networkStatusString; 
	NSString* _connectingString; 
	NSString* _callingString; 
	NSString* _receivedVideoCallString; 
	NSString* _receivedVoiceCallString; 
	UIView* _viewCallStatusBar; 
	UIButton* _buttonCallStatusBarControl; 
	UIView* _viewCallStatusBarLabelsCentering; 
	UILabel* _labelCallStatusBarTitle; 
	UILabel* _labelCallStatusBarDuration; 
	UIView* _viewVoiceCall; 
	UIButton* _networkUnstableMessageButton; 
	UIView* _viewCentering; 
	UIView* _viewCallInfo; 
	UIImageView* _imageViewThumbnail; 
	UIImageView* _imageViewThumbnailShadowImage; 
	UILabel* _labelName; 
	UILabel* _labelCallDuration; 
	UIButton* _buttonMinimize; 
	UIView* _viewCallingButtons; 
	UIButton* _buttonMute; 
	UIButton* _buttonSpeaker; 
	UIButton* _buttonCallEnd; 
	UIButton* _buttonVideoCall; 
	UIView* _viewIncomingButtons; 
	UIButton* _buttonReject; 
	UIButton* _buttonAccept; 
	UIView* _viewVideoCall; 
	UIView* _viewMainVideoContainer; 
	UIView* _viewSubVideoContainer; 
	UIImageView* _imageViewSubVideoCover; 
	UIView* _viewSubVideoOff; 
	AMPVideoRenderView* _viewLocalVideoRendering; 
	AMPVideoRenderView* _viewRemoteVideoRendering; 
	AMPVideoRenderView* _currentMainVideoRenderingView; 
	AMPVideoRenderView* _currentSubVideoRenderingView; 
	UIView* _viewVideoButtons; 
	UIButton* _buttonVideoMute; 
	UIButton* _buttonVideoEnd; 
	UIButton* _buttonVideoCameraOff; 
	UIView* _viewVideoCameraSwitchingButtonContainer; 
	UIButton* _buttonVideoCameraSwitching; 
	UIImageView* _imageViewVideoRotatableCameraSwitchingIcon; 
	UIView* _viewVideoMinimizingButtonContainer; 
	UIButton* _buttonVideoMinimizing; 
	UIImageView* _imageViewVideoRotatableMinimizingIcon; 
	UIView* _viewVideoEnding; 
	UIView* _viewVideoEndingPopup; 
	UIImageView* _imageViewVideoEndingPopupIcon; 
	UILabel* _labelVideoEndingPopup; 
	UIImageView* _imageViewVideoRotatableMuteIcon; 
	UIImageView* _imageViewVideoRotatableEndIcon; 
	UIImageView* _imageViewVideoRotatableCameraIcon; 
	UIImageView* _imageViewVideoRotatableCameraOffIcon; 
	UIView* _viewVideoCallingAccept; 
	UIButton* _buttonVideoCallingMinimizing; 
	UIButton* _buttonVideoCallingAcceptEnd; 
	UIButton* _buttonVideoCallingAcceptVoice; 
	UIButton* _buttonVideoCallingAcceptVideo; 
	UILabel* _labelVideoCallingName; 
	UILabel* _labelVideoCallingCall; 
	UIView* _viewVideoCallingProfile; 
	UIImageView* _imageViewVideoCallingBgImage; 
	UIImageView* _imageViewVideoCallingProfileImage; 
	UIView* _viewVideoNetworkStatus; 
	UIView* _viewVideoNetworkStatusCentered; 
	UIImageView* _imageViewVideoNetworkBGImage; 
	UIImageView* _imageViewVideoNetworkStatusIcon; 
	UILabel* _labelVideoNetworkStatus; 
	UIView* _viewMessagePopup; 
	UIImageView* _imageViewMessagePopupBackground; 
	UILabel* _labelMessagePopup; 
	UIImageView* _imageViewMessagePopupIcon; 
	unsigned _videoViewLayout; 
	UIView* _viewVideoUserGuide; 
	UIImageView* _imageViewVideoUserGuideSubVideoEffect; 
	UILabel* _labelVideoUserGuideSubVideoTooltip; 
	UILabel* _labelVideoUserGuideMinimizingButtonTooltip; 
	UIView* _viewVideoUserGuideTapScreenTooltipCentered; 
	UIImageView* _imageViewVideoUserGuideTapScreenTooltipIcon; 
	UILabel* _labelVideoUserGuideTapScreenTooltip; 
	id _orientationObserver; 
	NLCallCustomAlertView* _callAlertView; 
	int _localVideoViewContentMode; 
	int _remoteVideoViewContentMode; 
}
@property (assign,nonatomic) UIView* viewLoading; 				//@synthesize viewLoading=_viewLoading - In the implementation block
@property (nonatomic,retain) NSString* networkStatusString; 				//@synthesize networkStatusString=_networkStatusString - In the implementation block
@property (nonatomic,retain) NSString* connectingString; 				//@synthesize connectingString=_connectingString - In the implementation block
@property (nonatomic,retain) NSString* callingString; 				//@synthesize callingString=_callingString - In the implementation block
@property (nonatomic,retain) NSString* receivedVideoCallString; 				//@synthesize receivedVideoCallString=_receivedVideoCallString - In the implementation block
@property (nonatomic,retain) NSString* receivedVoiceCallString; 				//@synthesize receivedVoiceCallString=_receivedVoiceCallString - In the implementation block
@property (nonatomic,retain) UIView* viewCallStatusBar; 				//@synthesize viewCallStatusBar=_viewCallStatusBar - In the implementation block
@property (assign,nonatomic) UIButton* buttonCallStatusBarControl; 				//@synthesize buttonCallStatusBarControl=_buttonCallStatusBarControl - In the implementation block
@property (assign,nonatomic) UIView* viewCallStatusBarLabelsCentering; 				//@synthesize viewCallStatusBarLabelsCentering=_viewCallStatusBarLabelsCentering - In the implementation block
@property (assign,nonatomic) UILabel* labelCallStatusBarTitle; 				//@synthesize labelCallStatusBarTitle=_labelCallStatusBarTitle - In the implementation block
@property (assign,nonatomic) UILabel* labelCallStatusBarDuration; 				//@synthesize labelCallStatusBarDuration=_labelCallStatusBarDuration - In the implementation block
@property (nonatomic,retain) UIView* viewVoiceCall; 				//@synthesize viewVoiceCall=_viewVoiceCall - In the implementation block
@property (assign,nonatomic) UIButton* networkUnstableMessageButton; 				//@synthesize networkUnstableMessageButton=_networkUnstableMessageButton - In the implementation block
@property (assign,nonatomic) UIView* viewCentering; 				//@synthesize viewCentering=_viewCentering - In the implementation block
@property (assign,nonatomic) UIView* viewCallInfo; 				//@synthesize viewCallInfo=_viewCallInfo - In the implementation block
@property (assign,nonatomic) UIImageView* imageViewThumbnail; 				//@synthesize imageViewThumbnail=_imageViewThumbnail - In the implementation block
@property (assign,nonatomic) UIImageView* imageViewThumbnailShadowImage; 				//@synthesize imageViewThumbnailShadowImage=_imageViewThumbnailShadowImage - In the implementation block
@property (assign,nonatomic) UILabel* labelName; 				//@synthesize labelName=_labelName - In the implementation block
@property (assign,nonatomic) UILabel* labelCallDuration; 				//@synthesize labelCallDuration=_labelCallDuration - In the implementation block
@property (assign,nonatomic) UIButton* buttonMinimize; 				//@synthesize buttonMinimize=_buttonMinimize - In the implementation block
@property (assign,nonatomic) UIView* viewCallingButtons; 				//@synthesize viewCallingButtons=_viewCallingButtons - In the implementation block
@property (assign,nonatomic) UIButton* buttonMute; 				//@synthesize buttonMute=_buttonMute - In the implementation block
@property (assign,nonatomic) UIButton* buttonSpeaker; 				//@synthesize buttonSpeaker=_buttonSpeaker - In the implementation block
@property (assign,nonatomic) UIButton* buttonCallEnd; 				//@synthesize buttonCallEnd=_buttonCallEnd - In the implementation block
@property (assign,nonatomic) UIButton* buttonVideoCall; 				//@synthesize buttonVideoCall=_buttonVideoCall - In the implementation block
@property (assign,nonatomic) UIView* viewIncomingButtons; 				//@synthesize viewIncomingButtons=_viewIncomingButtons - In the implementation block
@property (assign,nonatomic) UIButton* buttonReject; 				//@synthesize buttonReject=_buttonReject - In the implementation block
@property (assign,nonatomic) UIButton* buttonAccept; 				//@synthesize buttonAccept=_buttonAccept - In the implementation block
@property (nonatomic,retain) UIView* viewVideoCall; 				//@synthesize viewVideoCall=_viewVideoCall - In the implementation block
@property (assign,nonatomic) UIView* viewMainVideoContainer; 				//@synthesize viewMainVideoContainer=_viewMainVideoContainer - In the implementation block
@property (assign,nonatomic) UIView* viewSubVideoContainer; 				//@synthesize viewSubVideoContainer=_viewSubVideoContainer - In the implementation block
@property (assign,nonatomic) UIImageView* imageViewSubVideoCover; 				//@synthesize imageViewSubVideoCover=_imageViewSubVideoCover - In the implementation block
@property (assign,nonatomic) UIView* viewSubVideoOff; 				//@synthesize viewSubVideoOff=_viewSubVideoOff - In the implementation block
@property (assign,nonatomic) AMPVideoRenderView* viewLocalVideoRendering; 				//@synthesize viewLocalVideoRendering=_viewLocalVideoRendering - In the implementation block
@property (assign,nonatomic) AMPVideoRenderView* viewRemoteVideoRendering; 				//@synthesize viewRemoteVideoRendering=_viewRemoteVideoRendering - In the implementation block
@property (nonatomic,retain) AMPVideoRenderView* currentMainVideoRenderingView; 				//@synthesize currentMainVideoRenderingView=_currentMainVideoRenderingView - In the implementation block
@property (nonatomic,retain) AMPVideoRenderView* currentSubVideoRenderingView; 				//@synthesize currentSubVideoRenderingView=_currentSubVideoRenderingView - In the implementation block
@property (assign,nonatomic) UIView* viewVideoButtons; 				//@synthesize viewVideoButtons=_viewVideoButtons - In the implementation block
@property (assign,nonatomic) UIButton* buttonVideoMute; 				//@synthesize buttonVideoMute=_buttonVideoMute - In the implementation block
@property (assign,nonatomic) UIButton* buttonVideoEnd; 				//@synthesize buttonVideoEnd=_buttonVideoEnd - In the implementation block
@property (assign,nonatomic) UIButton* buttonVideoCameraOff; 				//@synthesize buttonVideoCameraOff=_buttonVideoCameraOff - In the implementation block
@property (assign,nonatomic) UIView* viewVideoCameraSwitchingButtonContainer; 				//@synthesize viewVideoCameraSwitchingButtonContainer=_viewVideoCameraSwitchingButtonContainer - In the implementation block
@property (assign,nonatomic) UIButton* buttonVideoCameraSwitching; 				//@synthesize buttonVideoCameraSwitching=_buttonVideoCameraSwitching - In the implementation block
@property (assign,nonatomic) UIImageView* imageViewVideoRotatableCameraSwitchingIcon; 				//@synthesize imageViewVideoRotatableCameraSwitchingIcon=_imageViewVideoRotatableCameraSwitchingIcon - In the implementation block
@property (assign,nonatomic) UIView* viewVideoMinimizingButtonContainer; 				//@synthesize viewVideoMinimizingButtonContainer=_viewVideoMinimizingButtonContainer - In the implementation block
@property (assign,nonatomic) UIButton* buttonVideoMinimizing; 				//@synthesize buttonVideoMinimizing=_buttonVideoMinimizing - In the implementation block
@property (assign,nonatomic) UIImageView* imageViewVideoRotatableMinimizingIcon; 				//@synthesize imageViewVideoRotatableMinimizingIcon=_imageViewVideoRotatableMinimizingIcon - In the implementation block
@property (assign,nonatomic) UIView* viewVideoEnding; 				//@synthesize viewVideoEnding=_viewVideoEnding - In the implementation block
@property (assign,nonatomic) UIView* viewVideoEndingPopup; 				//@synthesize viewVideoEndingPopup=_viewVideoEndingPopup - In the implementation block
@property (assign,nonatomic) UIImageView* imageViewVideoEndingPopupIcon; 				//@synthesize imageViewVideoEndingPopupIcon=_imageViewVideoEndingPopupIcon - In the implementation block
@property (assign,nonatomic) UILabel* labelVideoEndingPopup; 				//@synthesize labelVideoEndingPopup=_labelVideoEndingPopup - In the implementation block
@property (assign,nonatomic) UIImageView* imageViewVideoRotatableMuteIcon; 				//@synthesize imageViewVideoRotatableMuteIcon=_imageViewVideoRotatableMuteIcon - In the implementation block
@property (assign,nonatomic) UIImageView* imageViewVideoRotatableEndIcon; 				//@synthesize imageViewVideoRotatableEndIcon=_imageViewVideoRotatableEndIcon - In the implementation block
@property (assign,nonatomic) UIImageView* imageViewVideoRotatableCameraIcon; 				//@synthesize imageViewVideoRotatableCameraIcon=_imageViewVideoRotatableCameraIcon - In the implementation block
@property (assign,nonatomic) UIImageView* imageViewVideoRotatableCameraOffIcon; 				//@synthesize imageViewVideoRotatableCameraOffIcon=_imageViewVideoRotatableCameraOffIcon - In the implementation block
@property (nonatomic,retain) UIView* viewVideoCallingAccept; 				//@synthesize viewVideoCallingAccept=_viewVideoCallingAccept - In the implementation block
@property (assign,nonatomic) UIButton* buttonVideoCallingMinimizing; 				//@synthesize buttonVideoCallingMinimizing=_buttonVideoCallingMinimizing - In the implementation block
@property (assign,nonatomic) UIButton* buttonVideoCallingAcceptEnd; 				//@synthesize buttonVideoCallingAcceptEnd=_buttonVideoCallingAcceptEnd - In the implementation block
@property (assign,nonatomic) UIButton* buttonVideoCallingAcceptVoice; 				//@synthesize buttonVideoCallingAcceptVoice=_buttonVideoCallingAcceptVoice - In the implementation block
@property (assign,nonatomic) UIButton* buttonVideoCallingAcceptVideo; 				//@synthesize buttonVideoCallingAcceptVideo=_buttonVideoCallingAcceptVideo - In the implementation block
@property (assign,nonatomic) UILabel* labelVideoCallingName; 				//@synthesize labelVideoCallingName=_labelVideoCallingName - In the implementation block
@property (assign,nonatomic) UILabel* labelVideoCallingCall; 				//@synthesize labelVideoCallingCall=_labelVideoCallingCall - In the implementation block
@property (assign,nonatomic) UIView* viewVideoCallingProfile; 				//@synthesize viewVideoCallingProfile=_viewVideoCallingProfile - In the implementation block
@property (assign,nonatomic) UIImageView* imageViewVideoCallingBgImage; 				//@synthesize imageViewVideoCallingBgImage=_imageViewVideoCallingBgImage - In the implementation block
@property (assign,nonatomic) UIImageView* imageViewVideoCallingProfileImage; 				//@synthesize imageViewVideoCallingProfileImage=_imageViewVideoCallingProfileImage - In the implementation block
@property (assign,nonatomic) UIView* viewVideoNetworkStatus; 				//@synthesize viewVideoNetworkStatus=_viewVideoNetworkStatus - In the implementation block
@property (assign,nonatomic) UIView* viewVideoNetworkStatusCentered; 				//@synthesize viewVideoNetworkStatusCentered=_viewVideoNetworkStatusCentered - In the implementation block
@property (assign,nonatomic) UIImageView* imageViewVideoNetworkBGImage; 				//@synthesize imageViewVideoNetworkBGImage=_imageViewVideoNetworkBGImage - In the implementation block
@property (assign,nonatomic) UIImageView* imageViewVideoNetworkStatusIcon; 				//@synthesize imageViewVideoNetworkStatusIcon=_imageViewVideoNetworkStatusIcon - In the implementation block
@property (assign,nonatomic) UILabel* labelVideoNetworkStatus; 				//@synthesize labelVideoNetworkStatus=_labelVideoNetworkStatus - In the implementation block
@property (assign,nonatomic) UIView* viewMessagePopup; 				//@synthesize viewMessagePopup=_viewMessagePopup - In the implementation block
@property (assign,nonatomic) UIImageView* imageViewMessagePopupBackground; 				//@synthesize imageViewMessagePopupBackground=_imageViewMessagePopupBackground - In the implementation block
@property (assign,nonatomic) UILabel* labelMessagePopup; 				//@synthesize labelMessagePopup=_labelMessagePopup - In the implementation block
@property (assign,nonatomic) UIImageView* imageViewMessagePopupIcon; 				//@synthesize imageViewMessagePopupIcon=_imageViewMessagePopupIcon - In the implementation block
@property (assign,nonatomic) unsigned videoViewLayout; 				//@synthesize videoViewLayout=_videoViewLayout - In the implementation block
@property (nonatomic,retain) UIView* viewVideoUserGuide; 				//@synthesize viewVideoUserGuide=_viewVideoUserGuide - In the implementation block
@property (assign,nonatomic) UIImageView* imageViewVideoUserGuideSubVideoEffect; 				//@synthesize imageViewVideoUserGuideSubVideoEffect=_imageViewVideoUserGuideSubVideoEffect - In the implementation block
@property (assign,nonatomic) UILabel* labelVideoUserGuideSubVideoTooltip; 				//@synthesize labelVideoUserGuideSubVideoTooltip=_labelVideoUserGuideSubVideoTooltip - In the implementation block
@property (assign,nonatomic) UILabel* labelVideoUserGuideMinimizingButtonTooltip; 				//@synthesize labelVideoUserGuideMinimizingButtonTooltip=_labelVideoUserGuideMinimizingButtonTooltip - In the implementation block
@property (assign,nonatomic) UIView* viewVideoUserGuideTapScreenTooltipCentered; 				//@synthesize viewVideoUserGuideTapScreenTooltipCentered=_viewVideoUserGuideTapScreenTooltipCentered - In the implementation block
@property (assign,nonatomic) UIImageView* imageViewVideoUserGuideTapScreenTooltipIcon; 				//@synthesize imageViewVideoUserGuideTapScreenTooltipIcon=_imageViewVideoUserGuideTapScreenTooltipIcon - In the implementation block
@property (assign,nonatomic) UILabel* labelVideoUserGuideTapScreenTooltip; 				//@synthesize labelVideoUserGuideTapScreenTooltip=_labelVideoUserGuideTapScreenTooltip - In the implementation block
@property (assign,nonatomic) BOOL animatingVideoControlsVisibility; 				//@synthesize animatingVideoControlsVisibility=_animatingVideoControlsVisibility - In the implementation block
@property (assign,nonatomic) BOOL videoControlsHidden; 				//@synthesize videoControlsHidden=_videoControlsHidden - In the implementation block
@property (nonatomic,retain) id orientationObserver; 				//@synthesize orientationObserver=_orientationObserver - In the implementation block
@property (nonatomic,retain) NLCallCustomAlertView* callAlertView; 				//@synthesize callAlertView=_callAlertView - In the implementation block
@property (assign,nonatomic) int localVideoViewContentMode; 				//@synthesize localVideoViewContentMode=_localVideoViewContentMode - In the implementation block
@property (assign,nonatomic) int remoteVideoViewContentMode; 				//@synthesize remoteVideoViewContentMode=_remoteVideoViewContentMode - In the implementation block
-(void)updateCallDurationView:(BOOL)arg1;
-(void)showVoiceCallingView;
-(void)updateCallViewModes:(unsigned)arg1;
-(void)updateCallingUser:(id)arg1;
-(void)updateAcceptCall;
-(void)hideMesssgePopupAnimated:(BOOL)arg1;
-(void)showMessagePopup:(int)arg1 animated:(BOOL)arg2;
-(void)setUserGuideHidden:(BOOL)arg1 animated:(BOOL)arg2;
-(void)presentNetworkStatus:(int)arg1;
-(void)showCallStatusBarDutation:(double)arg1 isInit:(BOOL)arg2;
-(void)processOnEnteringBackground;
-(void)processOnEnteringForeground;
-(void)processOnMinimizingCallView;
-(void)processOnMaximizingCallView;
-(void)updateCallViewErrorNotSupproted;
-(void)updateSpeakerButton;
-(void)updateMuteButton;
-(void)resetViews;
-(void)updateViewNetworkStatusSetHidden:(BOOL)arg1;
-(void)setVideoViewLayout:(unsigned)arg1;
-(void)initViewController;
-(void)initSetting;
-(void)initContents;
-(void)initSubviews;
-(void)setLabelName:(id)arg1;
-(void)configureNameLabel:(id)arg1;
-(void)prepareLocalizedStrings;
-(void)layoutCallStatusBar;
-(void)_toggleM:(id)arg1;
-(void)_toggleS:(id)arg1;
-(void)showCallStatusBarDutation:(id)arg1;
-(void)minimizeButtonPressed:(id)arg1;
-(void)callStatusBarControlTouched:(id)arg1;
-(void)receivedResultCodeAMPCallEventTypeWaitAccept;
-(void)receivedResultCodeAMPCallEventTypeOfferNewCall;
-(void)receivedResultCodeAMPCallEventTypeConnected;
-(void)setViewCallStatusBar:(id)arg1;
-(void)configureSubviews;
-(void)configureLoadingView:(id)arg1;
-(void)configureThumbnailImageView:(id)arg1;
-(void)setOrientationObserver:(id)arg1;
-(void)setLabelCallDuration:(id)arg1;
-(void)layoutCallInfoView;
-(void)layoutCallingView:(id)arg1;
-(void)layoutIncomingView:(id)arg1;
-(void)layoutVideoCallButtons;
-(void)layoutCenteringView:(id)arg1;
-(void)layoutNetworkUnstableMessage:(id)arg1;
-(void)layoutMinimizeButton:(id)arg1;
-(void)layoutVideoCallEndingView:(id)arg1;
-(void)layoutSubVideoContainerView:(id)arg1;
-(void)layoutCaptureVideoRenderView:(id)arg1;
-(void)layoutRemoteVideoRenderingView:(id)arg1;
-(void)layoutVideoNetworkStatusView:(id)arg1;
-(void)layoutMessagePopupView;
-(void)layoutVideoUserGuideSubVideoTooltipLabel:(id)arg1;
-(void)layoutVideoUserGuideMinimizingButtonTooltipLabel:(id)arg1;
-(void)layoutVideoUserGuideTapScreenTooltipCenteredView:(id)arg1;
-(void)layoutVideoProfileView;
-(void)layoutAcceptingVideoButtons;
-(void)layoutNameLabel;
-(void)layoutCallDurationLabel;
-(void)layoutAccpetingVoiceView;
-(void)layoutVoiceCallingView;
-(void)layoutAcceptingVideoView;
-(void)layoutVideoCallingView;
-(void)resetSubVideoContainerViewPosition;
-(void)showVideoCallingView;
-(void)showAcceptingVideoView;
-(void)showAcceptingVoiceView;
-(void)resetViewFrame;
-(void)updateViewBySetupVoiceCall:(BOOL)arg1 withFriendId:(id)arg2;
-(int)interfaceOrientationFromCurrentDeviceOrientation;
-(void)updateViewBySetupVideoCall:(BOOL)arg1;
-(void)hideVideoCallAcceptingPopup;
-(void)showVideoCallAcceptingPopup;
-(void)showVideoControls;
-(void)hideVideoControlsAutomaticallyAfterDelay:(double)arg1;
-(void)configureNetworkUnstableMessageButton:(id)arg1;
-(void)configureCenteringView:(id)arg1;
-(void)configureThumbnailShadowImageView:(id)arg1;
-(void)configureCallDurationLabel:(id)arg1;
-(void)configureMuteButton:(id)arg1;
-(void)configureSpeakerButton:(id)arg1;
-(void)configureVideoCallButton:(id)arg1;
-(void)configureCallEndButton:(id)arg1;
-(void)configureRejectButton:(id)arg1;
-(void)configureAcceptButton:(id)arg1;
-(void)configureMinimizeButton:(id)arg1;
-(void)configureCallStatusBarControl:(id)arg1;
-(void)configureCallStatusBarLabelsCenteringView:(id)arg1;
-(void)configureCallStatusBarTitleLabel:(id)arg1;
-(void)configureCallStatusBarDurationLabel:(id)arg1;
-(void)configureCameraSwitchingButton:(id)arg1;
-(void)configureInconmingButtonsView:(id)arg1;
-(void)configureVideoCallEndingInfoLabel:(id)arg1;
-(void)configureVideoMuteButton:(id)arg1;
-(void)configureVideoEndButton:(id)arg1;
-(void)configureVideoCameraOffButton:(id)arg1;
-(void)configureRemoteVideoRenderingView:(id)arg1;
-(void)configureLocalVideoRenderingView:(id)arg1;
-(void)configureVideoCallMinimizingButton:(id)arg1;
-(void)configureVideoNetworkStatusLabel:(id)arg1;
-(void)configureVideoNetworkStatusCenteredView:(id)arg1;
-(void)configureVideoNetworkBGImageView:(id)arg1;
-(void)configureMainVideoContainerView:(id)arg1;
-(void)configureSubVideoContainerView:(id)arg1;
-(void)configureMessagePopupBackgroundImageView:(id)arg1;
-(void)configureMessagePopupLabel:(id)arg1;
-(void)configureVideoUserGuideView:(id)arg1;
-(void)configureVideoUserGuideSubVideoTooltipLabel:(id)arg1;
-(void)configureVideoUserGuideMinimizingButtonTooltipLabel:(id)arg1;
-(void)configureVideoUserGuideTapScreenTooltipLabel:(id)arg1;
-(void)configureVideoCallingNameLabel:(id)arg1;
-(void)configureVideoCallingCallLabel:(id)arg1;
-(void)configureVideoCallingBgImageView:(id)arg1;
-(void)configureVideoCallingProfileImageView:(id)arg1;
-(void)configureVideoCallingAcceptVoiceButton:(id)arg1;
-(void)configureVideoCallingAcceptVideoButton:(id)arg1;
-(void)markContentModeOfRenderingView:(id)arg1;
-(void)_configureBackgroundImagesOfButton:(id)arg1;
-(void)recognizeDoubleTapGestureOnMainVideoView:(id)arg1;
-(void)recognizeSingleTapGestureOnMainVideoView:(id)arg1;
-(void)recognizePinchGestureOnMainVideoView:(id)arg1;
-(void)recognizeSingleTapGestureOnSubVideoView:(id)arg1;
-(void)recognizePanGestureOnSubVideoView:(id)arg1;
-(void)videoUserGuideCloseButtonTapped:(id)arg1;
-(void)_configureEachVideoUserGuideLabel:(id)arg1;
-(void)configureVideoCallingAcceptEndOnlyButton:(id)arg1;
-(void)configureVideoCallingAcceptEndButton:(id)arg1;
-(void)_configureEachCallButton:(id)arg1;
-(void)prepareUserGuideView;
-(void)setCurrentMainVideoRenderingView:(id)arg1;
-(void)setCurrentSubVideoRenderingView:(id)arg1;
-(void)toggleVideoControlsVisibility;
-(void)setVideoControlsHidden:(BOOL)arg1 animated:(BOOL)arg2;
-(void)setLocalVideoViewContentMode:(int)arg1;
-(void)setRemoteVideoViewContentMode:(int)arg1;
-(void)exchangeMainAndSubVideoView;
-(void)resetViewsOnVoiceCall;
-(void)resetViewsOnVideoCall;
-(void)changeUIForInterfaceOrientation:(int)arg1;
-(void)configureContentModeOfRenderingViews;
-(BOOL)shouldChangeOrientation;
-(float)requiredRotationAngleForInterfaceOrientation:(int)arg1;
-(void)_toggleO:(id)arg1;
-(void)callEndButtonPressed:(id)arg1;
-(void)storeContentModeOfRenderingViews;
-(void)showName:(id)arg1;
-(void)animateVideoCallingProfile;
-(void)setAnimatingVideoControlsVisibility:(BOOL)arg1;
-(void)setVideoControlsHidden:(BOOL)arg1;
-(void)hideVideoControlsAutomaticallyWithAnimation;
-(void)setGestureRecognizersEnabled:(BOOL)arg1;
-(void)beginBlinkAnimationOnView:(id)arg1;
-(void)finishBlinkAnimationOnView:(id)arg1;
-(void)rejectButtonPressed:(id)arg1;
-(void)acceptButtonPressed:(id)arg1;
-(void)acceptVoiceOnlyButtonPressed:(id)arg1;
-(void)touchDownMuteButton:(id)arg1;
-(void)touchDownSpeakerButton:(id)arg1;
-(void)touchDownVideoCallButton:(id)arg1;
-(void)cameraSwitchingButtonTapped:(id)arg1;
-(void)touchDownCameraOffButton:(id)arg1;
-(void)videoCallEndButtonTapped:(id)arg1;
-(void)setViewLoading:(id)arg1;
-(void)setNetworkStatusString:(id)arg1;
-(void)setConnectingString:(id)arg1;
-(void)setCallingString:(id)arg1;
-(void)setReceivedVideoCallString:(id)arg1;
-(void)setReceivedVoiceCallString:(id)arg1;
-(void)setButtonCallStatusBarControl:(id)arg1;
-(void)setViewCallStatusBarLabelsCentering:(id)arg1;
-(void)setLabelCallStatusBarTitle:(id)arg1;
-(void)setLabelCallStatusBarDuration:(id)arg1;
-(void)setViewVoiceCall:(id)arg1;
-(void)setNetworkUnstableMessageButton:(id)arg1;
-(void)setViewCentering:(id)arg1;
-(void)setViewCallInfo:(id)arg1;
-(void)setImageViewThumbnail:(id)arg1;
-(void)setImageViewThumbnailShadowImage:(id)arg1;
-(void)setButtonMinimize:(id)arg1;
-(void)setViewCallingButtons:(id)arg1;
-(void)setButtonMute:(id)arg1;
-(void)setButtonSpeaker:(id)arg1;
-(void)setButtonCallEnd:(id)arg1;
-(void)setButtonVideoCall:(id)arg1;
-(void)setViewIncomingButtons:(id)arg1;
-(void)setButtonReject:(id)arg1;
-(void)setButtonAccept:(id)arg1;
-(void)setViewVideoCall:(id)arg1;
-(void)setViewMainVideoContainer:(id)arg1;
-(void)setViewSubVideoContainer:(id)arg1;
-(void)setImageViewSubVideoCover:(id)arg1;
-(void)setViewSubVideoOff:(id)arg1;
-(void)setViewLocalVideoRendering:(id)arg1;
-(void)setViewRemoteVideoRendering:(id)arg1;
-(void)setViewVideoButtons:(id)arg1;
-(void)setButtonVideoMute:(id)arg1;
-(void)setButtonVideoEnd:(id)arg1;
-(void)setButtonVideoCameraOff:(id)arg1;
-(void)setViewVideoCameraSwitchingButtonContainer:(id)arg1;
-(void)setButtonVideoCameraSwitching:(id)arg1;
-(void)setImageViewVideoRotatableCameraSwitchingIcon:(id)arg1;
-(void)setViewVideoMinimizingButtonContainer:(id)arg1;
-(void)setButtonVideoMinimizing:(id)arg1;
-(void)setImageViewVideoRotatableMinimizingIcon:(id)arg1;
-(void)setViewVideoEnding:(id)arg1;
-(void)setViewVideoEndingPopup:(id)arg1;
-(void)setImageViewVideoEndingPopupIcon:(id)arg1;
-(void)setLabelVideoEndingPopup:(id)arg1;
-(void)setImageViewVideoRotatableMuteIcon:(id)arg1;
-(void)setImageViewVideoRotatableEndIcon:(id)arg1;
-(void)setImageViewVideoRotatableCameraIcon:(id)arg1;
-(void)setImageViewVideoRotatableCameraOffIcon:(id)arg1;
-(void)setViewVideoCallingAccept:(id)arg1;
-(void)setButtonVideoCallingMinimizing:(id)arg1;
-(void)setButtonVideoCallingAcceptEnd:(id)arg1;
-(void)setButtonVideoCallingAcceptVoice:(id)arg1;
-(void)setButtonVideoCallingAcceptVideo:(id)arg1;
-(void)setLabelVideoCallingName:(id)arg1;
-(void)setLabelVideoCallingCall:(id)arg1;
-(void)setViewVideoCallingProfile:(id)arg1;
-(void)setImageViewVideoCallingBgImage:(id)arg1;
-(void)setImageViewVideoCallingProfileImage:(id)arg1;
-(void)setViewVideoNetworkStatus:(id)arg1;
-(void)setViewVideoNetworkStatusCentered:(id)arg1;
-(void)setImageViewVideoNetworkBGImage:(id)arg1;
-(void)setImageViewVideoNetworkStatusIcon:(id)arg1;
-(void)setLabelVideoNetworkStatus:(id)arg1;
-(void)setViewMessagePopup:(id)arg1;
-(void)setImageViewMessagePopupBackground:(id)arg1;
-(void)setLabelMessagePopup:(id)arg1;
-(void)setImageViewMessagePopupIcon:(id)arg1;
-(void)setViewVideoUserGuide:(id)arg1;
-(void)setImageViewVideoUserGuideSubVideoEffect:(id)arg1;
-(void)setLabelVideoUserGuideSubVideoTooltip:(id)arg1;
-(void)setLabelVideoUserGuideMinimizingButtonTooltip:(id)arg1;
-(void)setViewVideoUserGuideTapScreenTooltipCentered:(id)arg1;
-(void)setImageViewVideoUserGuideTapScreenTooltipIcon:(id)arg1;
-(void)setLabelVideoUserGuideTapScreenTooltip:(id)arg1;
-(void)setCallAlertView:(id)arg1;
-(void)dealloc;
-(void)layoutSubviews;
-(BOOL)shouldAutorotate;
-(unsigned)supportedInterfaceOrientations;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2;
-(void)viewDidLoad;
-(void)updateLayout;
-(void).cxx_destruct;
@end