/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:14:13 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface NLCommonUILibrary : NSObject {
}
+(id)cellBorderColorStyle1ForRuleset:(id)arg1;
+(void)decorateRegistrationLabelStyle2:(id)arg1;
+(void)decorateRegistrationButtonStyle1:(id)arg1;
+(void)decorateRegistrationButtonStyle6:(id)arg1;
+(id)registrationCommonBgColor;
+(void)decorateRegistrationLabelStyle3:(id)arg1;
+(id)stickerShopNoResultLabel;
+(id)cellBackgroundViewStyle1;
+(id)selectedCellBackgroundViewStyle1;
+(void)decorateFriendAddInviteButton:(id)arg1 withTitle:(id)arg2;
+(id)cellBackgroundViewStyle1ForRuleset:(id)arg1;
+(id)selectedCellBackgroundViewStyle1ForRuleset:(id)arg1;
+(void)decorateRegistrationButtonStyle2:(id)arg1;
+(id)newBadge;
+(void)decorateProfileNoPhoneButton:(id)arg1 withTitle:(id)arg2 maximumWidth:(float)arg3;
+(void)decorateProfileHomeButton:(id)arg1 withTitle:(id)arg2 maximumWidth:(float)arg3;
+(void)decorateButtonWithHeaderViewStyle1:(id)arg1;
+(void)decorateRegistrationInputFieldStyle2:(id)arg1;
+(void)decorateRegistrationInputFieldStyle3:(id)arg1;
+(void)decorateStickerShopLabelStyle1:(id)arg1;
+(void)decorateRegistrationSeparatorLineStyle1:(id)arg1;
+(void)decorateFacebookConnectButtonStyle1:(id)arg1;
+(void)decorateChineseSNSButtonsView:(id)arg1;
+(void)decorateRegistrationButtonStyle5:(id)arg1;
+(void)decorateRegistrationLabelStyle15:(id)arg1;
+(void)decorateRegistrationInputFieldStyle4:(id)arg1;
+(void)decorateRegistrationLabelStyle1:(id)arg1;
+(void)decorateRegistrationLabelStyle16:(id)arg1;
+(void)decorateRegistrationLabelStyle17:(id)arg1;
+(void)decorateRegistrationButtonStyle8:(id)arg1;
+(void)decorateRegistrationButtonStyle9:(id)arg1;
+(void)decorateRegistrationInputFieldStyle1:(id)arg1;
+(void)decorateRegistrationCheckBoxStyle2:(id)arg1;
+(void)decorateRegistrationLabelStyle21:(id)arg1;
+(void)decorateRegistrationLabelStyle4:(id)arg1;
+(void)decorateRegistrationButtonStyle10:(id)arg1;
+(void)decorateRegistrationRoundedBoxStyle1:(id)arg1;
+(void)decorateRegistrationLabelStyle22:(id)arg1;
+(void)decorateRegistrationLabelStyle12:(id)arg1;
+(id)contentImageWithLabel:(id)arg1;
+(void)decorateRegistrationLabelStyle5:(id)arg1;
+(void)decorateRegistrationLabelStyle6:(id)arg1;
+(id)badgeStyle1WithText:(id)arg1;
+(id)badgeStyle2WithText:(id)arg1;
+(id)cellBorderColorStyle1;
+(void)decorateRegistrationLabelStyle20:(id)arg1;
+(void)decorateButtonCommonStyle:(id)arg1;
+(void)decorateRegistrationButtonStyle3:(id)arg1;
+(void)decorateVerticalContentLayoutOnButton:(id)arg1 imageAdjustment:(int)arg2 titleAdjustment:(int)arg3;
+(void)_decorate360ButtonsTextStyle1:(id)arg1;
+(id)badgeForNewPresentsCount:(int)arg1;
+(id)badgeStyle1WithNumber:(int)arg1;
+(id)badgeStyle2WithNumber:(int)arg1;
+(id)friendsCellBorderColor;
+(id)topBorderForCellBackground;
+(id)topBorderForSelectedCellBackground;
+(id)bottomBorderForCellBackground;
+(id)bottomBorderForSelectedCellBackground;
+(id)facebookConnectionButton;
+(void)decorateRegistrationButtonStyle4:(id)arg1;
+(void)decorateRegistrationButtonStyle11:(id)arg1;
+(void)decorateSNSIntegrateButtonStyle:(id)arg1 withSNSImage:(id)arg2;
+(void)decorateStickerShopButtonStyle1:(id)arg1;
+(void)decorateStickerShopButtonStyle2:(id)arg1;
+(void)decorateChannelRevokeButtonStyle2:(id)arg1;
+(void)decorateDeleteAccountButtonStyle:(id)arg1;
+(void)decorateDeleteAccountCancelButtonStyle:(id)arg1;
+(void)decorateCoinPopupButton:(id)arg1;
+(void)decorateRegistrationLabelStyle10:(id)arg1;
+(id)stickerManagementNoResultLabel;
+(void)decorateAccountVerifyTopLabel:(id)arg1;
+(void)decorateAccountVerifyLostEmailLabel:(id)arg1;
+(void)decorateCoinPopupLabel:(id)arg1;
+(void)decorateAuthorizingDesktopDescLabelStyle1:(id)arg1;
+(void)decorateSerialNumberLabel:(id)arg1;
+(void)decorateSerialNumberTextfield:(id)arg1;
+(void)decorateDownloadByteLabel:(id)arg1;
+(void)decorateWaitingForDownloadAtDownloadingView:(id)arg1;
+(void)decorateStickerDownloadButtonStyle1:(id)arg1;
+(void)decorateStickerDownloadButtonStyle2:(id)arg1;
+(void)decoratePrivacyPlusAddBtnButton:(id)arg1 withTitle:(id)arg2;
@end