/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:13:03 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface NLNeloManager : NSObject {
}
+(BOOL)isCustomLogEnabled;
+(void)markCustomLog:(id)arg1;
+(void)finishCustomLogging;
+(void)startCustomLogging;
+(void)setUserInfo;
+(void)initializeQuincy;
+(void)initializeNeloWithAppID:(id)arg1;
+(void)initializeTimer;
+(id)commonErrorMsg:(id)arg1;
+(id)defaultProfileInfo;
+(id)serverSettingsInfo;
+(void)logNetworkError:(id)arg1 location:(id)arg2;
+(void)logAuthorizationError:(id)arg1 location:(id)arg2;
+(void)logMessageDefineError:(id)arg1 location:(id)arg2;
+(void)logSystemError:(id)arg1 location:(id)arg2;
+(void)logFatalError:(id)arg1 location:(id)arg2;
+(void)initialize;
@end