/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:11:58 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface NLShakeSearchingView : UIView {
	NLShakeSearchingAnimationView* _animationView; 
	NSTimer* _animationTimer; 
	UIImageView* _iconView; 
	UILabel* _searchingLabel; 
}
-(id)initWithFrame:(CGRect)arg1;
-(void)dealloc;
-(void)drawRect:(CGRect)arg1;
-(void)layoutSubviews;
-(void).cxx_destruct;
@end