/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:14:43 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface NLStatusBarControllableViewController : NLViewController {
	BOOL _statusBarShouldBeHidden; 
	int _statusBarAnimation; 
}
@property (assign,nonatomic) BOOL statusBarShouldBeHidden; 				//@synthesize statusBarShouldBeHidden=_statusBarShouldBeHidden - In the implementation block
@property (assign,nonatomic) int statusBarAnimation; 				//@synthesize statusBarAnimation=_statusBarAnimation - In the implementation block
-(void)setStatusBarHidden:(BOOL)arg1 statusBarAnimation:(int)arg2;
-(void)setStatusBarShouldBeHidden:(BOOL)arg1;
-(void)setStatusBarAnimation:(int)arg1;
-(BOOL)prefersStatusBarHidden;
-(int)preferredStatusBarUpdateAnimation;
@end