/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:10:37 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol NLThemeListViewCellDelegate
@required
-(void)onTap(id):arg1 item(id):arg2 inCell(id):arg3 ;
-(void)onTap(id):arg1 item(id):arg2 inCell(id):arg3 ;
@end
