/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:14:06 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UIWebViewDelegate.h>

@interface RegistrationTermViewController : NLViewController <UIWebViewDelegate> {
	UILabel* _termsTitleLabel; 
	UIView* _termsView; 
	UIImageView* _termsBgView; 
	UIWebView* _termsContentView; 
	UIView* _privacyView; 
	UILabel* _privacyTitleLabel; 
	UIImageView* _privacyBgView; 
	UIWebView* _privacyContentView; 
	UILabel* _confirmLabel; 
	UIButton* _agreeButton; 
}
@property (assign,nonatomic) UILabel* termsTitleLabel; 				//@synthesize termsTitleLabel=_termsTitleLabel - In the implementation block
@property (assign,nonatomic) UIView* termsView; 				//@synthesize termsView=_termsView - In the implementation block
@property (assign,nonatomic) UIImageView* termsBgView; 				//@synthesize termsBgView=_termsBgView - In the implementation block
@property (assign,nonatomic) UIWebView* termsContentView; 				//@synthesize termsContentView=_termsContentView - In the implementation block
@property (assign,nonatomic) UIView* privacyView; 				//@synthesize privacyView=_privacyView - In the implementation block
@property (assign,nonatomic) UILabel* privacyTitleLabel; 				//@synthesize privacyTitleLabel=_privacyTitleLabel - In the implementation block
@property (assign,nonatomic) UIImageView* privacyBgView; 				//@synthesize privacyBgView=_privacyBgView - In the implementation block
@property (assign,nonatomic) UIWebView* privacyContentView; 				//@synthesize privacyContentView=_privacyContentView - In the implementation block
@property (assign,nonatomic) UILabel* confirmLabel; 				//@synthesize confirmLabel=_confirmLabel - In the implementation block
@property (assign,nonatomic) UIButton* agreeButton; 				//@synthesize agreeButton=_agreeButton - In the implementation block
-(void)configureNavigationItem;
-(void)openHelp:(id)arg1;
-(void)configureSubviews;
-(void)setupLocalizedStrings;
-(void)updateLayouts;
-(void)loadTermsContent;
-(void)setAgreeButton:(id)arg1;
-(void)agreeButtonPressed:(id)arg1;
-(void)setTermsTitleLabel:(id)arg1;
-(void)setTermsBgView:(id)arg1;
-(void)setTermsContentView:(id)arg1;
-(void)setPrivacyTitleLabel:(id)arg1;
-(void)setPrivacyBgView:(id)arg1;
-(void)setPrivacyContentView:(id)arg1;
-(void)setTermsView:(id)arg1;
-(void)setPrivacyView:(id)arg1;
-(void)setConfirmLabel:(id)arg1;
-(void)viewWillAppear:(BOOL)arg1;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2;
-(void)viewDidLoad;
-(void)viewDidUnload;
-(void)viewWillDisappear:(BOOL)arg1;
-(void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
-(BOOL)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(int)arg3;
@end