/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:13:13 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface SAGKImageLinkedAnswer : SAGKLinkedAnswer {
}
@property (nonatomic,copy) NSNumber* fileSize; 
@property (nonatomic,retain) SAUIImageResource* imageResource; 
@property (nonatomic,copy) NSArray* thumbnails; 
+(id)imageLinkedAnswer;
+(id)imageLinkedAnswerWithDictionary:(id)arg1 context:(id)arg2;
-(void)setFileSize:(id)arg1;
-(id)groupIdentifier;
-(id)encodedClassName;
-(void)setImageResource:(id)arg1;
-(void)setThumbnails:(id)arg1;
@end