/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:08:52 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <SAServerBoundCommand.h>

@interface SAPing : SABaseClientBoundCommand <SAServerBoundCommand> {
}
@property (nonatomic,@dynamic,copy) NSString* aceId; 
@property (nonatomic,@dynamic,copy) NSString* refId; 
+(id)pingWithDictionary:(id)arg1 context:(id)arg2;
+(id)ping;
-(id)groupIdentifier;
-(id)encodedClassName;
-(BOOL)requiresResponse;
@end