/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:08:52 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <SAAceSerializable.h>

@interface SARelatedName : AceObject <SAAceSerializable> {
}
@property (nonatomic,copy) NSString* label; 
@property (nonatomic,copy) NSString* name; 
+(id)relatedName;
+(id)relatedNameWithDictionary:(id)arg1 context:(id)arg2;
-(id)groupIdentifier;
-(void)setName:(id)arg1;
-(void)setLabel:(id)arg1;
-(id)encodedClassName;
@end