/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:09:31 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface SASetConnectionHeader : SABaseClientBoundCommand {
}
@property (nonatomic,copy) NSString* aceHostHeader; 
@property (assign,nonatomic) BOOL reconnectNow; 
+(id)setConnectionHeader;
+(id)setConnectionHeaderWithDictionary:(id)arg1 context:(id)arg2;
-(id)groupIdentifier;
-(id)encodedClassName;
-(BOOL)requiresResponse;
-(void)setAceHostHeader:(id)arg1;
-(void)setReconnectNow:(BOOL)arg1;
@end