/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:15:13 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <SAAceSerializable.h>

@interface SAWeatherCurrentConditions : AceObject <SAAceSerializable> {
}
@property (nonatomic,retain) SAWeatherBarometricPressure* barometricPressure; 
@property (nonatomic,retain) SAWeatherCondition* condition; 
@property (nonatomic,retain) NSNumber* dayOfWeek; 
@property (nonatomic,copy) NSString* dewPoint; 
@property (nonatomic,copy) NSString* feelsLike; 
@property (nonatomic,copy) NSString* heatIndex; 
@property (nonatomic,copy) NSString* moonPhase; 
@property (nonatomic,copy) NSString* percentHumidity; 
@property (nonatomic,retain) NSNumber* percentOfMoonFaceVisible; 
@property (nonatomic,copy) NSString* sunrise; 
@property (nonatomic,copy) NSString* sunset; 
@property (nonatomic,copy) NSString* temperature; 
@property (nonatomic,copy) NSString* timeOfObservation; 
@property (nonatomic,copy) NSString* timeZone; 
@property (nonatomic,copy) NSString* visibility; 
@property (nonatomic,copy) NSString* windChill; 
@property (nonatomic,retain) SAWeatherWindSpeed* windSpeed; 
+(id)currentConditions;
+(id)currentConditionsWithDictionary:(id)arg1 context:(id)arg2;
-(id)groupIdentifier;
-(void)setTimeZone:(id)arg1;
-(void)setCondition:(id)arg1;
-(void)setDayOfWeek:(id)arg1;
-(id)encodedClassName;
-(void)setBarometricPressure:(id)arg1;
-(void)setDewPoint:(id)arg1;
-(void)setFeelsLike:(id)arg1;
-(void)setHeatIndex:(id)arg1;
-(void)setMoonPhase:(id)arg1;
-(void)setPercentHumidity:(id)arg1;
-(void)setPercentOfMoonFaceVisible:(id)arg1;
-(void)setSunrise:(id)arg1;
-(void)setSunset:(id)arg1;
-(void)setTemperature:(id)arg1;
-(void)setTimeOfObservation:(id)arg1;
-(void)setWindChill:(id)arg1;
-(void)setWindSpeed:(id)arg1;
-(void)setVisibility:(id)arg1;
@end