/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:12:24 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol SticonImageComponentDelegate
@required
-(unsigned)sticonPKG_CODE;
-(unsigned)sticonCODE;
-(void)sticonDrawImage(id):arg1 PKG_CODE(unsigned):arg2 CODE(unsigned):arg3 ;
-(unsigned)sticonPKG_CODE;
-(unsigned)sticonCODE;
-(void)sticonDrawImage(id):arg1 PKG_CODE(unsigned):arg2 CODE(unsigned):arg3 ;
@end
