/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:11:59 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */

#import <UIAlertViewDelegate.h>
#import <NLStickerDownloadDelegate.h>

@interface StickerDownloadingViewController : NLViewController <UIAlertViewDelegate, NLStickerDownloadDelegate> {
	LineStickerPackage* package_; 
	UIImageView* thumbnailImageView_; 
	UILabel* packageNameLabel_; 
	UILabel* packageExpiredDateLabel_; 
	UIImageView* progressBar_; 
	NLActiveHitButton* stopButton_; 
	UIButton* confirmButton_; 
	UIAlertView* alertView_; 
	UILabel* downloadingLabel_; 
	UILabel* footerLabel_; 
	UIImageView* progressBG_; 
	BOOL hasCompleted; 
	BOOL isGoingToOpenAccountRegistrationView; 
	NSMutableArray* alertViews_; 
	UILabel* readyToDownloadLabel_; 
	NLSafeUnretainedObject* safeSelf; 
	BOOL isReceivedGiftProduct; 
	NSMutableDictionary* _downloadResults; 
}
@property (assign,nonatomic) BOOL isReceivedGiftProduct; 
@property (nonatomic,retain) NSMutableDictionary* downloadResults; 				//@synthesize downloadResults=_downloadResults - In the implementation block
-(id)initWithProduct:(id)arg1;
-(void)onClosePressed:(id)arg1;
-(void)onTapStopButton:(id)arg1;
-(void)stickerPackage:(id)arg1 downloaded:(float)arg2;
-(void)stickerPackageDownloadSuccess:(id)arg1;
-(void)stickerPackageDownloadFailed:(id)arg1;
-(void)updateViewToDownloadCompleteState;
-(void)setIsReceivedGiftProduct:(BOOL)arg1;
-(void)setDownloadResults:(id)arg1;
-(void)dealloc;
-(void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)loadView;
-(void)viewDidUnload;
-(void)viewDidAppear:(BOOL)arg1;
-(void)viewWillDisappear:(BOOL)arg1;
-(void)registerAccount:(id)arg1;
-(void).cxx_destruct;
@end