/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:10:09 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface ZBarCaptureReader : NSObject {
	AVCaptureVideoDataOutput* captureOutput; 
	id<ZBarCaptureDelegate> captureDelegate; 
	ZBarImageScanner* scanner; 
	CGRect scanCrop; 
	CGSize size; 
	float framesPerSecond; 
	BOOL enableCache; 
	struct dispatch_queue_s* queue; 
	ZBarImage* image; 
	ZBarCVImage* result; 
	unsigned state; 
	int framecnt; 
	unsigned width; 
	unsigned height; 
	unsigned long long t_frame; 
	unsigned long long t_fps; 
	unsigned long long t_scan; 
	float dt_frame; 
}
@property (nonatomic,copy) AVCaptureOutput* captureOutput; 
@property (assign,nonatomic) id<ZBarCaptureDelegate> captureDelegate; 
@property (nonatomic,copy) ZBarImageScanner* scanner; 
@property (assign,nonatomic) CGRect scanCrop; 
@property (nonatomic,copy) CGSize size; 
@property (assign,nonatomic,@dynamic) BOOL enableReader; 
@property (nonatomic,copy) float framesPerSecond; 
@property (assign,nonatomic) BOOL enableCache; 
-(void)initResult;
-(void)cropUpdate;
-(void)updateFPS:(id)arg1;
-(void)updateSize:(struct __CFDictionary*)arg1;
-(void)didReadNewSymbolsFromImage:(id)arg1;
-(void)willStartRunning;
-(void)willStopRunning;
-(void)captureFrame;
-(id)initWithImageScanner:(id)arg1;
-(void)setCaptureDelegate:(id)arg1;
-(void)setScanCrop:(CGRect)arg1;
-(void)setEnableCache:(BOOL)arg1;
-(void)setEnableReader:(BOOL)arg1;
-(void)didTrackSymbols:(id)arg1;
-(void)captureOutput:(id)arg1 didOutputSampleBuffer:(struct opaqueCMSampleBuffer*)arg2 fromConnection:(id)arg3;
-(void)dealloc;
-(id)init;
-(void)setSize:(CGSize)arg1;
-(void)flushCache;
-(void)setFramesPerSecond:(float)arg1;
@end