/*
 * This header is generated by weak_classdump 0.2
 * on Monday, June 23, 2014 at 9:09:46 PM Eastern European Summer Time
 * Operating System: Version 7.0.6 (Build 11B651)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@interface ZBarReaderViewController : UIViewController {
	ZBarImageScanner* scanner; 
	id<ZBarReaderDelegate> readerDelegate; 
	ZBarReaderView* readerView; 
	UIView* cameraOverlayView; 
	struct CGAffineTransform cameraViewTransform; 
	CGRect scanCrop; 
	unsigned supportedOrientationsMask; 
	int cameraDevice; 
	int cameraFlashMode; 
	int videoQuality; 
	BOOL showsZBarControls; 
	BOOL tracksSymbols; 
	BOOL enableCache; 
	ZBarHelpController* helpController; 
	UIView* controls; 
	UIView* shutter; 
	BOOL didHideStatusBar; 
	BOOL rotating; 
	ZBarCameraSimulator* cameraSim; 
}
@property (nonatomic,copy) ZBarImageScanner* scanner; 
@property (assign,nonatomic) id<ZBarReaderDelegate> readerDelegate; 
@property (assign,nonatomic) BOOL showsZBarControls; 
@property (assign,nonatomic) BOOL tracksSymbols; 
@property (assign,nonatomic) unsigned supportedOrientationsMask; 
@property (assign,nonatomic) CGRect scanCrop; 
@property (nonatomic,retain) UIView* cameraOverlayView; 
@property (assign,nonatomic) struct CGAffineTransform cameraViewTransform; 
@property (assign,nonatomic) int cameraDevice; 
@property (assign,nonatomic) int cameraFlashMode; 
@property (assign,nonatomic) int cameraCaptureMode; 
@property (assign,nonatomic) int videoQuality; 
@property (nonatomic,copy) ZBarReaderView* readerView; 
@property (assign,nonatomic) BOOL enableCache; 
@property (assign,nonatomic,@dynamic) int sourceType; 
@property (assign,nonatomic,@dynamic) BOOL allowsEditing; 
@property (assign,nonatomic,@dynamic) BOOL allowsImageEditing; 
@property (assign,nonatomic,@dynamic) BOOL showsCameraControls; 
@property (assign,nonatomic,@dynamic) BOOL showsHelpOnFail; 
@property (assign,nonatomic,@dynamic) int cameraMode; 
@property (assign,nonatomic,@dynamic) BOOL takesPicture; 
@property (assign,nonatomic,@dynamic) int maxScanDimension; 
+(BOOL)isSourceTypeAvailable:(int)arg1;
+(BOOL)isCameraDeviceAvailable:(int)arg1;
+(id)availableCaptureModesForCameraDevice:(int)arg1;
+(BOOL)isFlashAvailableForCameraDevice:(int)arg1;
-(void)setReaderDelegate:(id)arg1;
-(void)setShowsHelpOnFail:(BOOL)arg1;
-(void)setTracksSymbols:(BOOL)arg1;
-(void)readerView:(id)arg1 didReadSymbols:(id)arg2 fromImage:(id)arg3;
-(void)readerViewDidStart:(id)arg1;
-(void)initVideoQuality;
-(void)initControls;
-(void)showHelpWithReason:(id)arg1;
-(void)removeHelp:(id)arg1 done:(id)arg2 context:(void*)arg3;
-(void)helpControllerDidFinish:(id)arg1;
-(void)setTakesPicture:(BOOL)arg1;
-(void)setMaxScanDimension:(int)arg1;
-(void)setShowsZBarControls:(BOOL)arg1;
-(void)setSupportedOrientationsMask:(unsigned)arg1;
-(void)setScanCrop:(CGRect)arg1;
-(void)setEnableCache:(BOOL)arg1;
-(void)dealloc;
-(id)initWithCoder:(id)arg1;
-(id)init;
-(void)_init;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
-(void)viewWillAppear:(BOOL)arg1;
-(void)viewDidLoad;
-(void)loadView;
-(void)viewDidUnload;
-(void)viewWillDisappear:(BOOL)arg1;
-(void)viewDidDisappear:(BOOL)arg1;
-(void)willRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2;
-(void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
-(void)didRotateFromInterfaceOrientation:(int)arg1;
-(void)dismissModalViewControllerAnimated:(BOOL)arg1;
-(void)info;
-(void)cancel;
-(void)setCameraCaptureMode:(int)arg1;
-(void)setSourceType:(int)arg1;
-(void)setAllowsImageEditing:(BOOL)arg1;
-(void)setAllowsEditing:(BOOL)arg1;
-(void)setVideoQuality:(int)arg1;
-(void)setShowsCameraControls:(BOOL)arg1;
-(void)setCameraOverlayView:(id)arg1;
-(void)setCameraViewTransform:(struct CGAffineTransform)arg1;
-(void)takePicture;
-(void)setCameraDevice:(int)arg1;
-(void)setCameraFlashMode:(int)arg1;
-(void)cleanup;
-(void)setCameraMode:(int)arg1;
@end